CREATE OR REPLACE PROCEDURE "TEST_VSTSRedgate".prcDailyRateUpload
AS
    varmsg              varchar2(2000);
    dattemp             date;
    srNumber            number(3);

BEGIN
  varmsg := 'Select Max date from Rate table';
  SELECT MAX(DRAT_EFFECTIVE_DATE) INTO dattemp FROM TRTRAN012 
    where DRAT_RECORD_STATUS NOT IN(10200006);
  varmsg := 'Select Max serial number from Rate table';  
  SELECT MAX(DRAT_SERIAL_NUMBER) INTO srNumber FROM TRTRAN012 
    where DRAT_RECORD_STATUS NOT IN(10200006) AND DRAT_EFFECTIVE_DATE = dattemp;    
    
  varmsg := 'Inserting Data into Rate table';
  INSERT INTO TRTRAN012
    (DRAT_CURRENCY_CODE,DRAT_FOR_CURRENCY,DRAT_EFFECTIVE_DATE,DRAT_SERIAL_NUMBER,    
    DRAT_RATE_TIME,DRAT_TIME_STAMP,DRAT_RATE_DESCRIPTION,DRAT_SPOT_BID ,
    DRAT_SPOT_ASK ,DRAT_MONTH1_BID,DRAT_MONTH1_ASK,DRAT_MONTH2_BID,
    DRAT_MONTH2_ASK,DRAT_MONTH3_BID,DRAT_MONTH3_ASK,DRAT_MONTH6_BID,
    DRAT_MONTH6_ASK,DRAT_MONTH9_BID,DRAT_MONTH9_ASK,DRAT_MONTH12_BID,
    DRAT_MONTH12_ASK,DRAT_CREATE_DATE,DRAT_ADD_DATE,DRAT_ENTRY_DETAIL,
    DRAT_RECORD_STATUS,DRAT_MONTH4_BID,DRAT_MONTH4_ASK,DRAT_MONTH5_BID,
    DRAT_MONTH5_ASK,DRAT_MONTH7_BID,DRAT_MONTH7_ASK,DRAT_MONTH8_BID,
    DRAT_MONTH8_ASK,DRAT_MONTH10_BID,DRAT_MONTH10_ASK,DRAT_MONTH11_BID,
    DRAT_MONTH11_ASK)
  SELECT DRAT_CURRENCY_CODE,DRAT_FOR_CURRENCY,to_date(SYSDATE,'DD-MM-YY'),0,    
          DRAT_RATE_TIME,DRAT_TIME_STAMP,DRAT_RATE_DESCRIPTION,DRAT_SPOT_BID ,
          DRAT_SPOT_ASK ,DRAT_MONTH1_BID,DRAT_MONTH1_ASK,DRAT_MONTH2_BID,
          DRAT_MONTH2_ASK,DRAT_MONTH3_BID,DRAT_MONTH3_ASK,DRAT_MONTH6_BID,
          DRAT_MONTH6_ASK,DRAT_MONTH9_BID,DRAT_MONTH9_ASK,DRAT_MONTH12_BID,
          DRAT_MONTH12_ASK,DRAT_CREATE_DATE,DRAT_ADD_DATE,DRAT_ENTRY_DETAIL,
          DRAT_RECORD_STATUS,DRAT_MONTH4_BID,DRAT_MONTH4_ASK,DRAT_MONTH5_BID,
          DRAT_MONTH5_ASK,DRAT_MONTH7_BID,DRAT_MONTH7_ASK,DRAT_MONTH8_BID,
          DRAT_MONTH8_ASK,DRAT_MONTH10_BID,DRAT_MONTH10_ASK,DRAT_MONTH11_BID,
          DRAT_MONTH11_ASK 
  FROM TRTRAN012 WHERE DRAT_EFFECTIVE_DATE = dattemp
  AND DRAT_SERIAL_NUMBER = srNumber
  AND DRAT_RECORD_STATUS NOT IN(10200006);
commit;
exception 
when others then
varmsg:= varmsg;
rollback;
raise_application_error(-200001,varmsg);
end prcDailyRateUpload;
 
 
 
 
/