CREATE OR REPLACE procedure "TEST_VSTSRedgate".prcHedgingCost(asonDate in date,UserID in varchar2)
as
  numError          number(10);
  varOperation      GConst.gvarOperation%Type;
  varMessage        GConst.gvarMessage%Type;
  varError          GConst.gvarError%Type;
  datStart          date;
  datEnd            date;
  noDays            number;
  datLastmonth      date;
  datason           date;
  datTemp           date;
  numRate           number(15,6);
  numRate1          number(15,6);
  numRate2          number(15,6);
  numRate3          number(15,6);
begin 
  
  numRate  := fncGetRBIRefRate(asonDate,30400004); --This Month RBI RefRate
  numRate1 := fncGetRBIRefRate(last_day(add_months(asonDate,-1)),30400004); -- 1 Month old RBI Ref Rate
  numRate2 := fncGetRBIRefRate(last_day(add_months(asonDate,-2)),30400004); -- 2 Month old RBI Ref Rate
  delete from TRSYSTEM983_HEDGECOST;-- where HDCT_ASON_MONTH = TO_CHAR(asonDate,'MONYY');
  datStart := trunc(asonDate,'MONTH');
  datEnd := last_day(asonDate);
  noDays := datEnd - datStart;
  datLastmonth := datStart - 1;
  datason := datStart;
  FOR i IN 0..noDays 
  LOOP
    varOperation := 'Forward Deal processing ' || datason;
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_ASON_MONTH)
      SELECT DEAL_COMPANY_CODE,DEAL_LOCATION_CODE,DEAL_BACKUP_DEAL,DEAL_INIT_CODE,
      DEAL_BUY_SELL,DEAL_HEDGE_TRADE,DEAL_EXECUTE_DATE,DEAL_MATURITY_FROM,
      DEAL_MATURITY_DATE,DEAL_COUNTER_PARTY,
      PKGFOREXPROCESS.Fncgetoutstanding(Deal_Deal_Number, Deal_Serial_Number,Gconst.Utiltradedeal,Gconst.Amountfcy, datason),
      DEAL_EXCHANGE_RATE,DEAL_SPOT_RATE,DEAL_FORWARD_RATE,DEAL_MARGIN_RATE,0,0,0,
      DEAL_DEAL_NUMBER,'Forward',TO_CHAR(datStart,'MONYY'),1,1,'Forward',datason,
      DEAL_BASE_CURRENCY,DEAL_OTHER_CURRENCY,TO_CHAR(asonDate,'MONYY')
      from trtran001
      where  deal_execute_date <= datason
      and deal_hedge_trade in (GConst.HEDGEDEAL, GCONST.FTDEAL)
      and deal_company_code in (select usco_company_code from trsystem022a where usco_user_id =UserID)
      and deal_record_status in(GConst.STATUSENTRY, Gconst.STATUSAUTHORIZED, GConst.STATUSUPDATED)
      and ((deal_complete_date is null) or (deal_complete_date > datason))
      and deal_deal_type not in(25400001);
      varOperation := 'Option Deal processing ' || datason;      
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BUYCALL_RATE,HDCT_SELLCALL_RATE,HDCT_SELLPUT_RATE,
      HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_PREMIUM_RATE,HDCT_ASON_MONTH)
      SELECT COPT_COMPANY_CODE,COPT_LOCATION_CODE,COPT_BACKUP_DEAL,COPT_INIT_CODE,
      25399999,COPT_HEDGE_TRADE,COPT_EXECUTE_DATE,COPT_EXPIRY_DATE,
      COPT_MATURITY_DATE,COPT_COUNTER_PARTY,
      pkgForexProcess.fncGetOutstanding(COPT_DEAL_NUMBER,1,GConst.UTILOPTIONHEDGEDEAL,1,datason,null,1),
      0,COPT_SPOT_RATE,0,0,0,COPT_PREMIUM_AMOUNT,0,
      COPT_DEAL_NUMBER,'Option',TO_CHAR(datStart,'MONYY'),2,2,'Option',datason,
      fncGetOptionRate(COPT_DEAL_NUMBER,32400001,25300001),--BuyCall
      fncGetOptionRate(COPT_DEAL_NUMBER,32400001,25300002),--SellCall
      fncGetOptionRate(COPT_DEAL_NUMBER,32400002,25300002),--SellPut 
      COPT_BASE_CURRENCY,COPT_OTHER_CURRENCY,COPT_PREMIUM_RATE,TO_CHAR(asonDate,'MONYY')
      from trtran071 
      where copt_execute_date <=   datason       
      and ((copt_complete_date is null) or (copt_complete_date > datason))
      and copt_company_code in
      (select usco_company_code from trsystem022a where usco_user_id =UserID)
      and copt_record_status in (GConst.STATUSENTRY, Gconst.STATUSAUTHORIZED, GConst.STATUSUPDATED);
      datason := datason + 1;
  end loop;
    varOperation := 'New Option booked during the month';
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BUYCALL_RATE,HDCT_SELLCALL_RATE,HDCT_SELLPUT_RATE,
      HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_PREMIUM_RATE,HDCT_ASON_MONTH)
      SELECT COPT_COMPANY_CODE,COPT_LOCATION_CODE,COPT_BACKUP_DEAL,COPT_INIT_CODE,
      25399999,COPT_HEDGE_TRADE,COPT_EXECUTE_DATE,COPT_EXPIRY_DATE,
      COPT_MATURITY_DATE,COPT_COUNTER_PARTY,
      pkgForexProcess.fncGetOutstanding(COPT_DEAL_NUMBER,1,GConst.UTILOPTIONHEDGEDEAL,1,datason,null,1),
      0,COPT_SPOT_RATE,0,0,0,decode(COPT_PREMIUM_STATUS,33200002,COPT_PREMIUM_AMOUNT * -1,COPT_PREMIUM_AMOUNT),0,
      COPT_DEAL_NUMBER,'New Option',TO_CHAR(datStart,'MONYY'),3,3,'New Option',datason,
      fncGetOptionRate(COPT_DEAL_NUMBER,32400001,25300001),--BuyCall
      fncGetOptionRate(COPT_DEAL_NUMBER,32400001,25300002),--SellCall
      fncGetOptionRate(COPT_DEAL_NUMBER,32400002,25300002),--SellPut
      COPT_BASE_CURRENCY,COPT_OTHER_CURRENCY,copt_premium_rate,TO_CHAR(asonDate,'MONYY')
      from trtran071 
      where copt_execute_date between datStart and datEnd     
--      and ((copt_complete_date is null) or (copt_complete_date > datason))
      and copt_company_code in
      (select usco_company_code from trsystem022a where usco_user_id =UserID)
      and copt_record_status in (GConst.STATUSENTRY, Gconst.STATUSAUTHORIZED, GConst.STATUSUPDATED);
      
    varOperation := 'Last month Option Deal processing ' || datLastmonth;      
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BUYCALL_RATE,HDCT_SELLCALL_RATE,HDCT_SELLPUT_RATE,
      HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_PREMIUM_RATE,HDCT_ASON_MONTH)
      SELECT COPT_COMPANY_CODE,COPT_LOCATION_CODE,COPT_BACKUP_DEAL,COPT_INIT_CODE,
      25399999,COPT_HEDGE_TRADE,COPT_EXECUTE_DATE,COPT_EXPIRY_DATE,
      COPT_MATURITY_DATE,COPT_COUNTER_PARTY,
      pkgForexProcess.fncGetOutstanding(COPT_DEAL_NUMBER,1,GConst.UTILOPTIONHEDGEDEAL,1,datason,null,1),
      0,COPT_SPOT_RATE,0,0,0,COPT_PREMIUM_AMOUNT,0,
      COPT_DEAL_NUMBER,'Last month Option',TO_CHAR(datStart,'MONYY'),4,2,'Last moth Option',datason,
      fncGetOptionRate(COPT_DEAL_NUMBER,32400001,25300001),--BuyCall
      fncGetOptionRate(COPT_DEAL_NUMBER,32400001,25300002),--SellCall
      fncGetOptionRate(COPT_DEAL_NUMBER,32400002,25300002),--SellPut  
      COPT_BASE_CURRENCY,COPT_OTHER_CURRENCY,copt_premium_rate,TO_CHAR(asonDate,'MONYY')
      from trtran071 
      where copt_execute_date <=   datLastmonth       
      and ((copt_complete_date is null) or (copt_complete_date > datLastmonth))
      and copt_company_code in
      (select usco_company_code from trsystem022a where usco_user_id =UserID)
      and copt_record_status in (GConst.STATUSENTRY, Gconst.STATUSAUTHORIZED, GConst.STATUSUPDATED);
      
    varOperation := 'Option Expired/Excersied/Cancelled during the month';
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BUYCALL_RATE,HDCT_SELLCALL_RATE,HDCT_SELLPUT_RATE,
      HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_PREMIUM_RATE,HDCT_ASON_MONTH,HGCT_CANCEL_PREMIUM,HDCT_CANCEL_RATE)
      SELECT COPT_COMPANY_CODE,COPT_LOCATION_CODE,COPT_BACKUP_DEAL,COPT_INIT_CODE,
      25399999,COPT_HEDGE_TRADE,COPT_EXECUTE_DATE,COPT_EXPIRY_DATE,
      COPT_MATURITY_DATE,COPT_COUNTER_PARTY,COPT_BASE_AMOUNT,0,COPT_SPOT_RATE,0,0,CORV_BASE_AMOUNT,COPT_PREMIUM_AMOUNT,CORV_EXERCISE_TYPE,
      COPT_DEAL_NUMBER,'Option Excersied',TO_CHAR(datStart,'MONYY'),3,3,
      'Option '||pkgreturncursor.fncgetdescription(CORV_EXERCISE_TYPE,2),datason,
      fncGetOptionRate(COPT_DEAL_NUMBER,32400001,25300001),--BuyCall
      fncGetOptionRate(COPT_DEAL_NUMBER,32400001,25300002),--SellCall
      fncGetOptionRate(COPT_DEAL_NUMBER,32400002,25300002),--SellPut  
      COPT_BASE_CURRENCY,COPT_OTHER_CURRENCY,copt_premium_rate,TO_CHAR(asonDate,'MONYY'),
      CORV_PREMIUM_RATE,corv_exercise_rate
      From  trtran071
        JOIN TRTRAN072A 
        ON COPT_DEAL_NUMBER         = COSM_DEAL_NUMBER
        AND COSM_SERIAL_NUMBER = 1
        AND COSM_RECORD_STATUS NOT IN(10200005,10200006)
        JOIN TRTRAN072
        ON COSU_DEAL_NUMBER         = COSM_DEAL_NUMBER
        AND COSU_SERIAL_NUMBER      = COSM_SERIAL_NUMBER
        AND COSU_RECORD_STATUS NOT IN(10200005,10200006)
        AND COSU_SERIAL_NUMBER = 1
        JOIN TRTRAN073
        ON copt_deal_number = corv_deal_number 
        AND Corv_Record_Status Not In (10200005,10200006)
        AND corv_exercise_date  between datStart and datEnd
        WHERE copt_record_status between 10200001 and 10200004;    
    varOperation := 'Forward Cancel/Early Utilisation during the month';
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BUYCALL_RATE,HDCT_SELLCALL_RATE,HDCT_SELLPUT_RATE,
      HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_PREMIUM_RATE,HDCT_CANCEL_RATE,HDCT_CANCEL_SPOT,
      HDCT_CANCEL_FORWARD,HDCT_CANCEL_MARGIN,HDCT_CANCEL_DATE,HDCT_PROFIT_LOSS,HDCT_ASON_MONTH)
      SELECT DEAL_COMPANY_CODE,DEAL_LOCATION_CODE,DEAL_BACKUP_DEAL,DEAL_INIT_CODE,
      DEAL_BUY_SELL,DEAL_HEDGE_TRADE,DEAL_EXECUTE_DATE,DEAL_MATURITY_FROM,
      DEAL_MATURITY_DATE,DEAL_COUNTER_PARTY,DEAL_BASE_AMOUNT,0,0,0,0,CDEL_CANCEL_AMOUNT,0,0,
      DEAL_DEAL_NUMBER,'Forward Cancel',TO_CHAR(datStart,'MONYY'),3,3,
      'Forward '||pkgreturncursor.fncgetdescription(DEAL_COMPANY_CODE,2),datason,
      0,0,0, DEAL_BASE_CURRENCY,DEAL_OTHER_CURRENCY,0,CDEL_CANCEL_RATE,A.CDEL_SPOT_RATE,A.CDEL_FORWARD_RATE,
      A.CDEL_MARGIN_RATE,CDEL_CANCEL_DATE,CDEL_PROFIT_LOSS,TO_CHAR(asonDate,'MONYY')
      from trtran006 A,trtran001
        where deal_deal_number=cdel_deal_number
        and cdel_cancel_date  between datStart and datEnd
        and cdel_record_status not in (10200005,10200006)
        and deal_record_status not in (10200005,10200006)
        AND DEAL_DEAL_TYPE NOT IN(25400001)
        AND cdel_profit_loss <> 0;
        
    varOperation := 'Buyers Credit Opening Balance';
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BUYCALL_RATE,HDCT_SELLCALL_RATE,HDCT_SELLPUT_RATE,
      HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_PREMIUM_RATE,HDCT_CANCEL_RATE,HDCT_CANCEL_SPOT,
      HDCT_CANCEL_FORWARD,HDCT_CANCEL_MARGIN,HDCT_CANCEL_DATE,HDCT_PROFIT_LOSS,HDCT_ASON_MONTH)
      SELECT BCRD_COMPANY_CODE,BCRD_LOCATION_CODE,bcrd_product_category,BCRD_SUBPRODUCT_CODE,
      25300001,26099999,BCRD_SANCTION_DATE,BCRD_DUE_DATE,
      BCRD_DUE_DATE,BCRD_LOCAL_BANK,
      PKGFOREXPROCESS.fncGetOutstanding(bcrd_buyers_credit, 0,GConst.UTILBCRLOAN,GConst.AMOUNTFCY, AsonDate),
      bcrd_conversion_rate,bcrd_spot_rate,BCRD_FORWARD_RATE,BCRD_MARGIN_RATE,0,0,0,
      BCRD_BUYERS_CREDIT,'OP Buyers Credit',TO_CHAR(datStart,'MONYY'),3,3,
      'OP Buyers Credit '||pkgreturncursor.fncgetdescription(BCRD_COMPANY_CODE,2),datason,
      0,0,0, BCRD_CURRENCY_CODE,30400003,0,0,0,0,
      0,null,0,TO_CHAR(asonDate,'MONYY')
      from trtran045
        where BCRD_SANCTION_DATE <= datLastmonth
      and ((bcrd_completion_date is null) or (bcrd_completion_date > datLastmonth))
      and BCRD_COMPANY_CODE in
      (select usco_company_code from trsystem022a where usco_user_id =UserID)
      and BCRD_RECORD_STATUS in (GConst.STATUSENTRY, Gconst.STATUSAUTHORIZED, GConst.STATUSUPDATED);  
      
    varOperation := 'New Buyers Credit Taken';
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BUYCALL_RATE,HDCT_SELLCALL_RATE,HDCT_SELLPUT_RATE,
      HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_PREMIUM_RATE,HDCT_CANCEL_RATE,HDCT_CANCEL_SPOT,
      HDCT_CANCEL_FORWARD,HDCT_CANCEL_MARGIN,HDCT_CANCEL_DATE,HDCT_PROFIT_LOSS,HDCT_ASON_MONTH)
      SELECT BCRD_COMPANY_CODE,BCRD_LOCATION_CODE,bcrd_product_category,BCRD_SUBPRODUCT_CODE,
      25300001,26099999,BCRD_SANCTION_DATE,BCRD_DUE_DATE,
      BCRD_DUE_DATE,BCRD_LOCAL_BANK,
      PKGFOREXPROCESS.fncGetOutstanding(bcrd_buyers_credit, 0,GConst.UTILBCRLOAN,GConst.AMOUNTFCY, AsonDate),
      bcrd_conversion_rate,bcrd_spot_rate,BCRD_FORWARD_RATE,BCRD_MARGIN_RATE,0,0,0,
      BCRD_BUYERS_CREDIT,'New Buyers Credit',TO_CHAR(datStart,'MONYY'),3,3,
      'New Buyers Credit '||pkgreturncursor.fncgetdescription(BCRD_COMPANY_CODE,2),datason,
      0,0,0, BCRD_CURRENCY_CODE,30400003,0,0,0,0,
      0,null,0,TO_CHAR(asonDate,'MONYY')
      from trtran045
        where BCRD_SANCTION_DATE between datStart and datEnd 
      --and ((bcrd_completion_date is null) or (bcrd_completion_date > datLastmonth))
      and BCRD_COMPANY_CODE in
      (select usco_company_code from trsystem022a where usco_user_id =UserID)
      and BCRD_RECORD_STATUS in (GConst.STATUSENTRY, Gconst.STATUSAUTHORIZED, GConst.STATUSUPDATED); 
      
   varOperation := 'BC Repayment';
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BUYCALL_RATE,HDCT_SELLCALL_RATE,HDCT_SELLPUT_RATE,
      HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_PREMIUM_RATE,HDCT_CANCEL_RATE,HDCT_CANCEL_SPOT,
      HDCT_CANCEL_FORWARD,HDCT_CANCEL_MARGIN,HDCT_CANCEL_DATE,HDCT_PROFIT_LOSS,HDCT_ASON_MONTH)
      SELECT BCRD_COMPANY_CODE,BCRD_LOCATION_CODE,bcrd_product_category,BCRD_SUBPRODUCT_CODE,
      25300001,26099999,BCRD_SANCTION_DATE,BCRD_DUE_DATE,
      BCRD_DUE_DATE,BCRD_LOCAL_BANK,
      PKGFOREXPROCESS.fncGetOutstanding(bcrd_buyers_credit, 0,GConst.UTILBCRLOAN,GConst.AMOUNTFCY, AsonDate),
      bcrd_conversion_rate,bcrd_spot_rate,BCRD_FORWARD_RATE,BCRD_MARGIN_RATE,CDEL_CANCEL_AMOUNT,0,0,
      BCRD_BUYERS_CREDIT,'BC Repayment',TO_CHAR(datStart,'MONYY'),3,3,
      'BC Repayment '||pkgreturncursor.fncgetdescription(BCRD_COMPANY_CODE,2),datason,
      0,0,0, BCRD_CURRENCY_CODE,30400003,0,CDEL_CANCEL_RATE,0,0,
      0,CDEL_CANCEL_DATE,0,TO_CHAR(asonDate,'MONYY')
      from trtran045,TRTRAN006
        where CDEL_CANCEL_DATE between datStart and datEnd 
        AND BCRD_BUYERS_CREDIT = CDEL_TRADE_REFERENCE
        AND CDEL_RECORD_STATUS NOT IN(10200006,10200005)
      --and ((bcrd_completion_date is null) or (bcrd_completion_date > datLastmonth))
      and BCRD_COMPANY_CODE in
      (select usco_company_code from trsystem022a where usco_user_id =UserID)
      and BCRD_RECORD_STATUS in (GConst.STATUSENTRY, Gconst.STATUSAUTHORIZED, GConst.STATUSUPDATED);  
      
   varOperation := 'BC Otstanding ason date';
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BUYCALL_RATE,HDCT_SELLCALL_RATE,HDCT_SELLPUT_RATE,
      HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_PREMIUM_RATE,HDCT_CANCEL_RATE,HDCT_CANCEL_SPOT,
      HDCT_CANCEL_FORWARD,HDCT_CANCEL_MARGIN,HDCT_CANCEL_DATE,HDCT_PROFIT_LOSS,HDCT_ASON_MONTH)
      SELECT BCRD_COMPANY_CODE,BCRD_LOCATION_CODE,bcrd_product_category,BCRD_SUBPRODUCT_CODE,
      25300001,26099999,BCRD_SANCTION_DATE,BCRD_DUE_DATE,
      BCRD_DUE_DATE,BCRD_LOCAL_BANK,
      PKGFOREXPROCESS.fncGetOutstanding(bcrd_buyers_credit, 0,GConst.UTILBCRLOAN,GConst.AMOUNTFCY, AsonDate),
      bcrd_conversion_rate,bcrd_spot_rate,BCRD_FORWARD_RATE,BCRD_MARGIN_RATE,0,0,0,
      BCRD_BUYERS_CREDIT,'BC Outstanding',TO_CHAR(asonDate,'MONYY'),3,3,
      'BC Outstanding'||pkgreturncursor.fncgetdescription(BCRD_COMPANY_CODE,2),datason,
      0,0,0, BCRD_CURRENCY_CODE,30400003,0,0,0,0,
      0,null,0,TO_CHAR(asonDate,'MONYY')
      from trtran045
        where BCRD_SANCTION_DATE <= asonDate
      and ((bcrd_completion_date is null) or (bcrd_completion_date > asonDate))
      and BCRD_COMPANY_CODE in
      (select usco_company_code from trsystem022a where usco_user_id =UserID)
      and BCRD_RECORD_STATUS in (GConst.STATUSENTRY, Gconst.STATUSAUTHORIZED, GConst.STATUSUPDATED);  
      
      
    varOperation := 'MTM For Forward';       
    insert into TRSYSTEM983_HEDGECOST
    ( HDCT_COMPANY_CODE,HDCT_LOCATION_CODE,HDCT_BUSINESS_UNIT,HDCT_PROFIT_CENTER,HDCT_BUY_SELL,HDCT_HEDGE_TRADE,
      HDCT_EXECUTE_DATE,HDCT_MATURITY_FROM,HDCT_MATURITY_TO,HDCT_COUNTER_PARTY,HDCT_OUTSTANDING_AMOUNT,HDCT_EXCHANGE_RATE,
      HDCT_SPOT_RATE,HDCT_FORWARD_RATE,HDCT_MARGIN_RATE,HDCT_CANCEL_AMOUNT,HDCT_PREMIUM_AMOUNT,HDCT_EXERCISE_TYPE,
      HDCT_DEAL_NUMBER,HDCT_MAIN_DESCRIPTION,HDCT_SUB_DESCRIPTION,HDCT_MAIN_ORDER,HDCT_SUB_ORDER,
      HDCT_INSTUMENT,HDCT_ASON_DATE,HDCT_BASE_CURRENCY,HDCT_OTHER_CURRENCY,HDCT_ASON_MONTH,HDCT_MTM_AMOUNT)
      SELECT DEAL_COMPANY_CODE,DEAL_LOCATION_CODE,DEAL_BACKUP_DEAL,DEAL_INIT_CODE,
      DEAL_BUY_SELL,DEAL_HEDGE_TRADE,DEAL_EXECUTE_DATE,DEAL_MATURITY_FROM,
      DEAL_MATURITY_DATE,DEAL_COUNTER_PARTY,
      PKGFOREXPROCESS.Fncgetoutstanding(Deal_Deal_Number, Deal_Serial_Number,Gconst.Utiltradedeal,Gconst.Amountfcy, datason),
      DEAL_EXCHANGE_RATE,DEAL_SPOT_RATE,DEAL_FORWARD_RATE,DEAL_MARGIN_RATE,0,0,0,
      DEAL_DEAL_NUMBER,'Forward MTM',TO_CHAR(asonDate,'MONYY'),1,1,'Forward MTM',datason,
      DEAL_BASE_CURRENCY,DEAL_OTHER_CURRENCY,TO_CHAR(asonDate,'MONYY'),
        pkgreturnreport.fncgetprofitloss(pkgForexProcess.fncGetOutstanding(deal_deal_number,
        deal_serial_number,GConst.UTILTRADEDEAL,GConst.AMOUNTFCY,asonDate),
        (CASE WHEN DEAL_BUY_SELL = 25300001 THEN(
        pkgforexprocess.fncGetRate(deal_base_currency,deal_other_currency,
        asondate,deal_buy_sell,(pkgForexProcess.fncAllotMonth(deal_counter_party,
        asondate,deal_maturity_date)),
        deal_maturity_date)) ELSE
        (pkgforexprocess.fncGetRate(deal_base_currency,deal_other_currency,
        asondate,deal_buy_sell,(pkgForexProcess.fncAllotMonth(deal_counter_party,
        asondate,deal_maturity_date)),
        deal_maturity_date))END), DEAL_EXCHANGE_RATE, deal_buy_sell) *
        decode(deal_other_currency,30400003,1, pkgforexprocess.fncGetRate(deal_other_currency,30400003,
        asondate,deal_buy_sell,pkgForexProcess.fncAllotMonth(deal_counter_party,
        asondate,deal_maturity_date),deal_maturity_date))      
      from trtran001
      where  deal_execute_date <= asonDate
      and deal_hedge_trade in (GConst.HEDGEDEAL, GCONST.FTDEAL)
      and deal_company_code in (select usco_company_code from trsystem022a where usco_user_id =UserID)
      and deal_record_status in(GConst.STATUSENTRY, Gconst.STATUSAUTHORIZED, GConst.STATUSUPDATED)
      and ((deal_complete_date is null) or (deal_complete_date > asonDate))
      and deal_deal_type not in(25400001);

        
   delete from trsystem983A_hedgecost WHERE HGCT_ASON_MONTH = TO_CHAR(asonDate,'MON-YY');
   INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  DECODE(HDCT_BUSINESS_UNIT,33300003,1,2),pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1, ROUND(AVG(HDCT_OUTSTANDING_AMOUNT),2),Round((fncGetPremium(asonDate,HDCT_BUSINESS_UNIT,UserID)*numRate)/12,6),0,
   Round(AVG(HDCT_OUTSTANDING_AMOUNT * -1) * (fncGetPremium(asonDate,HDCT_BUSINESS_UNIT,UserID)*numRate)/12,2),
   32200001,'Forward',1,
   pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),1,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST
  WHERE HDCT_MAIN_DESCRIPTION = 'Forward'
  AND HDCT_BUSINESS_UNIT IN(33300004, 33300003)
  group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE
  order by HDCT_COMPANY_CODE;
     
   INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  DECODE(HDCT_BUSINESS_UNIT,33300003,1,2),pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1, 0 ,0,0,sum(hdct_premium_amount),32200001,'Option - ' || pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),2,
   'Option  Premium-Mio',1,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST
  WHERE HDCT_MAIN_DESCRIPTION = 'New Option'
  AND HDCT_BUSINESS_UNIT IN(33300004, 33300003)
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE;

   INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
      HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  DECODE(HDCT_BUSINESS_UNIT,33300003,1,2),pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1, sum(HDCT_OUTSTANDING_AMOUNT ),0,0,
   sum((HDCT_OUTSTANDING_AMOUNT * -1)*(numRate - HDCT_SPOT_RATE)) ,
   32200001,'Option - ' || pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),2,
   'New Option',2,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST
  WHERE HDCT_MAIN_DESCRIPTION = 'New Option'
  AND HDCT_BUSINESS_UNIT IN(33300004, 33300003)
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE;
  
   INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  DECODE(HDCT_BUSINESS_UNIT,33300003,1,2),pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1,SUM(HDCT_OUTSTANDING_AMOUNT)- nvl(Excer.Amount,0),0,0,
   ((SUM(HDCT_OUTSTANDING_AMOUNT)- nvl(Excer.Amount,0))*-1)*(numRate - numRate1 ),
   32200001,'Option - ' || pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),2,
   'Option- Translation',3,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST left outer join(
    SELECT HDCT_COMPANY_CODE CompanyCode,HDCT_BUSINESS_UNIT BusinessUnit,ROUND(SUM(HDCT_OUTSTANDING_AMOUNT),2) Amount
  FROM TRSYSTEM983_HEDGECOST
  WHERE HDCT_MAIN_DESCRIPTION = 'Option Excersied'
  AND HDCT_BUSINESS_UNIT IN(33300004, 33300003)
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE) Excer on
   HDCT_COMPANY_CODE = Excer.CompanyCode
   and HDCT_BUSINESS_UNIT = Excer.BusinessUnit
  WHERE HDCT_MAIN_DESCRIPTION = 'Last month Option'
  AND HDCT_BUSINESS_UNIT IN(33300004, 33300003)
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE,Excer.Amount;
  
   INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
      HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  DECODE(HDCT_BUSINESS_UNIT,33300003,1,2),pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1, ROUND(SUM(HDCT_OUTSTANDING_AMOUNT),2),0,0,24.13,32200001,'Option - ' || pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),2,
   'Option Expired/Excersied/Cancelled',4,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST
  WHERE HDCT_MAIN_DESCRIPTION = 'Option Excersied'
  AND HDCT_BUSINESS_UNIT IN(33300004, 33300003)
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE;
  
  INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)     
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  DECODE(HDCT_BUSINESS_UNIT,33300003,1,2),pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1, ROUND(sum(HDCT_OUTSTANDING_AMOUNT),2),0,0,ROUND(sum(HDCT_OUTSTANDING_AMOUNT * HGCT_CANCEL_PREMIUM),2),32200001,'Option - ' || pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),2,
   'Option Cancelled',5,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST
  WHERE HDCT_MAIN_DESCRIPTION = 'Option Excersied'
  AND HDCT_BUSINESS_UNIT IN(33300004, 33300003)
  AND HDCT_EXERCISE_TYPE = 33000003
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE;
  
  INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  DECODE(HDCT_BUSINESS_UNIT,33300003,1,2),pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1, ROUND(sum(HDCT_OUTSTANDING_AMOUNT),2),0,0,Round(Forward.AmounFcy * (Forward.Rate - numRate1),2),32200001,'Option - ' || pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),2,
   'Option Expired',6,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST 
  left outer join
  (SELECT sum(DEAL_BASE_AMOUNT)AmounFcy,
    sum(DEAL_BASE_AMOUNT * deal_exchange_rate)/sum(DEAL_BASE_AMOUNT) Rate,
    deal_backup_deal BusinessUnit,
    deal_company_code CompanyCode,
    TO_CHAR(deal_execute_date,'MON-YY') Month1
  FROM TRTRAN001
  WHERE DEAL_DEAL_TYPE  = 25400001
  AND deal_backup_deal IN(33300004, 33300003)
  AND deal_record_status not in(10200005,10200006)
  AND TO_CHAR(deal_execute_date,'MON-YY') = TO_CHAR(asonDate,'MON-YY')
  group by deal_backup_deal,deal_company_code, TO_CHAR(deal_execute_date,'MON-YY'))Forward
  on HDCT_BUSINESS_UNIT = Forward.BusinessUnit
  and HDCT_COMPANY_CODE = Forward.CompanyCode
  and TO_CHAR(asonDate,'MON-YY') = Forward.Month1
  WHERE HDCT_MAIN_DESCRIPTION = 'Option Excersied'
  AND HDCT_BUSINESS_UNIT IN(33300004, 33300003)
  AND HDCT_EXERCISE_TYPE = 33000002
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE,Forward.AmounFcy,Forward.Rate;
  
  INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)    
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  DECODE(HDCT_BUSINESS_UNIT,33300003,1,2),pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1, ROUND(sum(HDCT_OUTSTANDING_AMOUNT),2),0,0,
   Round(sum(HDCT_OUTSTANDING_AMOUNT * (HDCT_CANCEL_RATE - numRate1)),6),32200001,
   'Option - ' || pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),2,
   'Option Exercise',7,TO_CHAR(asonDate,'MON-YY'),
    TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST
  WHERE HDCT_MAIN_DESCRIPTION = 'Option Excersied'
  AND HDCT_BUSINESS_UNIT IN(33300004, 33300003)
  AND HDCT_EXERCISE_TYPE = 33000001
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE;
  
  INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)    
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  DECODE(HDCT_BUSINESS_UNIT,33300003,1,2),pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1, 0,0,0,
   SUM(fncgetOPTMTM1 (asonDate,0,HDCT_COMPANY_CODE,HDCT_BUSINESS_UNIT)) - 
   SUM(fncgetOPTMTM1 (datLastmonth,0,HDCT_COMPANY_CODE,HDCT_BUSINESS_UNIT)),
   32200001,'Option - ' || pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),2,
   'MTM on option for the month',8,TO_CHAR(asonDate,'MON-YY'),
    TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST
  WHERE HDCT_MAIN_DESCRIPTION = 'Option'
  AND HDCT_BUSINESS_UNIT IN(33300004, 33300003)
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE;
  
  INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)    
  SELECT pkgreturncursor.fncgetdescription(deal_backup_deal,2),
  DECODE(deal_backup_deal,33300003,1,2),pkgreturncursor.fncgetdescription(deal_COMPANY_CODE,2),
   1, 0,0,0,
   sum(cdel_cancel_amount * (numRate - numRate1)),
   32200001,'Others',3,
   'Gain/(Loss) Due to hedging (BL - Spot rate )',1,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
      FROM trtran006
      INNER JOIN trtran002
      ON cdel_trade_reference = trad_trade_reference
      inner join trtran001
      on cdel_deal_number = deal_deal_number
      WHERE cdel_record_Status NOT IN (10200005,10200006)
      AND trad_record_Status NOT   IN (10200005,10200006)
      and deal_record_status not in(10200005,10200006)
      AND deal_backup_deal IN(33300004, 33300003)
      AND CDEL_CANCEL_DATE BETWEEN datStart and datEnd
      AND TRAD_IMPORT_EXPORT > 25900050
      GROUP BY deal_backup_deal,deal_COMPANY_CODE;
  
 INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
      HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR,HGCT_PICKKEY_CODE)  
  SELECT pkgreturncursor.fncgetdescription(33300003,2),
   1,pkgreturncursor.fncgetdescription(30100001,2),
   1, PLAC_TOTAL_AMOUNT,0,0,(PLAC_TOTAL_AMOUNT*(numRate - numRate1)),32299999,'Others',3,
   pkgreturncursor.fncgetdescription(PLAC_PICK_CODE,1),1,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2),
   PLAC_PICK_CODE
  from trtran155
  where PLAC_PICK_CODE between 38000001 and 38000050
  and plac_effective_date = (SELECT MAX(plac_effective_date) FROM TRTRAN155 A 
                            WHERE PLAC_RECORD_STATUS NOT IN(10200005,10200006)
                            AND PLAC_PICK_CODE = PLAC_PICK_CODE
                            AND plac_effective_date <= asonDate)
  order by PLAC_PICK_CODE; ---RMBC releted entries   
   
  INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)
  SELECT pkgreturncursor.fncgetdescription(33300004,1),
   2,pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1, SUM(hdct_outstanding_amount)-CapexOpt.Amount ,0,0,
   (SUM(hdct_outstanding_amount)-CapexOpt.Amount) *(numRate - numRate1),32299999,'Capitalised BC',3,
   'Capitalised BC',49,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST
  LEFT OUTER JOIN 
  (SELECT SUM(hgtc_amount_fcy)Amount,
      hgct_ason_month Month1,
      hgct_main_description Description
    FROM trsystem983A_hedgecost
    WHERE HGCT_SUB_DESCRIPTION1 = 'Option- Translation'
    AND hgct_main_description   = 'Capex BC'
    AND hgct_ason_month         = TO_CHAR(asonDate,'MON-YY')
    GROUP BY hgct_ason_month,hgct_main_description)CapexOpt
    ON pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2) = CapexOpt.Description
  WHERE HDCT_MAIN_DESCRIPTION = 'BC Outstanding'
  AND HDCT_BUSINESS_UNIT IN(33300004)
  GROUP BY HDCT_COMPANY_CODE,CapexOpt.Amount;
  
 INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
      HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR,HGCT_PICKKEY_CODE)
  SELECT pkgreturncursor.fncgetdescription(33300004,1),
   2,pkgreturncursor.fncgetdescription(30100001,2),
   1, PLAC_TOTAL_AMOUNT,0,0,(PLAC_TOTAL_AMOUNT*(numRate - numRate1)),32299999,'Subsidiary',3,
   pkgreturncursor.fncgetdescription(PLAC_PICK_CODE,1),50,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2),
   PLAC_PICK_CODE
  from trtran155
  where PLAC_PICK_CODE between 38000050 and 38000100
  and plac_effective_date = (SELECT MAX(plac_effective_date) FROM TRTRAN155 A 
                            WHERE PLAC_RECORD_STATUS NOT IN(10200005,10200006)
                            AND PLAC_PICK_CODE = PLAC_PICK_CODE
                            AND plac_effective_date <= asonDate)
  order by PLAC_PICK_CODE; ---Capex releted entries   
  
    INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)  
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  DECODE(HDCT_BUSINESS_UNIT,33300003,1,2),pkgreturncursor.fncgetdescription(HDCT_COMPANY_CODE,2),
   1, 0,0,0,sum(HDCT_PROFIT_LOSS),32200001,'Others',3,
   case when HDCT_BUY_SELL = 25300001 then 'Import - Cancellation & Early Delivery' Else 'Export - Cancellation & Early Delivery' End,75,
   TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST
  WHERE HDCT_MAIN_DESCRIPTION = 'Forward Cancel'
  AND HDCT_BUSINESS_UNIT IN(33300003,33300004)
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE,HDCT_BUY_SELL;
  
  
   INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
      HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR,HGCT_PICKKEY_CODE) 
  SELECT 'Amortisation',3,pkgreturncursor.fncgetdescription(30100001,2),
   1, PLAC_TOTAL_AMOUNT,0,0,
   PLAC_TOTAL_AMOUNT * (numRate - numRate1),
   32299999,'Amortisation',3,
   pkgreturncursor.fncgetdescription(PLAC_PICK_CODE,1),rownum,TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2),
   PLAC_PICK_CODE
  from trtran155
  where PLAC_PICK_CODE between 38000101 and 38000150
  and plac_effective_date = (SELECT MAX(plac_effective_date) FROM TRTRAN155 A 
                            WHERE PLAC_RECORD_STATUS NOT IN(10200005,10200006)
                            AND PLAC_PICK_CODE = PLAC_PICK_CODE
                            AND plac_effective_date <= asonDate)
  order by PLAC_PICK_CODE; ---Amortisation releted entries   
  
    INSERT INTO trsystem983A_hedgecost
    (HGCT_MAIN_DESCRIPTION,HGCT_MAIN_ORDER,HGCT_SUB_DESCRIPTION,
     HGCT_SUB_ORDER,HGTC_AMOUNT_FCY,HGTC_PREMIUM,HGTC_RATE,
     HGTC_AMOUNT_INR,HGTC_INSTRUMENT_TYPE,HGTC_INSTRUMENT_DESCRIPTION,
     HGTC_INSTRUMENT_ORDER,HGCT_SUB_DESCRIPTION1,HGCT_SUB_ORDER1,HGCT_ASON_MONTH,
     HGCT_MONTH_ORDER,HGCT_FINACIAL_YEAR)  
  SELECT pkgreturncursor.fncgetdescription(HDCT_BUSINESS_UNIT,2),
  1,1,0,0,0,0,sum(DECODE (HDCT_OTHER_CURRENCY,30400003,HDCT_MTM_AMOUNT,(HDCT_MTM_AMOUNT * pkgForexProcess.fncGetRate(HDCT_OTHER_CURRENCY,30400003,asonDate,HDCT_BUY_SELL,0,NULL)))),
  0,'ForwardMTM',3,'ForwardMTM',1,
   TO_CHAR(asonDate,'MON-YY'),
   TO_NUMBER(TO_CHAR(asonDate,'YYYYMM')),FNCGETFINANCIALYEAR(asonDate,asonDate,2)
  FROM TRSYSTEM983_HEDGECOST
  WHERE HDCT_MAIN_DESCRIPTION = 'Forward MTM'
  AND HDCT_BUY_SELL = 25300002
   group by HDCT_BUSINESS_UNIT,HDCT_COMPANY_CODE,HDCT_BUY_SELL;
   
   
  commit;
  Exception
    When others then
      numError := SQLCODE;
      varError := SQLERRM;
      varError := GConst.fncReturnError('prcHedgingCost', numError, varMessage,varOperation, varError);
      Raise_Application_Error(-20101, Varerror);    
 end prcHedgingCost;
/