CREATE TABLE "TEST_VSTSRedgate".dealtemp (
  dealnumber VARCHAR2(25 BYTE),
  executedate DATE,
  buysell VARCHAR2(25 BYTE),
  status VARCHAR2(25 BYTE),
  baseamount NUMBER(15,2),
  maturitydate DATE,
  canceldate DATE,
  cbuysell VARCHAR2(512 BYTE),
  cancelrate NUMBER(15,6),
  cancelamount NUMBER(15,2),
  profitloss NUMBER(15,2),
  washrate NUMBER(15,6),
  netamount NUMBER(15,2),
  mtmrate NUMBER(15,6),
  basecurrency VARCHAR2(25 BYTE),
  othercurrency VARCHAR2(25 BYTE),
  exchangerate NUMBER(15,6),
  valuedate DATE,
  bank VARCHAR2(25 BYTE),
  enhanceddate DATE,
  enhancedrate NUMBER(15,6),
  enhancedfcy NUMBER(15,2),
  firstquarter NUMBER(15,2),
  secondquarter NUMBER(15,2),
  thirdquarter NUMBER(15,2),
  fourquarter NUMBER(15,2),
  yesterdayamt NUMBER(15,2),
  todayamt NUMBER(15,2),
  todayshedgedeal NUMBER(15,2),
  statusorder NUMBER(3),
  prevfinyear NUMBER(15,2),
  remarks VARCHAR2(500 BYTE),
  companycode NUMBER(8)
);