CREATE TABLE "TEST_VSTSRedgate".dmrs_tables (
  table_name VARCHAR2(256 BYTE) NOT NULL,
  abbreviation VARCHAR2(30 BYTE),
  object_id VARCHAR2(70 BYTE) NOT NULL,
  ovid VARCHAR2(36 BYTE) NOT NULL,
  import_id VARCHAR2(70 BYTE),
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  structured_type_id VARCHAR2(70 BYTE),
  structured_type_ovid VARCHAR2(36 BYTE),
  structured_type_name VARCHAR2(256 BYTE),
  number_data_elements NUMBER,
  classification_type_id VARCHAR2(70 BYTE),
  classification_type_ovid VARCHAR2(36 BYTE),
  classification_type_name VARCHAR2(256 BYTE),
  allow_type_substitution CHAR,
  engineer_as_relationship VARCHAR2(1 BYTE),
  allow_col_reorder VARCHAR2(1 BYTE),
  min_volume NUMBER,
  expected_volume NUMBER,
  max_volume NUMBER,
  growth_rate_percents NUMBER,
  growth_rate_interval VARCHAR2(5 BYTE),
  normal_form VARCHAR2(6 BYTE),
  temporary_object_scope VARCHAR2(30 BYTE),
  adequately_normalized CHAR,
  substitution_parent VARCHAR2(70 BYTE),
  substitution_parent_ovid VARCHAR2(36 BYTE),
  engineer CHAR,
  spatial_table CHAR,
  oid_is_pk CHAR,
  oid_is_user_defined CHAR,
  include_scripts_into_ddl CHAR,
  model_name VARCHAR2(256 BYTE),
  substitution_parent_name VARCHAR2(256 BYTE),
  schema_ovid VARCHAR2(36 BYTE),
  schema_name VARCHAR2(256 BYTE),
  source_info_ovid VARCHAR2(36 BYTE),
  source_datadict_schema_name VARCHAR2(256 BYTE),
  source_datadict_object_name VARCHAR2(256 BYTE),
  redaction_policy_name VARCHAR2(50 BYTE),
  redaction_policy_enabled VARCHAR2(1 BYTE),
  redaction_policy_expression VARCHAR2(50 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);