CREATE TABLE "TEST_VSTSRedgate".dmrs_flows (
  flow_id VARCHAR2(70 BYTE) NOT NULL,
  flow_ovid VARCHAR2(36 BYTE) NOT NULL,
  flow_name VARCHAR2(256 BYTE) NOT NULL,
  diagram_id VARCHAR2(70 BYTE) NOT NULL,
  diagram_ovid VARCHAR2(36 BYTE) NOT NULL,
  diagram_name VARCHAR2(256 BYTE) NOT NULL,
  event_id VARCHAR2(70 BYTE),
  event_ovid VARCHAR2(36 BYTE),
  event_name VARCHAR2(256 BYTE),
  source_id VARCHAR2(70 BYTE),
  source_ovid VARCHAR2(36 BYTE),
  source_name VARCHAR2(256 BYTE),
  destination_id VARCHAR2(70 BYTE),
  destination_ovid VARCHAR2(36 BYTE),
  destination_name VARCHAR2(256 BYTE),
  parent_id VARCHAR2(70 BYTE),
  parent_ovid VARCHAR2(36 BYTE),
  parent_name VARCHAR2(256 BYTE),
  source_type VARCHAR2(30 BYTE),
  destination_type VARCHAR2(30 BYTE),
  system_objective VARCHAR2(4000 BYTE),
  "LOGGING" CHAR,
  op_create CHAR,
  op_read CHAR,
  op_update CHAR,
  op_delete CHAR,
  crud_code VARCHAR2(4 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);