CREATE TABLE "TEST_VSTSRedgate".dmrs_info_stores (
  info_store_id VARCHAR2(70 BYTE) NOT NULL,
  info_store_ovid VARCHAR2(36 BYTE) NOT NULL,
  info_store_name VARCHAR2(256 BYTE) NOT NULL,
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  model_name VARCHAR2(256 BYTE) NOT NULL,
  info_store_type VARCHAR2(30 BYTE),
  object_type VARCHAR2(30 BYTE),
  implementation_name VARCHAR2(256 BYTE),
  "LOCATION" VARCHAR2(256 BYTE),
  "SOURCE" VARCHAR2(256 BYTE),
  file_name VARCHAR2(256 BYTE),
  file_type VARCHAR2(30 BYTE),
  "OWNER" VARCHAR2(256 BYTE),
  rdbms_site VARCHAR2(256 BYTE),
  "SCOPE" VARCHAR2(30 BYTE),
  transfer_type VARCHAR2(30 BYTE),
  field_separator VARCHAR2(4 BYTE),
  text_delimiter VARCHAR2(4 BYTE),
  skip_records NUMBER(10),
  self_describing CHAR,
  system_objective VARCHAR2(4000 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);