CREATE TABLE "TEST_VSTSRedgate".dmrs_foreignkeys (
  fk_name VARCHAR2(256 BYTE) NOT NULL,
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  object_id VARCHAR2(70 BYTE) NOT NULL,
  ovid VARCHAR2(36 BYTE) NOT NULL,
  import_id VARCHAR2(70 BYTE),
  child_table_name VARCHAR2(256 BYTE) NOT NULL,
  referred_table_name VARCHAR2(256 BYTE) NOT NULL,
  engineer CHAR,
  delete_rule VARCHAR2(10 BYTE),
  child_table_id VARCHAR2(70 BYTE) NOT NULL,
  child_table_ovid VARCHAR2(36 BYTE),
  referred_table_id VARCHAR2(70 BYTE) NOT NULL,
  referred_table_ovid VARCHAR2(36 BYTE),
  referred_key_id VARCHAR2(70 BYTE) NOT NULL,
  referred_key_ovid VARCHAR2(36 BYTE),
  number_of_columns NUMBER NOT NULL,
  mandatory CHAR,
  transferable CHAR,
  in_arc CHAR,
  arc_id VARCHAR2(70 BYTE),
  model_name VARCHAR2(256 BYTE),
  referred_key_name VARCHAR2(256 BYTE),
  discriminator_column_ovid VARCHAR2(36 BYTE),
  discriminator_value VARCHAR2(50 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);