CREATE TABLE "TEST_VSTSRedgate".dmrs_view_columns (
  view_ovid VARCHAR2(36 BYTE) NOT NULL,
  view_id VARCHAR2(70 BYTE) NOT NULL,
  view_name VARCHAR2(256 BYTE) NOT NULL,
  container_id VARCHAR2(70 BYTE) NOT NULL,
  container_ovid VARCHAR2(36 BYTE) NOT NULL,
  container_name VARCHAR2(256 BYTE) NOT NULL,
  container_alias VARCHAR2(256 BYTE),
  is_expression CHAR,
  column_id VARCHAR2(70 BYTE) NOT NULL,
  column_ovid VARCHAR2(36 BYTE) NOT NULL,
  column_name VARCHAR2(256 BYTE) NOT NULL,
  column_alias VARCHAR2(256 BYTE),
  native_type VARCHAR2(60 BYTE),
  "TYPE" CHAR,
  expression VARCHAR2(2000 BYTE),
  "SEQUENCE" NUMBER(3) NOT NULL,
  personally_id_information CHAR,
  sensitive_information CHAR,
  mask_for_none_production CHAR(12 BYTE),
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  model_name VARCHAR2(256 BYTE) NOT NULL,
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);