CREATE TABLE "TEST_VSTSRedgate".dmrs_attributes (
  attribute_name VARCHAR2(256 BYTE) NOT NULL,
  object_id VARCHAR2(80 BYTE) NOT NULL,
  ovid VARCHAR2(36 BYTE) NOT NULL,
  import_id VARCHAR2(70 BYTE),
  container_id VARCHAR2(70 BYTE) NOT NULL,
  container_ovid VARCHAR2(36 BYTE) NOT NULL,
  mandatory CHAR NOT NULL,
  datatype_kind VARCHAR2(20 BYTE) NOT NULL,
  value_type VARCHAR2(10 BYTE),
  formula VARCHAR2(4000 BYTE),
  scopeentity_id VARCHAR2(70 BYTE),
  scopeentity_ovid VARCHAR2(36 BYTE),
  domain_id VARCHAR2(70 BYTE),
  domain_ovid VARCHAR2(36 BYTE),
  logical_type_id VARCHAR2(70 BYTE),
  logical_type_ovid VARCHAR2(36 BYTE),
  distinct_type_id VARCHAR2(70 BYTE),
  distinct_type_ovid VARCHAR2(36 BYTE),
  structured_type_id VARCHAR2(70 BYTE),
  structured_type_ovid VARCHAR2(36 BYTE),
  collection_type_id VARCHAR2(70 BYTE),
  collection_type_ovid VARCHAR2(36 BYTE),
  check_constraint_name VARCHAR2(256 BYTE),
  default_value VARCHAR2(256 BYTE),
  use_domain_constraint CHAR,
  domain_name VARCHAR2(256 BYTE),
  logical_type_name VARCHAR2(256 BYTE),
  structured_type_name VARCHAR2(256 BYTE),
  distinct_type_name VARCHAR2(256 BYTE),
  collection_type_name VARCHAR2(256 BYTE),
  synonyms VARCHAR2(4000 BYTE),
  preferred_abbreviation VARCHAR2(256 BYTE),
  relationship_id VARCHAR2(100 BYTE),
  relationship_ovid VARCHAR2(36 BYTE),
  entity_name VARCHAR2(256 BYTE) NOT NULL,
  pk_flag VARCHAR2(1 BYTE),
  fk_flag VARCHAR2(1 BYTE),
  relationship_name VARCHAR2(256 BYTE),
  "SEQUENCE" NUMBER NOT NULL,
  t_size VARCHAR2(20 BYTE),
  t_precision NUMBER,
  char_units CHAR(4 BYTE),
  native_type VARCHAR2(60 BYTE),
  t_scale NUMBER,
  data_source VARCHAR2(256 BYTE),
  scopeentity_name VARCHAR2(256 BYTE),
  sensitive_type_ovid VARCHAR2(36 BYTE),
  sensitive_data_descr VARCHAR2(256 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);