CREATE TABLE "TEST_VSTSRedgate".dmrs_events (
  event_id VARCHAR2(70 BYTE) NOT NULL,
  event_ovid VARCHAR2(36 BYTE) NOT NULL,
  event_name VARCHAR2(256 BYTE) NOT NULL,
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  model_name VARCHAR2(256 BYTE) NOT NULL,
  flow_id VARCHAR2(70 BYTE),
  flow_ovid VARCHAR2(36 BYTE),
  flow_name VARCHAR2(256 BYTE),
  event_type VARCHAR2(30 BYTE),
  times_when_run VARCHAR2(100 BYTE),
  day_of_week VARCHAR2(100 BYTE),
  "MONTHS" VARCHAR2(100 BYTE),
  frequency NUMBER(10),
  time_frequency NUMBER(10),
  "MINUTE" NUMBER(2),
  "HOUR" NUMBER(2),
  day_of_month NUMBER(2),
  quarter NUMBER(1),
  "YEAR" NUMBER(4),
  on_day CHAR,
  at_time CHAR,
  fiscal CHAR,
  "TEXT" VARCHAR2(4000 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);