CREATE TABLE "TEST_VSTSRedgate".dmrs_diagram_elements (
  "NAME" VARCHAR2(256 BYTE) NOT NULL,
  long_name VARCHAR2(256 BYTE),
  "TYPE" VARCHAR2(30 BYTE) NOT NULL,
  geometry_type VARCHAR2(10 BYTE) NOT NULL,
  object_id VARCHAR2(80 BYTE) NOT NULL,
  ovid VARCHAR2(36 BYTE) NOT NULL,
  view_id VARCHAR2(70 BYTE),
  source_id VARCHAR2(70 BYTE),
  source_ovid VARCHAR2(36 BYTE),
  source_view_id VARCHAR2(70 BYTE),
  target_id VARCHAR2(70 BYTE),
  target_ovid VARCHAR2(36 BYTE),
  target_view_id VARCHAR2(70 BYTE),
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  location_x NUMBER(10,2),
  location_y NUMBER(10,2),
  height NUMBER(10,2),
  width NUMBER(10,2),
  bg_color NUMBER(10),
  fg_color NUMBER(10),
  use_default_color CHAR,
  formatting VARCHAR2(4000 BYTE),
  points VARCHAR2(4000 BYTE),
  diagram_ovid VARCHAR2(36 BYTE) NOT NULL,
  diagram_id VARCHAR2(70 BYTE) NOT NULL,
  diagram_name VARCHAR2(256 BYTE) NOT NULL,
  source_name VARCHAR2(256 BYTE),
  target_name VARCHAR2(256 BYTE),
  model_name VARCHAR2(256 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);