CREATE TABLE "TEST_VSTSRedgate".dmrs_columns (
  column_name VARCHAR2(256 BYTE) NOT NULL,
  abbreviation VARCHAR2(30 BYTE),
  object_id VARCHAR2(70 BYTE) NOT NULL,
  ovid VARCHAR2(36 BYTE) NOT NULL,
  import_id VARCHAR2(70 BYTE),
  container_id VARCHAR2(70 BYTE) NOT NULL,
  container_ovid VARCHAR2(36 BYTE) NOT NULL,
  mandatory CHAR NOT NULL,
  datatype_kind VARCHAR2(20 BYTE) NOT NULL,
  value_type VARCHAR2(10 BYTE),
  computed CHAR,
  formula VARCHAR2(4000 BYTE),
  scopeentity_id VARCHAR2(70 BYTE),
  scopeentity_ovid VARCHAR2(36 BYTE),
  domain_id VARCHAR2(70 BYTE),
  domain_ovid VARCHAR2(36 BYTE),
  logical_type_id VARCHAR2(70 BYTE),
  logical_type_ovid VARCHAR2(36 BYTE),
  distinct_type_id VARCHAR2(70 BYTE),
  distinct_type_ovid VARCHAR2(36 BYTE),
  structured_type_id VARCHAR2(70 BYTE),
  structured_type_ovid VARCHAR2(36 BYTE),
  collection_type_id VARCHAR2(70 BYTE),
  collection_type_ovid VARCHAR2(36 BYTE),
  check_constraint_name VARCHAR2(256 BYTE),
  default_value VARCHAR2(256 BYTE),
  use_domain_constraint CHAR,
  domain_name VARCHAR2(256 BYTE),
  logical_type_name VARCHAR2(256 BYTE),
  structured_type_name VARCHAR2(256 BYTE),
  distinct_type_name VARCHAR2(256 BYTE),
  collection_type_name VARCHAR2(256 BYTE),
  uses_default CHAR,
  engineer CHAR NOT NULL,
  table_name VARCHAR2(256 BYTE) NOT NULL,
  pk_flag VARCHAR2(1 BYTE),
  fk_flag VARCHAR2(1 BYTE),
  native_type VARCHAR2(60 BYTE),
  "SEQUENCE" NUMBER NOT NULL,
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  model_name VARCHAR2(256 BYTE) NOT NULL,
  t_size VARCHAR2(20 BYTE),
  t_precision NUMBER,
  t_scale NUMBER,
  char_units CHAR(4 BYTE),
  personally_id_information CHAR,
  sensitive_information CHAR,
  sensitive_type_ovid VARCHAR2(36 BYTE),
  sensitive_data_descr VARCHAR2(256 BYTE),
  contains_pii VARCHAR2(3 BYTE),
  mask_type VARCHAR2(10 BYTE),
  mask_tymplate_ovid VARCHAR2(36 BYTE),
  mask_for_none_production CHAR(12 BYTE),
  scopeentity_name VARCHAR2(256 BYTE),
  auto_increment_column CHAR,
  identity_column CHAR,
  auto_increment_generate_always CHAR,
  auto_increment_start_with NUMBER,
  auto_increment_increment_by NUMBER,
  auto_increment_min_value NUMBER,
  auto_increment_max_value NUMBER,
  auto_increment_cycle CHAR,
  auto_increment_disable_cache CHAR,
  auto_increment_cache NUMBER,
  auto_increment_order CHAR,
  auto_increment_sequence_name VARCHAR2(256 BYTE),
  auto_increment_trigger_name VARCHAR2(256 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);