CREATE TABLE "TEST_VSTSRedgate".dmrs_entities (
  entity_name VARCHAR2(256 BYTE) NOT NULL,
  object_id VARCHAR2(70 BYTE) NOT NULL,
  ovid VARCHAR2(36 BYTE) NOT NULL,
  import_id VARCHAR2(70 BYTE),
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  structured_type_id VARCHAR2(70 BYTE),
  structured_type_ovid VARCHAR2(36 BYTE),
  structured_type_name VARCHAR2(256 BYTE),
  number_data_elements NUMBER,
  classification_type_id VARCHAR2(70 BYTE),
  classification_type_ovid VARCHAR2(36 BYTE),
  classification_type_name VARCHAR2(256 BYTE),
  allow_type_substitution CHAR,
  create_surrogate_key VARCHAR2(1 BYTE),
  min_volume NUMBER,
  expected_volume NUMBER,
  max_volume NUMBER,
  growth_rate_percents NUMBER,
  growth_rate_interval VARCHAR2(5 BYTE),
  normal_form VARCHAR2(6 BYTE),
  temporary_object_scope VARCHAR2(30 BYTE),
  adequately_normalized CHAR,
  substitution_parent VARCHAR2(70 BYTE),
  substitution_parent_ovid VARCHAR2(36 BYTE),
  synonyms VARCHAR2(4000 BYTE),
  synonym_to_display VARCHAR2(60 BYTE),
  preferred_abbreviation VARCHAR2(256 BYTE),
  supertypeentity_id VARCHAR2(70 BYTE),
  supertypeentity_ovid VARCHAR2(36 BYTE),
  engineering_strategy VARCHAR2(25 BYTE),
  "OWNER" VARCHAR2(50 BYTE),
  entity_source VARCHAR2(200 BYTE),
  model_name VARCHAR2(256 BYTE),
  substitution_parent_name VARCHAR2(256 BYTE),
  supertypeentity_name VARCHAR2(256 BYTE),
  subt_subtree_generation VARCHAR2(30 BYTE),
  subt_apply_to_model_ovid VARCHAR2(36 BYTE),
  subt_references VARCHAR2(30 BYTE),
  subt_attributes_inheritance VARCHAR2(30 BYTE),
  subt_generate_discriminator VARCHAR2(1 BYTE),
  subt_use_attribute_id VARCHAR2(36 BYTE),
  subt_discriminator_column_name VARCHAR2(30 BYTE),
  subt_discriminator_value VARCHAR2(50 BYTE),
  subt_complete_subtypes VARCHAR2(1 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);