CREATE TABLE "TEST_VSTSRedgate".dmrs_relationships (
  relationship_name VARCHAR2(256 BYTE) NOT NULL,
  model_id VARCHAR2(80 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  object_id VARCHAR2(80 BYTE) NOT NULL,
  ovid VARCHAR2(36 BYTE) NOT NULL,
  import_id VARCHAR2(70 BYTE),
  source_entity_name VARCHAR2(256 BYTE) NOT NULL,
  target_entity_name VARCHAR2(256 BYTE) NOT NULL,
  source_label VARCHAR2(100 BYTE),
  target_label VARCHAR2(100 BYTE),
  sourceto_target_cardinality VARCHAR2(3 BYTE) NOT NULL,
  targetto_source_cardinality VARCHAR2(3 BYTE) NOT NULL,
  source_optional CHAR NOT NULL,
  target_optional CHAR NOT NULL,
  dominant_role VARCHAR2(256 BYTE) NOT NULL,
  identifying CHAR NOT NULL,
  source_id VARCHAR2(70 BYTE) NOT NULL,
  source_ovid VARCHAR2(36 BYTE) NOT NULL,
  target_id VARCHAR2(70 BYTE) NOT NULL,
  target_ovid VARCHAR2(36 BYTE) NOT NULL,
  number_of_attributes NUMBER NOT NULL,
  transferable CHAR,
  in_arc CHAR,
  arc_id VARCHAR2(70 BYTE),
  model_name VARCHAR2(256 BYTE),
  source_name VARCHAR2(256 BYTE),
  target_name VARCHAR2(256 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);