CREATE TABLE "TEST_VSTSRedgate".dmrs_processes (
  process_id VARCHAR2(70 BYTE) NOT NULL,
  process_ovid VARCHAR2(36 BYTE) NOT NULL,
  process_name VARCHAR2(256 BYTE) NOT NULL,
  diagram_id VARCHAR2(70 BYTE) NOT NULL,
  diagram_ovid VARCHAR2(36 BYTE) NOT NULL,
  diagram_name VARCHAR2(256 BYTE) NOT NULL,
  transformation_task_id VARCHAR2(70 BYTE),
  transformation_task_ovid VARCHAR2(36 BYTE),
  transformation_task_name VARCHAR2(256 BYTE),
  parent_process_id VARCHAR2(70 BYTE),
  parent_process_ovid VARCHAR2(36 BYTE),
  parent_process_name VARCHAR2(256 BYTE),
  process_number VARCHAR2(30 BYTE),
  process_type VARCHAR2(30 BYTE),
  process_mode VARCHAR2(30 BYTE),
  "PRIORITY" VARCHAR2(30 BYTE),
  frequency_times NUMBER(10),
  frequency_time_unit VARCHAR2(30 BYTE),
  peak_periods_string VARCHAR2(30 BYTE),
  parameters_wrappers_string VARCHAR2(4000 BYTE),
  interactive_max_response_time NUMBER(10),
  interactive_response_time_unit VARCHAR2(30 BYTE),
  batch_min_transactions NUMBER(10),
  batch_time_unit VARCHAR2(30 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);