CREATE TABLE "TEST_VSTSRedgate".dmrs_collection_types (
  design_id VARCHAR2(70 BYTE) NOT NULL,
  design_ovid VARCHAR2(36 BYTE) NOT NULL,
  design_name VARCHAR2(256 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  model_name VARCHAR2(256 BYTE) NOT NULL,
  collection_type_id VARCHAR2(70 BYTE) NOT NULL,
  collection_type_ovid VARCHAR2(36 BYTE) NOT NULL,
  collection_type_name VARCHAR2(256 BYTE) NOT NULL,
  c_type VARCHAR2(30 BYTE),
  datatype_id VARCHAR2(70 BYTE),
  datatype_ovid VARCHAR2(36 BYTE),
  datatype_name VARCHAR2(256 BYTE),
  dt_type VARCHAR2(30 BYTE),
  dt_ref CHAR,
  max_element NUMBER,
  predefined CHAR,
  char_units CHAR(4 BYTE),
  t_size VARCHAR2(20 BYTE),
  t_precision NUMBER,
  t_scale NUMBER,
  datatype_kind VARCHAR2(20 BYTE),
  domain_name VARCHAR2(256 BYTE)
);