CREATE TABLE "TEST_VSTSRedgate".dmrs_diagrams (
  diagram_name VARCHAR2(256 BYTE) NOT NULL,
  object_id VARCHAR2(70 BYTE) NOT NULL,
  ovid VARCHAR2(36 BYTE) NOT NULL,
  diagram_type VARCHAR2(12 BYTE) NOT NULL,
  is_display CHAR NOT NULL,
  "VISIBLE" CHAR NOT NULL,
  master_diagram_id VARCHAR2(70 BYTE),
  master_diagram_ovid VARCHAR2(36 BYTE),
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  model_name VARCHAR2(256 BYTE) NOT NULL,
  subview_id VARCHAR2(70 BYTE),
  subview_ovid VARCHAR2(36 BYTE),
  subview_name VARCHAR2(256 BYTE),
  display_id VARCHAR2(70 BYTE),
  display_ovid VARCHAR2(36 BYTE),
  display_name VARCHAR2(256 BYTE),
  notation VARCHAR2(30 BYTE),
  show_all_details CHAR,
  show_names_only CHAR,
  show_elements CHAR,
  show_datatype CHAR,
  show_keys CHAR,
  autoroute CHAR,
  box_in_box CHAR,
  master_diagram_name VARCHAR2(256 BYTE),
  diagram_svg CLOB,
  diagram_pdf BLOB,
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);