CREATE TABLE "TEST_VSTSRedgate".dmrs_measures (
  measure_id VARCHAR2(70 BYTE) NOT NULL,
  measure_name VARCHAR2(256 BYTE) NOT NULL,
  measure_ovid VARCHAR2(36 BYTE) NOT NULL,
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_name VARCHAR2(256 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  cube_id VARCHAR2(70 BYTE),
  cube_name VARCHAR2(256 BYTE),
  cube_ovid VARCHAR2(36 BYTE),
  fact_object_id VARCHAR2(70 BYTE),
  fact_object_name VARCHAR2(256 BYTE),
  fact_object_ovid VARCHAR2(36 BYTE),
  oracle_long_name VARCHAR2(2000 BYTE),
  oracle_plural_name VARCHAR2(2000 BYTE),
  oracle_short_name VARCHAR2(2000 BYTE),
  fact_object_type VARCHAR2(30 BYTE),
  additivity_type VARCHAR2(30 BYTE),
  is_fact_dimension CHAR,
  is_formula CHAR,
  is_custom_formula CHAR,
  formula VARCHAR2(4000 BYTE),
  where_clause VARCHAR2(4000 BYTE),
  description VARCHAR2(4000 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);