CREATE TABLE "TEST_VSTSRedgate".dmrs_levels (
  level_id VARCHAR2(70 BYTE) NOT NULL,
  level_name VARCHAR2(256 BYTE) NOT NULL,
  level_ovid VARCHAR2(36 BYTE) NOT NULL,
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_name VARCHAR2(256 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  entity_id VARCHAR2(70 BYTE),
  entity_name VARCHAR2(256 BYTE),
  entity_ovid VARCHAR2(36 BYTE),
  name_column_id VARCHAR2(70 BYTE),
  name_column_name VARCHAR2(256 BYTE),
  name_column_ovid VARCHAR2(36 BYTE),
  value_column_id VARCHAR2(70 BYTE),
  value_column_name VARCHAR2(256 BYTE),
  value_column_ovid VARCHAR2(36 BYTE),
  oracle_long_name VARCHAR2(2000 BYTE),
  oracle_plural_name VARCHAR2(2000 BYTE),
  oracle_short_name VARCHAR2(2000 BYTE),
  root_identification VARCHAR2(30 BYTE),
  identification_value VARCHAR2(2000 BYTE),
  selection_criteria VARCHAR2(4000 BYTE),
  selection_criteria_description VARCHAR2(4000 BYTE),
  is_value_based_hierarchy CHAR,
  description VARCHAR2(4000 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);