CREATE TABLE "TEST_VSTSRedgate".dmrs_cubes (
  cube_id VARCHAR2(70 BYTE) NOT NULL,
  cube_name VARCHAR2(256 BYTE) NOT NULL,
  cube_ovid VARCHAR2(36 BYTE) NOT NULL,
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_name VARCHAR2(256 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  part_dimension_id VARCHAR2(70 BYTE),
  part_dimension_name VARCHAR2(256 BYTE),
  part_dimension_ovid VARCHAR2(36 BYTE),
  part_hierarchy_id VARCHAR2(70 BYTE),
  part_hierarchy_name VARCHAR2(256 BYTE),
  part_hierarchy_ovid VARCHAR2(36 BYTE),
  part_level_id VARCHAR2(70 BYTE),
  part_level_name VARCHAR2(256 BYTE),
  part_level_ovid VARCHAR2(36 BYTE),
  full_cube_slice_id VARCHAR2(70 BYTE),
  full_cube_slice_name VARCHAR2(256 BYTE),
  full_cube_slice_ovid VARCHAR2(36 BYTE),
  oracle_long_name VARCHAR2(2000 BYTE),
  oracle_plural_name VARCHAR2(2000 BYTE),
  oracle_short_name VARCHAR2(2000 BYTE),
  is_compressed_composites CHAR,
  is_global_composites CHAR,
  is_partitioned CHAR,
  is_virtual CHAR,
  part_description VARCHAR2(4000 BYTE),
  description VARCHAR2(4000 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);