CREATE TABLE "TEST_VSTSRedgate".dmrs_keys (
  key_name VARCHAR2(256 BYTE) NOT NULL,
  object_id VARCHAR2(70 BYTE) NOT NULL,
  ovid VARCHAR2(36 BYTE) NOT NULL,
  import_id VARCHAR2(70 BYTE),
  container_id VARCHAR2(70 BYTE) NOT NULL,
  container_ovid VARCHAR2(36 BYTE) NOT NULL,
  "STATE" VARCHAR2(20 BYTE) NOT NULL,
  synonyms VARCHAR2(4000 BYTE),
  entity_name VARCHAR2(256 BYTE) NOT NULL,
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);