CREATE TABLE "TEST_VSTSRedgate".dmrs_rollup_links (
  rollup_link_id VARCHAR2(70 BYTE) NOT NULL,
  rollup_link_name VARCHAR2(256 BYTE) NOT NULL,
  rollup_link_ovid VARCHAR2(36 BYTE) NOT NULL,
  model_id VARCHAR2(70 BYTE) NOT NULL,
  model_name VARCHAR2(256 BYTE) NOT NULL,
  model_ovid VARCHAR2(36 BYTE) NOT NULL,
  parent_object_id VARCHAR2(70 BYTE),
  parent_object_name VARCHAR2(256 BYTE),
  parent_object_ovid VARCHAR2(36 BYTE),
  child_object_id VARCHAR2(70 BYTE),
  child_object_name VARCHAR2(256 BYTE),
  child_object_ovid VARCHAR2(36 BYTE),
  fact_entity_id VARCHAR2(70 BYTE),
  fact_entity_name VARCHAR2(256 BYTE),
  fact_entity_ovid VARCHAR2(36 BYTE),
  parent_object_type VARCHAR2(30 BYTE),
  child_object_type VARCHAR2(30 BYTE),
  oracle_long_name VARCHAR2(2000 BYTE),
  oracle_plural_name VARCHAR2(2000 BYTE),
  oracle_short_name VARCHAR2(2000 BYTE),
  default_aggr_operator VARCHAR2(256 BYTE),
  is_role_playing CHAR,
  is_sparse_dimension CHAR,
  description VARCHAR2(4000 BYTE),
  design_ovid VARCHAR2(36 BYTE) NOT NULL
);