CREATE TABLE "TEST_VSTSRedgate".md_target_all_errors (
  "OWNER" VARCHAR2(128 BYTE) NOT NULL,
  "NAME" VARCHAR2(128 BYTE) NOT NULL,
  "TYPE" VARCHAR2(12 BYTE),
  "SEQUENCE" NUMBER NOT NULL,
  line NUMBER NOT NULL,
  position NUMBER NOT NULL,
  "TEXT" VARCHAR2(4000 BYTE) NOT NULL,
  "ATTRIBUTE" VARCHAR2(9 BYTE),
  message_number NUMBER
);