CREATE TABLE "TEST_VSTSRedgate".mvewriskdeals (
  companycode NUMBER(8),
  dealnumber VARCHAR2(25 BYTE),
  dealserial NUMBER,
  crossdeal CHAR,
  dealtype CHAR,
  executedate DATE,
  hedgecode NUMBER(8),
  buycode NUMBER,
  bankcode NUMBER(8),
  currencycode NUMBER(8),
  othercode NUMBER(8),
  exchangerate NUMBER,
  baseamount NUMBER(15,2),
  otheramount NUMBER(15,2),
  dealmaturity DATE,
  balancefcy NUMBER,
  balanceinr NUMBER,
  usdrate NUMBER,
  inrrate NUMBER,
  mtmrate NUMBER,
  washrate NUMBER,
  userid VARCHAR2(30 BYTE),
  dealmonth NUMBER,
  today DATE,
  counterparty VARCHAR2(4000 BYTE),
  basecurrency VARCHAR2(4000 BYTE),
  othercurrency VARCHAR2(4000 BYTE),
  usdeq NUMBER,
  inreq NUMBER,
  profitloss NUMBER
);