CREATE TABLE "TEST_VSTSRedgate".reporttest (
  status VARCHAR2(25 BYTE),
  typeoftrans VARCHAR2(25 BYTE),
  companycode NUMBER(8),
  backupdeal NUMBER(8),
  productcode NUMBER(8),
  exchangerate NUMBER(15,2),
  basecurrency NUMBER(8),
  othercurrency NUMBER(8),
  financialyear VARCHAR2(15 BYTE),
  maturitymonth VARCHAR2(15 BYTE),
  baseamount NUMBER(8),
  gainloss NUMBER(10,2),
  wtdavgrate NUMBER(10,2),
  baseamountinr NUMBER(12,2),
  forcastedexpo NUMBER(15,4),
  hedged NUMBER(15,4),
  percenthedged NUMBER(15,2),
  hedgedpolicy NUMBER(12,2),
  hedgeratemonth NUMBER(15,2),
  additionalcov NUMBER(15,2),
  unhedgedexpo NUMBER(15,2),
  forwardrate NUMBER(15,2)
);