CREATE GLOBAL TEMPORARY TABLE "TEST_VSTSRedgate".ss2k5_types (
  db_id NUMBER(10),
  "NAME" VARCHAR2(256 BYTE) NOT NULL,
  user_type_id NUMBER(10) NOT NULL,
  system_type_id NUMBER(3) NOT NULL
)
ON COMMIT PRESERVE ROWS;