CREATE GLOBAL TEMPORARY TABLE "TEST_VSTSRedgate".ss2k5_sysproperties (
  db_id NUMBER(5),
  major_id NUMBER(5) NOT NULL,
  minor_id NUMBER(5) NOT NULL,
  "NAME" VARCHAR2(500 BYTE) NOT NULL,
  "VALUE" VARCHAR2(1000 BYTE) NOT NULL
)
ON COMMIT PRESERVE ROWS;