CREATE GLOBAL TEMPORARY TABLE "TEST_VSTSRedgate".ss2k5_server_principals (
  db_id NUMBER(10),
  "NAME" VARCHAR2(256 BYTE) NOT NULL,
  "SID" RAW(85),
  "TYPE" CHAR(2 BYTE) NOT NULL
)
ON COMMIT PRESERVE ROWS;