CREATE GLOBAL TEMPORARY TABLE "TEST_VSTSRedgate".ss2k5_tables (
  db_id NUMBER(10),
  "NAME" VARCHAR2(256 BYTE) NOT NULL,
  object_id NUMBER(10) NOT NULL,
  schema_id NUMBER(10) NOT NULL,
  "TYPE" CHAR(2 BYTE) NOT NULL
)
ON COMMIT PRESERVE ROWS;