CREATE GLOBAL TEMPORARY TABLE "TEST_VSTSRedgate".stage_ss2k5_sysproperties (
  svrid_fk NUMBER(38),
  dbid_gen_fk NUMBER(38),
  "CLASS" NUMBER(38) NOT NULL,
  major_id NUMBER(38) NOT NULL,
  minor_id NUMBER(38) NOT NULL,
  "NAME" VARCHAR2(500 CHAR) NOT NULL,
  "VALUE" VARCHAR2(1000 CHAR) NOT NULL
)
ON COMMIT PRESERVE ROWS;