CREATE GLOBAL TEMPORARY TABLE "TEST_VSTSRedgate".stage_syb12_sysreferences (
  svrid_fk NUMBER,
  dbid_gen_fk NUMBER,
  constraint_gen_fk NUMBER,
  table_id_gen_fk NUMBER,
  ref_table_id_gen_fk NUMBER,
  frgn_dbid_gen_fk NUMBER,
  pmry_dbid_gen_fk NUMBER,
  indexid NUMBER,
  constrid NUMBER,
  tableid NUMBER,
  reftabid NUMBER,
  keycnt NUMBER,
  status NUMBER,
  frgndbid NUMBER,
  pmrydbid NUMBER,
  spare2 NUMBER,
  fokey1 NUMBER,
  fokey2 NUMBER,
  fokey3 NUMBER,
  fokey4 NUMBER,
  fokey5 NUMBER,
  fokey6 NUMBER,
  fokey7 NUMBER,
  fokey8 NUMBER,
  fokey9 NUMBER,
  fokey10 NUMBER,
  fokey11 NUMBER,
  fokey12 NUMBER,
  fokey13 NUMBER,
  fokey14 NUMBER,
  fokey15 NUMBER,
  fokey16 NUMBER,
  refkey1 NUMBER,
  refkey2 NUMBER,
  refkey3 NUMBER,
  refkey4 NUMBER,
  refkey5 NUMBER,
  refkey6 NUMBER,
  refkey7 NUMBER,
  refkey8 NUMBER,
  refkey9 NUMBER,
  refkey10 NUMBER,
  refkey11 NUMBER,
  refkey12 NUMBER,
  refkey13 NUMBER,
  refkey14 NUMBER,
  refkey15 NUMBER,
  refkey16 NUMBER,
  frgndbname VARCHAR2(30 BYTE),
  pmrydbname VARCHAR2(30 BYTE)
)
ON COMMIT PRESERVE ROWS;