CREATE GLOBAL TEMPORARY TABLE "TEST_VSTSRedgate".syb12_sysindexes (
  db_id NUMBER(10),
  table_id NUMBER(10),
  index_name VARCHAR2(256 BYTE) NOT NULL,
  "INDEX_DESC" VARCHAR2(1000 BYTE),
  index_keys VARCHAR2(1000 BYTE)
)
ON COMMIT PRESERVE ROWS;