CREATE TABLE "TEST_VSTSRedgate".trdepo003b (
  schm_company_code NUMBER(8) NOT NULL,
  schm_counter_party NUMBER(8) NOT NULL,
  schm_plan_code NUMBER(8) NOT NULL,
  schm_short_desc VARCHAR2(10 BYTE),
  schm_long_desc VARCHAR2(50 BYTE),
  schm_interest_plan NUMBER(8),
  schm_currency_code NUMBER(8) NOT NULL,
  schm_effective_date DATE NOT NULL,
  schm_maturity_type NUMBER(8),
  schm_intrepayment_type NUMBER(8),
  schm_principal_type NUMBER(8),
  schm_installment_type NUMBER(8),
  schm_autorenew_type NUMBER(8),
  schm_interest_basedon NUMBER(8),
  schm_rounding_factor NUMBER(8),
  schm_rounding_to NUMBER(8),
  schm_holiday_indpaid NUMBER(8),
  schm_tds_plan NUMBER(8),
  schm_tds_drac NUMBER(15),
  schm_tds_crac NUMBER(15),
  schm_tds_surchargecrac NUMBER(8),
  schm_record_status NUMBER(8),
  schm_mail_alert VARCHAR2(200 BYTE),
  schm_user_remarks VARCHAR2(200 BYTE),
  schm_financial_year NUMBER(8),
  schm_add_date DATE,
  schm_create_date DATE,
  schm_period_in NUMBER(8),
  schm_entry_detail XMLTYPE,
  CONSTRAINT pk_trdepo003 PRIMARY KEY (schm_plan_code,schm_company_code,schm_currency_code,schm_counter_party,schm_effective_date)
);