CREATE TABLE "TEST_VSTSRedgate".trmaster410 (
  mfsc_company_code NUMBER(8),
  mfsc_location_code NUMBER(8),
  mfsc_nav_code VARCHAR2(10 BYTE) NOT NULL,
  mfsc_amc_code NUMBER(8),
  mfsc_short_description VARCHAR2(15 BYTE),
  mfsc_long_description VARCHAR2(200 BYTE),
  mfsc_scheme_type NUMBER(8),
  mfsc_scheme_category NUMBER(8),
  mfsc_scheme_navname VARCHAR2(200 BYTE),
  mfsc_scheme_minamount NUMBER(15,2),
  mfsc_launch_date DATE,
  mfsc_closure_date DATE,
  mfsc_closedflag NUMBER(8),
  mfsc_entry_load NUMBER(5),
  mfsc_exit_load NUMBER(5),
  mfsc_exit_aplicable NUMBER(5),
  mfsc_reinvestment_schema NUMBER(8),
  mfsc_entry_details XMLTYPE,
  mfsc_add_date DATE,
  mfsc_create_date DATE,
  mfsc_record_status NUMBER(8),
  mfsc_mf_remarks VARCHAR2(1024 BYTE),
  CONSTRAINT trmaster410 PRIMARY KEY (mfsc_nav_code)
);