CREATE TABLE "TEST_VSTSRedgate".trmaster404 (
  mfsc_company_code NUMBER(8),
  mfsc_location_code NUMBER(8),
  mfsc_scheme_code NUMBER(8) NOT NULL,
  mfsc_nav_code NUMBER(8),
  mfsc_amc_code NUMBER(8),
  mfsc_source_code VARCHAR2(50 BYTE),
  mfsc_scheme_navname VARCHAR2(200 BYTE),
  mfsc_folio_number VARCHAR2(25 BYTE),
  mfsc_short_description VARCHAR2(15 BYTE),
  mfsc_long_description VARCHAR2(200 BYTE),
  mfsc_scheme_type NUMBER(8),
  mfsc_scheme_category NUMBER(8),
  mfsc_scheme_minamount NUMBER(15,2),
  mfsc_launch_date DATE,
  mfsc_closure_date DATE,
  mfsc_closedflag NUMBER(8),
  mfsc_entry_load NUMBER(15,2),
  mfsc_exit_load NUMBER(15,2),
  mfsc_exit_aplicable NUMBER(5),
  mfsc_reinvestment_schema NUMBER(8),
  mfsc_plan_name NUMBER(8),
  mfsc_option_type NUMBER(8),
  mfsc_dividend_period NUMBER(8),
  mfsc_investment_type NUMBER(8),
  mfsc_lock_perioddays NUMBER(4),
  mfsc_lock_periodmonths NUMBER(4),
  mfsc_lock_periodyears NUMBER(4),
  mfsc_bank_code NUMBER(8),
  mfsc_ifsc_code VARCHAR2(20 BYTE),
  mfsc_account_number VARCHAR2(25 BYTE),
  mfsc_account_name VARCHAR2(200 BYTE),
  mfsc_branch_name VARCHAR2(50 BYTE),
  mfsc_mf_remarks VARCHAR2(500 BYTE),
  mfsc_user_remarks VARCHAR2(4000 BYTE),
  mfsc_add_date DATE,
  mfsc_create_date DATE,
  mfsc_entry_details XMLTYPE,
  mfsc_record_status NUMBER(8),
  mfsc_pnl_param NUMBER(8),
  CONSTRAINT trmaster404_pk1 PRIMARY KEY (mfsc_scheme_code)
);