CREATE TABLE "TEST_VSTSRedgate".trmaster412 (
  debe_company_code NUMBER(8),
  debe_location_code NUMBER(8),
  debe_pick_code NUMBER(8) NOT NULL,
  debe_instrument_type NUMBER(8),
  debe_short_description VARCHAR2(15 BYTE),
  debe_long_description VARCHAR2(50 BYTE),
  debe_isin_number VARCHAR2(25 BYTE),
  debe_instrument_name VARCHAR2(200 BYTE),
  debe_nsdl_description VARCHAR2(200 BYTE),
  debe_currency_code NUMBER(8),
  debe_issue_price NUMBER(15,2),
  debe_face_value NUMBER(15,2),
  debe_issue_date DATE,
  debe_maturity_date DATE,
  debe_coupon_rate NUMBER(15,2),
  debe_interest_type NUMBER(8),
  debe_int_payfrequency NUMBER(8),
  debe_int_paydate VARCHAR2(15 BYTE),
  debe_put_option VARCHAR2(100 BYTE),
  debe_call_option VARCHAR2(100 BYTE),
  debe_put_date VARCHAR2(200 BYTE),
  debe_call_date VARCHAR2(200 BYTE),
  debe_certificate_nos VARCHAR2(200 BYTE),
  debe_registrar_bpid VARCHAR2(200 BYTE),
  debe_address VARCHAR2(500 BYTE),
  debe_credit_rating VARCHAR2(200 BYTE),
  debe_lead_manager VARCHAR2(200 BYTE),
  debe_remarks VARCHAR2(200 BYTE),
  debe_tax_type NUMBER(8),
  debe_trade_type NUMBER(1),
  debe_bond_type NUMBER(8),
  debe_issuer_bank NUMBER(8),
  debe_issuer_branch VARCHAR2(50 BYTE),
  debe_account_number VARCHAR2(25 BYTE),
  debe_account_name VARCHAR2(25 BYTE),
  debe_ifsc_code VARCHAR2(25 BYTE),
  debe_add_date DATE,
  debe_create_date DATE,
  debe_entry_detail XMLTYPE,
  debe_record_status NUMBER(8),
  debe_intbased_on NUMBER(8),
  CONSTRAINT trmaster412_pk PRIMARY KEY (debe_pick_code)
);