CREATE TABLE "TEST_VSTSRedgate".trmaster306a (
  brnh_company_code NUMBER(8) NOT NULL,
  brnh_bank_code NUMBER(8) NOT NULL,
  brnh_short_description VARCHAR2(15 BYTE),
  brnh_long_description VARCHAR2(75 BYTE),
  brnh_icontact_person VARCHAR2(50 BYTE),
  brnh_econtact_person VARCHAR2(50 BYTE),
  brnh_address_1 VARCHAR2(75 BYTE) NOT NULL,
  brnh_address_2 VARCHAR2(50 BYTE),
  brnh_address_3 VARCHAR2(50 BYTE),
  brnh_address_4 VARCHAR2(50 BYTE),
  brnh_ifsc_code VARCHAR2(25 BYTE),
  brnh_phone_numbers VARCHAR2(200 BYTE),
  brnh_fax_numbers VARCHAR2(200 BYTE),
  brnh_email_id VARCHAR2(100 BYTE),
  brnh_account_type NUMBER(8) NOT NULL,
  brnh_account_number VARCHAR2(25 BYTE) NOT NULL,
  brnh_create_date DATE NOT NULL,
  brnh_add_date DATE NOT NULL,
  brnh_entry_detail XMLTYPE,
  brnh_record_status NUMBER(8) NOT NULL,
  brnh_sap_code VARCHAR2(25 BYTE),
  brnh_location_code NUMBER(8),
  brnh_swift_code VARCHAR2(50 BYTE),
  brnh_host_host NUMBER(8),
  brnh_minimum_balance NUMBER(15),
  CONSTRAINT trmaster306a_pk PRIMARY KEY (brnh_bank_code,brnh_account_number)
);