CREATE TABLE "TEST_VSTSRedgate".trmaster411 (
  debt_company_code NUMBER(8),
  debt_location_code NUMBER(8),
  debt_isin_number VARCHAR2(25 BYTE),
  debt_instrument_name VARCHAR2(500 BYTE),
  debt_nsdl_description VARCHAR2(200 BYTE),
  debt_issue_price VARCHAR2(20 BYTE),
  debt_face_value VARCHAR2(20 BYTE),
  debt_issue_date DATE,
  debt_maturity_date DATE,
  debt_coupon_rate VARCHAR2(20 BYTE),
  debt_intpayment_frequency VARCHAR2(200 BYTE),
  debt_putcall_option VARCHAR2(200 BYTE),
  debt_certificate_number VARCHAR2(200 BYTE),
  debt_bpid_number VARCHAR2(200 BYTE),
  debt_physical_security VARCHAR2(500 BYTE),
  debt_creditdetails VARCHAR2(500 BYTE),
  debt_credit_rating VARCHAR2(25 BYTE),
  debt_rating_agency VARCHAR2(50 BYTE),
  debt_arranger_details VARCHAR2(500 BYTE),
  debt_create_date DATE,
  debt_add_date DATE,
  debt_entry_details XMLTYPE,
  debt_record_status NUMBER(8),
  debt_remarks VARCHAR2(500 BYTE),
  debt_instrument_type NUMBER(8),
  debt_issuer_company VARCHAR2(50 BYTE)
);