CREATE TABLE "TEST_VSTSRedgate".trmaster501 (
  comx_company_code NUMBER(8) NOT NULL,
  comx_pick_code NUMBER(8) NOT NULL,
  comx_short_description VARCHAR2(15 BYTE) NOT NULL,
  comx_long_description VARCHAR2(50 BYTE) NOT NULL,
  comx_contact_person VARCHAR2(50 BYTE),
  comx_address_1 VARCHAR2(50 BYTE) NOT NULL,
  comx_address_2 VARCHAR2(50 BYTE),
  comx_address_3 VARCHAR2(50 BYTE),
  comx_address_4 VARCHAR2(50 BYTE),
  comx_phone_numbers VARCHAR2(200 BYTE),
  comx_fax_numbers VARCHAR2(200 BYTE),
  comx_website_url VARCHAR2(100 BYTE),
  comx_email_id VARCHAR2(100 BYTE),
  comx_exchange_type NUMBER(8) NOT NULL,
  comx_country_code NUMBER(8) NOT NULL,
  comx_default_due NUMBER(2),
  comx_create_date DATE NOT NULL,
  comx_add_date DATE NOT NULL,
  comx_entry_detail XMLTYPE,
  comx_record_status NUMBER(8) NOT NULL,
  comx_location_code NUMBER(8),
  CONSTRAINT pk_trmaster501 PRIMARY KEY (comx_company_code,comx_pick_code)
);