CREATE TABLE "TEST_VSTSRedgate".trmaster503 (
  cpro_company_code NUMBER(8) NOT NULL,
  cpro_exchange_code NUMBER(8) NOT NULL,
  cpro_pick_code NUMBER(8),
  cpro_short_description VARCHAR2(15 BYTE) NOT NULL,
  cpro_long_description VARCHAR2(50 BYTE) NOT NULL,
  cpro_effective_date DATE NOT NULL,
  cpro_due_date DATE,
  cpro_product_category NUMBER(8) NOT NULL,
  cpro_ticker_symbol VARCHAR2(25 BYTE),
  cpro_trade_unit NUMBER(7) NOT NULL,
  cpro_trade_uom NUMBER(8) NOT NULL,
  cpro_quote_value NUMBER(7) NOT NULL,
  cpro_quote_uom NUMBER(8) NOT NULL,
  cpro_conversion_value NUMBER(15,4),
  cpro_tick_size NUMBER(8,2),
  cpro_tick_value NUMBER(7),
  cpro_tick_uom NUMBER(8),
  cpro_order_max NUMBER(7),
  cpro_order_uom NUMBER(8),
  cpro_position_max NUMBER(7),
  cpro_position_uom NUMBER(8),
  cpro_delivery_unit NUMBER(7),
  cpro_delivery_uom NUMBER(8),
  cpro_price_band NUMBER(5,2),
  cpro_initial_margin NUMBER(5,2),
  cpro_quality_detail VARCHAR2(512 BYTE),
  cpro_delivery_places VARCHAR2(200 BYTE),
  cpro_commodity_specs BLOB,
  cpro_create_date DATE NOT NULL,
  cpro_add_date DATE NOT NULL,
  cpro_entry_detail XMLTYPE,
  cpro_record_status NUMBER(8) NOT NULL,
  cpro_product_code NUMBER(8),
  cpro_location_code NUMBER(8),
  cpro_file_path VARCHAR2(100 BYTE)
);