CREATE TABLE "TEST_VSTSRedgate".trstaging021 (
  record_type VARCHAR2(5 BYTE),
  company_code VARCHAR2(10 BYTE),
  location_code VARCHAR2(10 BYTE),
  lob_code VARCHAR2(10 BYTE),
  document_date VARCHAR2(10 BYTE),
  reference_no VARCHAR2(25 BYTE),
  reference_nodate VARCHAR2(10 BYTE),
  product_code VARCHAR2(15 BYTE),
  product_description VARCHAR2(50 BYTE),
  customer_code VARCHAR2(15 BYTE),
  customer_name VARCHAR2(50 BYTE),
  currency_code VARCHAR2(35 BYTE),
  payment_terms_desc VARCHAR2(50 BYTE),
  payment_terms VARCHAR2(10 BYTE),
  invoice_fcy NUMBER(15,6),
  invoice_rate NUMBER(15,6),
  invoice_inr NUMBER(15,6),
  invoice_item VARCHAR2(15 BYTE),
  uom_qty NUMBER(15,6),
  uom_code VARCHAR2(15 BYTE),
  uom_rate NUMBER(15,6),
  nett_weight NUMBER(15,6),
  gross_weight NUMBER(15,6),
  invoice_no# VARCHAR2(25 BYTE),
  sales_order_no# VARCHAR2(25 BYTE)
);