CREATE TABLE "TEST_VSTSRedgate".trstaging019 (
  company_name VARCHAR2(100 BYTE),
  intimation_date DATE,
  commodity VARCHAR2(100 BYTE),
  supplier VARCHAR2(100 BYTE),
  contractno_dtae VARCHAR2(500 BYTE),
  vessel_name VARCHAR2(200 BYTE),
  load_port VARCHAR2(100 BYTE),
  disport VARCHAR2(100 BYTE),
  bill_of_lading_quantity NUMBER(15,4),
  bill_date DATE,
  bill_rate NUMBER(15,6),
  due_date DATE,
  cfr NUMBER(15,6),
  provisional_cf_value NUMBER(15,2),
  lcrv_cadrv_no VARCHAR2(500 BYTE),
  remarks VARCHAR2(200 BYTE),
  recordstatus NUMBER(8),
  entrydate DATE
);