CREATE TABLE "TEST_VSTSRedgate".trstaging023 (
  "TYPE" VARCHAR2(5 BYTE),
  company_code VARCHAR2(25 BYTE),
  location_code VARCHAR2(25 BYTE),
  lob_code VARCHAR2(25 BYTE),
  purchase_order_no# VARCHAR2(25 BYTE),
  created_date VARCHAR2(25 BYTE),
  vendor_no# VARCHAR2(25 BYTE),
  vendor_name VARCHAR2(50 BYTE),
  document_no# VARCHAR2(25 BYTE),
  document_date VARCHAR2(25 BYTE),
  currency_code VARCHAR2(25 BYTE),
  payment_text VARCHAR2(25 BYTE),
  payment_terms VARCHAR2(25 BYTE),
  material_no# VARCHAR2(25 BYTE),
  uom VARCHAR2(10 BYTE),
  quantity VARCHAR2(10 BYTE),
  amount_in_local_currency VARCHAR2(25 BYTE),
  amount VARCHAR2(25 BYTE),
  exchange_rate VARCHAR2(25 BYTE),
  reference_no# VARCHAR2(25 BYTE),
  due_date VARCHAR2(10 BYTE)
);