CREATE TABLE "TEST_VSTSRedgate".trstaging024 (
  record_type VARCHAR2(10 BYTE),
  principal_interest VARCHAR2(10 BYTE),
  posting_status VARCHAR2(5 BYTE),
  company_code VARCHAR2(5 BYTE),
  location_code VARCHAR2(10 BYTE),
  lob_code VARCHAR2(10 BYTE),
  buyerscreditnumber VARCHAR2(25 BYTE),
  requestdate VARCHAR2(10 BYTE),
  localbank VARCHAR2(25 BYTE),
  currency_code VARCHAR2(10 BYTE),
  appliedamount NUMBER(15,6),
  sanctionedfcy NUMBER(15,6),
  conversionrate NUMBER(15,6),
  sanctionedinr NUMBER(15,6),
  sanctionreference VARCHAR2(25 BYTE),
  sanctiondate VARCHAR2(10 BYTE),
  noofdays VARCHAR2(10 BYTE),
  duedate VARCHAR2(10 BYTE),
  libortype VARCHAR2(15 BYTE),
  liborrate NUMBER(15,6),
  interestspread NUMBER(15,6),
  interestrate NUMBER(15,6),
  interestfcy NUMBER(15,6),
  repaiddate VARCHAR2(10 BYTE),
  repaidrate NUMBER(15,6),
  purchase_order_number VARCHAR2(25 BYTE),
  lcrv_no VARCHAR2(25 BYTE)
);