CREATE TABLE "TEST_VSTSRedgate".trstaging015_arc (
  executedate VARCHAR2(20 BYTE),
  linkamount VARCHAR2(20 BYTE),
  basecurrency VARCHAR2(20 BYTE),
  othercurrency VARCHAR2(100 BYTE),
  bank VARCHAR2(100 BYTE),
  maturitydate VARCHAR2(20 BYTE),
  amountfcy VARCHAR2(20 BYTE),
  forwardrate VARCHAR2(20 BYTE),
  contractnumber VARCHAR2(100 BYTE),
  buysell VARCHAR2(20 BYTE),
  companycode VARCHAR2(20 BYTE),
  locationcode VARCHAR2(20 BYTE),
  product VARCHAR2(20 BYTE),
  subproduct VARCHAR2(20 BYTE),
  entrydate VARCHAR2(20 BYTE),
  guid VARCHAR2(50 BYTE),
  rowno NUMBER(5),
  processstatus NUMBER(8),
  remarks VARCHAR2(4000 BYTE),
  basecurrency_code NUMBER(8),
  othercurrency_code NUMBER(8),
  bank_code NUMBER(8),
  buysell_code NUMBER(8),
  companycode_code NUMBER(8),
  locationcode_code NUMBER(8),
  product_code NUMBER(8),
  subproduct_code NUMBER(8),
  sysreferencenumber VARCHAR2(25 BYTE)
);