CREATE TABLE "TEST_VSTSRedgate".trstaging025 (
  company_code VARCHAR2(50 BYTE),
  flow_type VARCHAR2(50 BYTE),
  posting_status VARCHAR2(50 BYTE),
  lob_code VARCHAR2(50 BYTE),
  loan_number VARCHAR2(50 BYTE),
  loan_type VARCHAR2(50 BYTE),
  local_bank VARCHAR2(50 BYTE),
  currencycode VARCHAR2(50 BYTE),
  instalment_frequency VARCHAR2(50 BYTE),
  due_date VARCHAR2(20 BYTE),
  libour_rate VARCHAR2(50 BYTE),
  interest_rate VARCHAR2(50 BYTE),
  interestspread VARCHAR2(50 BYTE),
  interesttype VARCHAR2(50 BYTE),
  sactionedfcy VARCHAR2(50 BYTE),
  sanctionedrate VARCHAR2(50 BYTE),
  sanctionedinr VARCHAR2(50 BYTE),
  "ACTIVITY" VARCHAR2(50 BYTE),
  appliedamount VARCHAR2(50 BYTE),
  effectivedate VARCHAR2(20 BYTE),
  portfolio VARCHAR2(50 BYTE),
  foreignbank VARCHAR2(50 BYTE),
  libortype VARCHAR2(50 BYTE),
  startdate VARCHAR2(20 BYTE)
);