CREATE TABLE "TEST_VSTSRedgate".trsystem169 (
  schm_company_code NUMBER(8),
  schm_counter_party NUMBER(8),
  schm_plan_code NUMBER(8),
  schm_short_desc VARCHAR2(10 BYTE),
  schm_long_desc VARCHAR2(50 BYTE),
  schm_interest_plan NUMBER(8),
  schm_currency_code NUMBER(8),
  schm_effective_date DATE,
  schm_maturity_type NUMBER(8),
  schm_intrepayment_type NUMBER(8),
  schm_principal_type NUMBER(8),
  schm_installment_type NUMBER(8),
  schm_autorenew_type NUMBER(8),
  schm_interest_basedon NUMBER(8),
  schm_holiday_indpaid NUMBER(8),
  schm_tds_plan NUMBER(8),
  schm_tds_drac NUMBER(15),
  schm_tds_crac NUMBER(15),
  schm_tds_surchargecrac NUMBER(8),
  schm_record_status NUMBER(8),
  schm_mail_alert VARCHAR2(200 BYTE),
  schm_user_remarks VARCHAR2(200 BYTE),
  schm_financial_year NUMBER(8),
  schm_add_date DATE,
  schm_create_date DATE,
  schm_period_in NUMBER(8),
  schm_entry_detail XMLTYPE,
  schm_intcredit_to NUMBER(8),
  schm_preclose_interest NUMBER(8),
  schm_location_code NUMBER(8),
  imagetype VARCHAR2(10 BYTE),
  entity VARCHAR2(30 BYTE),
  datestamp VARCHAR2(25 BYTE),
  workdate DATE
);