CREATE TABLE "TEST_VSTSRedgate".trsystem009 (
  rate_currency_code NUMBER(8) NOT NULL,
  rate_for_currency NUMBER(8) NOT NULL,
  rate_effective_date DATE NOT NULL,
  rate_serial_number NUMBER(5) NOT NULL,
  rate_rate_time VARCHAR2(10 BYTE),
  rate_time_stamp VARCHAR2(25 BYTE),
  rate_rate_description VARCHAR2(50 BYTE),
  rate_spot_bid NUMBER(15,6),
  rate_spot_ask NUMBER(15,6),
  rate_month1_bid NUMBER(15,6),
  rate_month1_ask NUMBER(15,6),
  rate_month2_bid NUMBER(15,6),
  rate_month2_ask NUMBER(15,6),
  rate_month3_bid NUMBER(15,6),
  rate_month3_ask NUMBER(15,6),
  rate_month6_bid NUMBER(15,6),
  rate_month6_ask NUMBER(15,6),
  rate_month9_bid NUMBER(15,6),
  rate_month9_ask NUMBER(15,6),
  rate_month12_bid NUMBER(15,6),
  rate_month12_ask NUMBER(15,6),
  rate_create_date DATE NOT NULL,
  rate_add_date DATE NOT NULL,
  rate_entry_detail XMLTYPE,
  rate_record_status NUMBER(8) NOT NULL,
  rate_usd_rate NUMBER(15,6),
  rate_month4_bid NUMBER(15,6),
  rate_month4_ask NUMBER(15,6),
  rate_month5_bid NUMBER(15,6),
  rate_month5_ask NUMBER(15,6),
  rate_month7_bid NUMBER(15,6),
  rate_month7_ask NUMBER(15,6),
  rate_month8_bid NUMBER(15,6),
  rate_month8_ask NUMBER(15,6),
  rate_month10_bid NUMBER(15,6),
  rate_month10_ask NUMBER(15,6),
  rate_month11_bid NUMBER(15,6),
  rate_month11_ask NUMBER(15,6),
  rate_cash_bid NUMBER(15,6),
  rate_cash_ask NUMBER(15,6),
  rate_tom_bid NUMBER(15,6),
  rate_tom_ask NUMBER(15,6),
  CONSTRAINT pk_trsystem009 PRIMARY KEY (rate_currency_code,rate_for_currency,rate_effective_date,rate_serial_number)
);