CREATE TABLE "TEST_VSTSRedgate".trsystem972 (
  monthno NUMBER(2),
  monthname VARCHAR2(3 BYTE),
  "YEARS" NUMBER(4),
  currency NUMBER(8),
  company NUMBER(8),
  exports NUMBER(15,2),
  exportslink VARCHAR2(100 BYTE),
  expforwards NUMBER(15,2),
  expforwardlink VARCHAR2(100 BYTE),
  expavgdealrate NUMBER(15,4),
  expavgbookrate NUMBER(15,4),
  imports NUMBER(15,2),
  importslink VARCHAR2(100 BYTE),
  impforwards NUMBER(15,2),
  impforwardlink VARCHAR2(100 BYTE),
  impavgdealrate NUMBER(15,4),
  impavgbookrate NUMBER(15,4),
  exportstoploss NUMBER(15,2),
  importstoploss NUMBER(15,2),
  asondate DATE,
  exportsinr NUMBER(15,2),
  expforwardsinr NUMBER(15,2),
  importsinr NUMBER(15,2),
  impforwardsinr NUMBER(15,2),
  frwcontract NUMBER(15,2),
  futureimp NUMBER(15,2),
  optionimp NUMBER(15,2),
  pclavailedimp NUMBER(15,2),
  orderinhandimp NUMBER(15,2),
  rupeepcimp NUMBER(15,2),
  impexp NUMBER(1),
  productcode NUMBER(8),
  mtmrate NUMBER(15,4),
  mtmrateexp NUMBER(15,4),
  mtmrateimp NUMBER(15,4)
);