CREATE TABLE "TEST_VSTSRedgate".trsystem996a (
  crsh_company_code NUMBER(8),
  crsh_location_code NUMBER(8),
  crsh_portfolio_code NUMBER(8),
  crsh_subportfolio_code NUMBER(8),
  crsh_reference_date DATE,
  crsh_currency_code NUMBER(8),
  crsh_for_currency NUMBER(8),
  crsh_maturity_date DATE,
  crsh_export_fcy NUMBER(15,2),
  crsh_import_fcy NUMBER(15,2),
  crsh_net_exposure NUMBER(15,2),
  crsh_hedge_sell NUMBER(15,2),
  crsh_hedge_sellrate NUMBER(15,2),
  crsh_hedge_buy NUMBER(15,2),
  crsh_hedge_buyrate NUMBER(15,2),
  crsh_tot_hedge NUMBER(15,2),
  crsh_firstforward_rate NUMBER(15,6),
  crsh_percentage_hedge NUMBER(15,2),
  crsh_lockin_rate NUMBER(15,6),
  crsh_mtm_rate NUMBER(15,6),
  crsh_action_taken NUMBER(8),
  crsh_action_emailids VARCHAR2(1000 BYTE),
  crsh_limit_min NUMBER(15,2),
  crsh_limit_max NUMBER(15,2),
  crsh_nextlockin_rate NUMBER(15,6),
  crsh_nextlimit_min NUMBER(15,2),
  crsh_nextlimit_max NUMBER(15,2),
  crsh_adjusted_return NUMBER(15,6),
  crsh_adjusted_mtmrate NUMBER(15,6),
  crsh_budget_rate NUMBER(15,6),
  crsh_portfolio_rate NUMBER(15,6),
  crsh_tot_hedgerate NUMBER(15,6),
  crsh_reference_number VARCHAR2(30 BYTE),
  crsh_limit_percentage NUMBER(15,6)
);