CREATE TABLE "TEST_VSTSRedgate".trsystem991 (
  dp_deal_number VARCHAR2(25 BYTE),
  dp_ecr_date DATE,
  dp_buy_sell NUMBER(8),
  dp_swap_outright NUMBER(8),
  dp_deal_type NUMBER(8),
  dp_counter_party NUMBER(8),
  dp_base_currency NUMBER(8),
  dp_other_currency NUMBER(8),
  dp_ecr_rate NUMBER(15,6),
  dp_ecrlocal_rate NUMBER(15,6),
  dp_ecrbase_amount NUMBER(15,2),
  dp_ecrother_amount NUMBER(15,2),
  dp_ecramount_local NUMBER(15,2),
  dp_maturity_code NUMBER(8),
  dp_ermaturity_from DATE,
  dp_ermaturity_date DATE,
  dp_ermaturity_month NUMBER(2),
  dp_ecruser_id VARCHAR2(30 BYTE),
  dp_confirm_date DATE,
  dp_ecrexecute_time VARCHAR2(10 BYTE),
  dp_process_complete NUMBER(8),
  dp_complete_date DATE,
  dp_trade_reference VARCHAR2(25 BYTE),
  dp_cancel_type NUMBER(8),
  dp_crprofit_loss NUMBER(15,2),
  dp_crpl_voucher VARCHAR2(25 BYTE),
  dp_status VARCHAR2(25 BYTE),
  dp_status_no NUMBER,
  dp_delivered_status NUMBER(8)
);