CREATE TABLE "TEST_VSTSRedgate".trsystem999 (
  fldp_table_synonym VARCHAR2(30 BYTE) NOT NULL,
  fldp_column_name VARCHAR2(30 BYTE) NOT NULL,
  fldp_xml_field VARCHAR2(30 BYTE),
  fldp_column_id NUMBER(3),
  fldp_data_type VARCHAR2(15 BYTE),
  fldp_key_no NUMBER(1),
  fldp_show_yn NUMBER(8),
  fldp_display_yn NUMBER(8),
  fldp_pick_group NUMBER(3),
  fldp_add_action NUMBER(8),
  fldp_edit_action NUMBER(8),
  fldp_delete_action NUMBER(8),
  fldp_confirm_action NUMBER(8),
  fldp_process_yn NUMBER(8),
  fldp_text_case NUMBER(8),
  fldp_text_length VARCHAR2(4 BYTE),
  fldp_tooltip_text VARCHAR2(100 BYTE),
  fldp_default_value VARCHAR2(100 BYTE),
  fldp_date_range VARCHAR2(10 BYTE),
  fldp_description_type NUMBER(8),
  fldp_label_text VARCHAR2(50 BYTE),
  fldp_enable_disable NUMBER(8),
  fldp_column_displayname VARCHAR2(50 BYTE),
  fldp_required_yn CHAR,
  fldp_enable_disable_edit NUMBER(8),
  fldp_columns_forimage VARCHAR2(30 BYTE),
  fldp_mandatory_field NUMBER(8),
  fldp_tab_number NUMBER(1),
  fldp_field_sort NUMBER(3),
  fldp_cascade_from VARCHAR2(50 BYTE),
  fldp_cascade_type NUMBER(8),
  fldp_dropdown_selector NUMBER(8),
  fldp_dropdown_cursor NUMBER(4),
  fldp_bind_time VARCHAR2(100 BYTE),
  fldp_dropdown_relationkey NUMBER(8),
  fldp_holiday_check NUMBER(8),
  fldp_text_format_code NUMBER(8),
  fldp_create_date DATE,
  fldp_add_date DATE,
  fldp_record_status NUMBER(8),
  fldp_entry_details XMLTYPE
);