CREATE TABLE "TEST_VSTSRedgate".trsystem997_delearposition (
  depn_currency_code NUMBER(8),
  depn_other_currency NUMBER(8),
  depn_dealer_name VARCHAR2(50 BYTE),
  depn_base_amount NUMBER(15,2),
  depn_holding_rate NUMBER(15,6),
  depn_open_position NUMBER(15,2),
  depn_total_buy NUMBER(15,2),
  depn_total_sell NUMBER(15,2),
  depn_total_position NUMBER(15,2),
  depn_profitloss_ytd NUMBER(15,2),
  depn_mtmpandl_inr NUMBER(15,2),
  depn_instrument VARCHAR2(30 BYTE),
  depn_company_code NUMBER(8),
  depn_init_code NUMBER(8),
  depn_backup_deal NUMBER(8),
  depn_dtd NUMBER(15,2),
  depn_mtd NUMBER(15,2),
  depn_qtd NUMBER(15,2),
  depn_ytd NUMBER(15,2),
  depn_dealer_budget NUMBER(15,2),
  depn_postion_usd NUMBER(15,2),
  depn_position_rate NUMBER(15,6)
);