CREATE TABLE "TEST_VSTSRedgate".trsystem109 (
  cdel_company_code NUMBER(8) NOT NULL,
  cdel_deal_number VARCHAR2(25 BYTE) NOT NULL,
  cdel_deal_serial NUMBER(5) NOT NULL,
  cdel_reverse_serial NUMBER(5) NOT NULL,
  cdel_trade_reference VARCHAR2(25 BYTE),
  cdel_trade_serial NUMBER(5),
  cdel_cancel_date DATE NOT NULL,
  cdel_deal_type NUMBER(8),
  cdel_cancel_type NUMBER(8),
  cdel_cancel_amount NUMBER(15,2),
  cdel_cancel_rate NUMBER(15,6) NOT NULL,
  cdel_other_amount NUMBER(15,2),
  cdel_local_rate NUMBER(15,6),
  cdel_cancel_inr NUMBER(15,2) NOT NULL,
  cdel_holding_rate NUMBER(15,6),
  cdel_holding_rate1 NUMBER(15,6),
  cdel_dealer_holding NUMBER(15,6),
  cdel_dealer_holding1 NUMBER(15,6),
  cdel_profit_loss NUMBER(15,2),
  cdel_user_id VARCHAR2(50 BYTE),
  cdel_dealer_remark VARCHAR2(1024 BYTE),
  cdel_time_stamp VARCHAR2(25 BYTE),
  cdel_create_date DATE NOT NULL,
  cdel_entry_detail XMLTYPE,
  cdel_record_status NUMBER(8) NOT NULL,
  cdel_pl_voucher VARCHAR2(25 BYTE),
  cdel_delivery_from VARCHAR2(25 BYTE),
  cdel_delivery_serial NUMBER(5),
  cdel_forward_rate NUMBER(15,6),
  cdel_spot_rate NUMBER(15,6),
  cdel_margin_rate NUMBER(15,6),
  cdel_pandl_spot NUMBER(15,4),
  cdel_pandl_usd NUMBER(15,2),
  cdel_cancel_reason NUMBER(8),
  cdel_confirm_time VARCHAR2(10 BYTE),
  cdel_confirm_date DATE,
  cdel_bank_reference VARCHAR2(50 BYTE),
  cdel_bo_remark VARCHAR2(1024 BYTE),
  cdel_location_code NUMBER(8),
  cdel_int_outlay NUMBER(15,2),
  cdel_intoutlay_rate NUMBER(15,6),
  cdel_dealer_name VARCHAR2(50 BYTE),
  cdel_counter_dealer VARCHAR2(50 BYTE),
  cdel_edc_charge NUMBER(15,2),
  cdel_cashflow_date DATE,
  cdel_batch_number VARCHAR2(25 BYTE),
  workdate DATE,
  datestamp VARCHAR2(25 BYTE),
  imagetype VARCHAR2(10 BYTE),
  entity VARCHAR2(30 BYTE)
);