CREATE TABLE "TEST_VSTSRedgate".trsystem131 (
  mdel_company_code NUMBER(8) NOT NULL,
  mdel_deal_number VARCHAR2(25 BYTE) NOT NULL,
  mdel_user_reference VARCHAR2(25 BYTE),
  mdel_execute_date DATE NOT NULL,
  mdel_borrow_invest NUMBER(8) NOT NULL,
  mdel_transaction_type NUMBER(8) NOT NULL,
  mdel_account_head NUMBER(8) NOT NULL,
  mdel_counter_party NUMBER(8) NOT NULL,
  mdel_currency_code NUMBER(8) NOT NULL,
  mdel_local_bank NUMBER(8) NOT NULL,
  mdel_deal_amount NUMBER(15,2) NOT NULL,
  mdel_exchange_rate NUMBER(15,6) NOT NULL,
  mdel_amount_local NUMBER(15,2) NOT NULL,
  mdel_maturity_amount NUMBER(15,2),
  mdel_interest_type NUMBER(8) NOT NULL,
  mdel_base_rate NUMBER(15,6),
  mdel_interest_rate NUMBER(15,6),
  mdel_market_price NUMBER(15,6),
  mdel_repurchase_price NUMBER(15,6),
  mdel_period_type NUMBER(8) NOT NULL,
  mdel_period_number NUMBER(5) NOT NULL,
  mdel_due_date DATE NOT NULL,
  mdel_maturity_month NUMBER(2),
  mdel_user_id VARCHAR2(30 BYTE),
  mdel_dealer_remark VARCHAR2(1000 BYTE),
  mdel_bo_remark VARCHAR2(1000 BYTE),
  mdel_confirm_date DATE,
  mdel_execute_time VARCHAR2(10 BYTE),
  mdel_time_stamp VARCHAR2(25 BYTE),
  mdel_process_complete NUMBER(8) NOT NULL,
  mdel_complete_date DATE,
  mdel_create_date DATE NOT NULL,
  mdel_entry_detail XMLTYPE,
  mdel_record_status NUMBER(8) NOT NULL,
  workdate DATE,
  datestamp VARCHAR2(25 BYTE),
  imagetype VARCHAR2(10 BYTE),
  entity VARCHAR2(30 BYTE),
  mdel_total_charges NUMBER(15,2),
  mdel_brokerage_amount NUMBER(15,2),
  mdel_broker_code NUMBER(8),
  mdel_unit_price NUMBER(15,2),
  mdel_unit_quantity NUMBER(15,2),
  mdel_current_ac VARCHAR2(500 BYTE),
  mdel_value_date DATE,
  mdel_security_name VARCHAR2(500 BYTE),
  mdel_location_code NUMBER(8)
);