CREATE TABLE "TEST_VSTSRedgate".trsystem163 (
  tint_company_code NUMBER(8),
  tint_counter_party NUMBER(8),
  tint_currency_code NUMBER(8),
  tint_effective_date DATE,
  tint_period_upto NUMBER(5),
  tint_period_in NUMBER(8),
  tint_from_amount NUMBER(15,2),
  tint_to_amount NUMBER(15,2),
  tint_mat_date DATE,
  tint_record_status NUMBER(8),
  tint_user_remarks VARCHAR2(200 BYTE),
  tint_entry_detail XMLTYPE,
  tint_create_date DATE,
  tint_add_date DATE,
  tint_int_rate NUMBER(8,4),
  tint_negotiated_rate NUMBER(6,2),
  tint_serial_number NUMBER(8),
  tint_location_code NUMBER(8),
  tint_preclosure_rate NUMBER(6,2),
  imagetype VARCHAR2(10 BYTE),
  entity VARCHAR2(30 BYTE),
  datestamp VARCHAR2(25 BYTE),
  workdate DATE
);