CREATE TABLE "TEST_VSTSRedgate".trsystem975 (
  misr_company_code NUMBER(8),
  misr_location_code NUMBER(8),
  misr_counter_party NUMBER(8),
  misr_currency_code NUMBER(8),
  misr_for_currency NUMBER(8),
  misr_transaction_type NUMBER(8),
  misr_buy_sell NUMBER(8),
  misr_transaction_amount NUMBER(15,2),
  misr_oustsnding_amount NUMBER(15,2),
  misr_realised_amount NUMBER(15,2),
  misr_exchange_rate NUMBER(15,6),
  misr_effective_rate NUMBER(15,6),
  misr_interest_rate NUMBER(15,6),
  misr_ason_date DATE,
  misr_reference_date DATE,
  misr_maturity_date DATE,
  misr_reference_number VARCHAR2(25 BYTE),
  misr_bank_reference VARCHAR2(30 BYTE),
  misr_remrks VARCHAR2(30 BYTE),
  misr_actual_projected VARCHAR2(10 BYTE),
  misr_port_folio NUMBER(8),
  misr_subport_folio NUMBER(8),
  misr_expairy_quarter VARCHAR2(10 BYTE),
  misr_expairy_month VARCHAR2(10 BYTE),
  misr_month_order NUMBER(6),
  misr_spot_rate NUMBER(15,6),
  misr_forward_rate NUMBER(15,6),
  misr_margin_rate NUMBER(15,6),
  misr_deal_type NUMBER(8),
  misr_main_order NUMBER(5),
  misr_sub_order NUMBER(5),
  misr_description VARCHAR2(50 BYTE),
  misr_settlement_type NUMBER(8),
  misr_local_amount NUMBER(15,2)
);