CREATE TABLE "TEST_VSTSRedgate".trsystem017 (
  lrat_currency_code NUMBER(8) NOT NULL,
  lrat_for_currency NUMBER(8) NOT NULL,
  lrat_effective_date DATE NOT NULL,
  lrat_serial_number NUMBER(5) NOT NULL,
  lrat_rate_time VARCHAR2(10 BYTE),
  lrat_time_stamp VARCHAR2(25 BYTE),
  lrat_rate_description VARCHAR2(50 BYTE),
  lrat_spot_bid NUMBER(15,6),
  lrat_spot_ask NUMBER(15,6),
  lrat_month1_bid NUMBER(15,6),
  lrat_month1_ask NUMBER(15,6),
  lrat_month3_bid NUMBER(15,6),
  lrat_month3_ask NUMBER(15,6),
  lrat_month6_bid NUMBER(15,6),
  lrat_month6_ask NUMBER(15,6),
  lrat_year1_bid NUMBER(15,6),
  lrat_year1_ask NUMBER(15,6),
  lrat_year3_bid NUMBER(15,6),
  lrat_year3_ask NUMBER(15,6),
  lrat_year5_bid NUMBER(15,6),
  lrat_year5_ask NUMBER(15,6),
  lrat_year10_bid NUMBER(15,6),
  lrat_year10_ask NUMBER(15,6),
  lrat_create_date DATE,
  lrat_add_date DATE,
  lrat_entry_detail XMLTYPE,
  lrat_record_status NUMBER(8),
  lrat_usd_rate NUMBER(15,6),
  lrat_rbi_usd NUMBER(15,6),
  lrat_libor_1month NUMBER(15,6),
  lrat_libor_3month NUMBER(15,6),
  lrat_libor_6month NUMBER(15,6),
  lrat_libor_12month NUMBER(15,6),
  lrat_tokyo_rate NUMBER(15,6),
  lrat_lbmaam_rate NUMBER(15,4),
  lrat_lbmapm_rate NUMBER(15,4),
  lrat_int_type NUMBER(8),
  lrat_swaer_rate NUMBER(15,6),
  lrat_mer_rate NUMBER(15,6),
  CONSTRAINT trsystem017_pk PRIMARY KEY (lrat_currency_code,lrat_effective_date)
);