CREATE TABLE "TEST_VSTSRedgate".trsystem168 (
  trpy_company_code NUMBER(8) NOT NULL,
  trpy_location_code NUMBER(8) NOT NULL,
  trpy_loan_number VARCHAR2(25 BYTE) NOT NULL,
  trpy_loan_serial NUMBER(5) NOT NULL,
  trpy_repaid_date DATE NOT NULL,
  trpy_to_date DATE NOT NULL,
  trpy_debit_type NUMBER(8),
  trpy_transfer_code NUMBER(8),
  trpy_repaid_fcy NUMBER(15,4),
  trpy_conversion_rate NUMBER(15,4),
  trpy_repaid_inr NUMBER(15,2),
  trpy_spot_rate NUMBER(15,4),
  trpy_spot_inr NUMBER(15,2),
  trpy_voucher_number VARCHAR2(25 BYTE),
  trpy_total_charges NUMBER(15,2),
  trpy_loan_remarks VARCHAR2(200 BYTE),
  trpy_create_date DATE NOT NULL,
  trpy_entry_detail XMLTYPE,
  trpy_record_status NUMBER(8),
  imagetype VARCHAR2(10 BYTE),
  entity VARCHAR2(30 BYTE),
  datestamp VARCHAR2(25 BYTE),
  workdate DATE
);