CREATE TABLE "TEST_VSTSRedgate".trsystem997f (
  ripo_company_code NUMBER(8) NOT NULL,
  ripo_location_code NUMBER(8) NOT NULL,
  ripo_base_currency NUMBER(8) NOT NULL,
  ripo_other_currency NUMBER(8) NOT NULL,
  ripo_account_code NUMBER(8) NOT NULL,
  ripo_user_id VARCHAR2(50 BYTE),
  ripo_reference_number VARCHAR2(25 BYTE) NOT NULL,
  ripo_reference_serial NUMBER(5),
  ripo_reference_date DATE,
  ripo_dealer_id VARCHAR2(50 BYTE),
  ripo_counter_party NUMBER(8),
  ripo_transaction_amount NUMBER(15,6),
  ripo_fcy_rate NUMBER(15,6),
  ripo_usd_rate NUMBER(15,6),
  ripo_inr_value NUMBER(15,2),
  ripo_usd_value NUMBER(15,2),
  ripo_m2m_fcyrate NUMBER(15,6),
  ripo_m2m_localinrrate NUMBER(15,6),
  ripo_revalue_usd NUMBER(15,2),
  ripo_revalue_inr NUMBER(15,2),
  ripo_position_usd NUMBER(15,2),
  ripo_position_inr NUMBER(15,2),
  ripo_due_date DATE,
  ripo_maturity_month NUMBER(2),
  ripo_product_code NUMBER(8),
  ripo_asset_liability CHAR,
  ripo_for_currency NUMBER(8),
  ripo_subproduct_code NUMBER(8),
  ripo_mtm_pnl NUMBER(15,2),
  ripo_mtm_pnllocal NUMBER(15,2),
  ripo_hedge_trade NUMBER(8),
  ripo_buy_sell NUMBER(8),
  ripo_swap_outright NUMBER(8),
  ripo_deal_type NUMBER(8),
  ripo_currency_product NUMBER(8)
);