CREATE TABLE "TEST_VSTSRedgate".trsystem969 (
  load_data_name VARCHAR2(50 BYTE),
  load_data_file VARCHAR2(200 BYTE),
  load_file_path VARCHAR2(200 BYTE),
  load_backup_folder VARCHAR2(200 BYTE),
  load_file_format VARCHAR2(10 BYTE),
  load_download_from VARCHAR2(500 BYTE),
  load_run_program VARCHAR2(100 BYTE),
  load_staging_table VARCHAR2(50 BYTE),
  load_file_separator CHAR,
  load_zip_status NUMBER(8) NOT NULL,
  load_record_status NUMBER(8),
  load_serial_number NUMBER(8),
  load_sheet_range VARCHAR2(100 BYTE),
  load_comp_query VARCHAR2(100 BYTE),
  load_synonym_name VARCHAR2(100 BYTE),
  load_user_password VARCHAR2(50 BYTE),
  load_user_id VARCHAR2(50 BYTE),
  load_filename_column VARCHAR2(50 BYTE),
  load_filename_include VARCHAR2(50 BYTE),
  load_header_yn VARCHAR2(50 BYTE),
  load_staging_table_two VARCHAR2(50 BYTE),
  load_staging_table_archive VARCHAR2(50 BYTE),
  load_process_while_err NUMBER(8)
);