CREATE TABLE "TEST_VSTSRedgate".trsystem987 (
  repd_deal_number VARCHAR2(25 BYTE),
  repd_serial_number NUMBER(5),
  repd_company_code NUMBER(8),
  repd_execute_date DATE,
  repd_counter_party NUMBER(8),
  repd_base_amount NUMBER(15,2),
  repd_maturity_date DATE,
  repd_delivery_date DATE,
  repd_premium_amount NUMBER(15,2),
  repd_premium_local NUMBER(15,2),
  repd_user_reference VARCHAR2(200 BYTE),
  repd_buy_call NUMBER(15,4),
  repd_buy_put NUMBER(15,4),
  repd_sell_put NUMBER(15,4),
  repd_sell_call NUMBER(15,4),
  repd_expiry_date DATE,
  repe_reference_date DATE,
  repe_trade_reference VARCHAR2(25 BYTE),
  repe_hedged_fcy NUMBER(15,2),
  repe_buyer_seller NUMBER(8),
  repe_maturity_from DATE,
  repe_product_code NUMBER(8),
  repe_import_export NUMBER(8),
  repc_exercise_date DATE,
  repc_cancle_amount NUMBER(15,4),
  repc_rbi_refrate NUMBER(15,6),
  repc_profit_loss NUMBER(15,2),
  repc_row_number NUMBER(5),
  repc_sub_row NUMBER(5),
  repi_trade_reference VARCHAR2(25 BYTE),
  repi_hedged_fcy NUMBER(15,2),
  repi_buyer_seller NUMBER(8),
  repi_maturity_from DATE,
  repi_product_code NUMBER(8),
  repi_import_export NUMBER(8),
  repi_reference_date DATE,
  repi_order_exist NUMBER(5),
  repe_trade_fcy NUMBER(15,2),
  repi_trade_fcy NUMBER(15,2),
  repe_maturity_date DATE,
  repe_maturity_month DATE,
  repe_user_reference VARCHAR2(50 BYTE)
);