CREATE TABLE "TEST_VSTSRedgate".trsystem801 (
  status VARCHAR2(20 BYTE),
  comp_code VARCHAR2(4 BYTE),
  cont_po_no VARCHAR2(10 BYTE),
  entry_date VARCHAR2(8 BYTE),
  due_date VARCHAR2(8 BYTE),
  vendor VARCHAR2(10 BYTE),
  category_cd VARCHAR2(8 BYTE),
  sub_cat VARCHAR2(4 BYTE),
  currency VARCHAR2(5 BYTE),
  quantity VARCHAR2(20 BYTE),
  price VARCHAR2(15 BYTE),
  cont_val VARCHAR2(13 BYTE),
  pay_terms VARCHAR2(4 BYTE),
  bank VARCHAR2(15 BYTE),
  remarks VARCHAR2(8 BYTE),
  approval_date VARCHAR2(8 BYTE),
  transfer_date VARCHAR2(8 BYTE),
  tran_time_stamp VARCHAR2(8 BYTE)
);