CREATE TABLE "TEST_VSTSRedgate".trsystem107 (
  copt_company_code NUMBER(8) NOT NULL,
  copt_deal_number VARCHAR2(25 BYTE) NOT NULL,
  copt_serial_number NUMBER(5) NOT NULL,
  copt_multiple_deals NUMBER(8),
  copt_deal_type NUMBER(8) NOT NULL,
  copt_user_reference VARCHAR2(200 BYTE),
  copt_execute_date DATE NOT NULL,
  copt_exchange_code NUMBER(8) NOT NULL,
  copt_counter_party NUMBER(8) NOT NULL,
  copt_base_currency NUMBER(8) NOT NULL,
  copt_other_currency NUMBER(8) NOT NULL,
  copt_base_amount NUMBER(15,2) NOT NULL,
  copt_other_amount NUMBER(15,2),
  copt_contract_type NUMBER(8) NOT NULL,
  copt_hedge_trade NUMBER(8) NOT NULL,
  copt_option_style NUMBER(8) NOT NULL,
  copt_expiry_date DATE NOT NULL,
  copt_maturity_date DATE NOT NULL,
  copt_spread_yn NUMBER(8) NOT NULL,
  copt_spread_deal VARCHAR2(25 BYTE),
  copt_cancel_deal VARCHAR2(25 BYTE),
  copt_refrate_code NUMBER(8),
  copt_user_id VARCHAR2(30 BYTE) NOT NULL,
  copt_dealer_remark VARCHAR2(1000 BYTE),
  copt_bo_remark VARCHAR2(1000 BYTE),
  copt_product_code NUMBER(8) NOT NULL,
  copt_broker_code NUMBER(8),
  copt_local_bank NUMBER(8) NOT NULL,
  copt_lot_numbers NUMBER(15) NOT NULL,
  copt_lot_quantity NUMBER(15,2) NOT NULL,
  copt_lot_price NUMBER(15,4) NOT NULL,
  copt_margin_rate NUMBER(15,4) NOT NULL,
  copt_margin_amount NUMBER(15,2) NOT NULL,
  copt_brokerage_rate NUMBER(15,4) NOT NULL,
  copt_brokerage_amount NUMBER(15,2) NOT NULL,
  copt_service_tax NUMBER(15,2),
  copt_transaction_cost NUMBER(15,2),
  copt_other_charges NUMBER(15,2),
  copt_delivery_yn NUMBER(8) NOT NULL,
  copt_delivery_date DATE,
  copt_delivery_qty NUMBER(7),
  copt_delivery_uom NUMBER(8),
  copt_deal_status NUMBER(8),
  copt_receipt_number VARCHAR2(25 BYTE),
  copt_receipt_date DATE,
  copt_warehouse_code NUMBER(8),
  copt_delivery_type NUMBER(8),
  copt_noof_deliveries NUMBER(5),
  copt_premium_rate NUMBER(15,6),
  copt_premium_amount NUMBER(15,2),
  copt_premium_exrate NUMBER(15,6),
  copt_premium_local NUMBER(15,2),
  copt_premium_valuedate DATE,
  copt_pl_voucher VARCHAR2(25 BYTE),
  copt_execute_time VARCHAR2(10 BYTE) NOT NULL,
  copt_time_stamp VARCHAR2(25 BYTE) NOT NULL,
  copt_confirm_date DATE,
  copt_process_complete NUMBER(8) NOT NULL,
  copt_complete_date DATE,
  copt_create_date DATE NOT NULL,
  copt_add_date DATE NOT NULL,
  copt_entry_detail XMLTYPE,
  copt_record_status NUMBER(8) NOT NULL,
  copt_backup_deal NUMBER(8),
  copt_premium_status NUMBER(8),
  copt_init_code NUMBER(8),
  copt_stop_loss NUMBER(15,6),
  copt_take_profit NUMBER(15,6),
  copt_cancel_reason NUMBER(8),
  copt_bank_reference VARCHAR2(50 BYTE),
  copt_confirm_time VARCHAR2(10 BYTE),
  copt_analysis_option NUMBER(8),
  copt_analysis_type NUMBER(8),
  copt_analysis_frequency NUMBER(8),
  copt_analysis_selection NUMBER(8),
  copt_location_code NUMBER(8),
  copt_tenor NUMBER(4),
  copt_deliverystart_date DATE,
  copt_dealer_name VARCHAR2(50 BYTE),
  copt_counter_dealer VARCHAR2(50 BYTE),
  workdate DATE,
  datestamp VARCHAR2(25 BYTE),
  imagetype VARCHAR2(10 BYTE),
  entity VARCHAR2(30 BYTE),
  sc NUMBER(15,6),
  sp NUMBER(15,6),
  bc NUMBER(15,6),
  bp NUMBER(15,6)
);