CREATE TABLE "TEST_VSTSRedgate".trsystem021 (
  splc_company_code NUMBER(8) NOT NULL,
  splc_policy_group NUMBER(8) NOT NULL,
  splc_serial_number NUMBER(5) NOT NULL,
  splc_userid_type NUMBER(8) NOT NULL,
  splc_userid_minimum NUMBER(2) NOT NULL,
  splc_userid_maximum NUMBER(2) NOT NULL,
  splc_userid_content NUMBER(8) NOT NULL,
  splc_access_terminal NUMBER(8) NOT NULL,
  splc_access_time NUMBER(8) NOT NULL,
  splc_access_timefrom VARCHAR2(5 BYTE),
  splc_access_timeto VARCHAR2(5 BYTE),
  splc_access_dayyn NUMBER(8) NOT NULL,
  splc_access_days VARCHAR2(15 BYTE),
  splc_access_weeklyoff NUMBER(8) NOT NULL,
  splc_access_holiday NUMBER(8) NOT NULL,
  splc_suspend_type NUMBER(8) NOT NULL,
  splc_suspend_self NUMBER(8) NOT NULL,
  splc_login_logoffperiod NUMBER(2) NOT NULL,
  splc_login_attempts NUMBER(2) NOT NULL,
  splc_login_timedelay NUMBER(2) NOT NULL,
  splc_login_allowtime NUMBER(2),
  splc_password_type NUMBER(8) NOT NULL,
  splc_password_change NUMBER(8) NOT NULL,
  splc_password_frequency NUMBER(8) NOT NULL,
  splc_password_minimum NUMBER(2) NOT NULL,
  splc_password_maximum NUMBER(2) NOT NULL,
  splc_password_content NUMBER(8) NOT NULL,
  splc_password_alpha NUMBER(2),
  splc_password_numeric NUMBER(2),
  splc_password_others NUMBER(2),
  splc_password_dictionary NUMBER(8) NOT NULL,
  splc_password_reuse NUMBER(2),
  splc_create_date DATE NOT NULL,
  splc_add_date DATE NOT NULL,
  splc_entry_detail XMLTYPE,
  splc_record_status NUMBER(8) NOT NULL,
  CONSTRAINT pk_trsystem021 PRIMARY KEY (splc_company_code,splc_policy_group,splc_serial_number)
);