CREATE TABLE "TEST_VSTSRedgate".trsystem102c (
  conr_trade_reference VARCHAR2(25 BYTE) NOT NULL,
  conr_buyer_seller NUMBER(8),
  conr_total_quantity NUMBER(15,2),
  conr_product_rate VARCHAR2(25 BYTE),
  conr_base_amount NUMBER(15,2),
  conr_base_currency NUMBER(8),
  conr_payment_terms NUMBER(8),
  conr_local_bank NUMBER(8),
  conr_add_date DATE,
  conr_create_date DATE,
  conr_record_status NUMBER(8),
  conr_reference_date DATE,
  conr_user_reference VARCHAR2(25 BYTE),
  conr_company_code NUMBER(8),
  conr_product_category NUMBER(8),
  conr_sub_category NUMBER(8),
  conr_end_date DATE,
  imagetype VARCHAR2(10 BYTE),
  entity VARCHAR2(30 BYTE),
  datestamp VARCHAR2(25 BYTE),
  workdate DATE,
  conr_execute_date DATE,
  conr_cont_remarks VARCHAR2(200 BYTE),
  conr_account_code NUMBER(8)
);