CREATE TABLE "TEST_VSTSRedgate".trsystem977 (
  openamount NUMBER(15,2),
  hedgeamount NUMBER(15,2),
  invoiceamount NUMBER(15,2),
  forwardrate NUMBER(15,2),
  invoicerate NUMBER(15,6),
  spotbooking NUMBER(15,6),
  spotrate NUMBER(15,6),
  tradecurrency NUMBER(8),
  oppgainloss NUMBER(15,6),
  acutalpl NUMBER(15,6),
  notionalpl NUMBER(15,6),
  mtmpl NUMBER(15,6),
  companycode NUMBER(8),
  localbank NUMBER(8),
  importexport NUMBER(8),
  referenceno VARCHAR2(25 BYTE),
  matdate DATE,
  execdate DATE,
  hedgsale NUMBER(8),
  rec_no NUMBER(2),
  slno NUMBER(2),
  open_balance NUMBER(15,6)
);