CREATE TABLE "TEST_VSTSRedgate".trsystem106 (
  cfrv_company_code NUMBER(8) NOT NULL,
  cfrv_deal_number VARCHAR2(25 BYTE) NOT NULL,
  cfrv_reverse_deal VARCHAR2(25 BYTE) NOT NULL,
  cfrv_reverse_lot NUMBER(5) NOT NULL,
  cfrv_create_date DATE,
  cfrv_record_status NUMBER(8),
  cfrv_profit_loss NUMBER(15,2),
  cfrv_pl_voucher VARCHAR2(25 BYTE),
  cfrv_execute_date DATE,
  cfrv_serial_number NUMBER(5),
  cfrv_reverse_serial NUMBER(5),
  cfrv_lot_price NUMBER(15,6),
  cfrv_dealer_remarks VARCHAR2(100 BYTE),
  cfrv_cancel_reason NUMBER(8),
  cfrv_cancel_amount NUMBER(15,2),
  cfrv_confirm_date DATE,
  cfrv_confirm_time VARCHAR2(10 BYTE),
  cfrv_bank_reference VARCHAR2(50 BYTE),
  cfrv_bo_remark VARCHAR2(1024 BYTE),
  cfrv_entry_detail XMLTYPE,
  cfrv_spot_rate NUMBER(15,4),
  cfrv_forward_rate NUMBER(15,4),
  cfrv_bank_margin NUMBER(15,4),
  cfrv_dealer_name VARCHAR2(50 BYTE),
  cfrv_counter_dealer VARCHAR2(50 BYTE),
  cfrv_exchange_rate NUMBER(15,6),
  cfrv_user_id VARCHAR2(25 BYTE),
  workdate DATE,
  datestamp VARCHAR2(25 BYTE),
  imagetype VARCHAR2(10 BYTE),
  entity VARCHAR2(30 BYTE),
  cfrv_reference_number VARCHAR2(25 BYTE)
);