CREATE TABLE "TEST_VSTSRedgate".trsystem996 (
  crsk_ason_date DATE NOT NULL,
  crsk_risk_type NUMBER(8),
  crsk_deal_number VARCHAR2(25 BYTE),
  crsk_serial_number NUMBER(5),
  crsk_deal_date DATE,
  crsk_buy_sell NUMBER(8),
  crsk_currency_code NUMBER(8),
  crsk_counter_party NUMBER(8),
  crsk_deal_rate NUMBER(15,6),
  crsk_maturity_date DATE,
  crsk_user_id VARCHAR2(50 BYTE),
  crsk_maturity_month NUMBER(2),
  crsk_position_fcy NUMBER(15,2),
  crsk_inr_amount NUMBER(15,2),
  crsk_rate_usd NUMBER(15,6),
  crsk_position_usd NUMBER(15,2),
  crsk_rate_inr NUMBER(15,6),
  crsk_position_inr NUMBER(15,2),
  crsk_allowed_usd NUMBER(15,2),
  crsk_allowed_inr NUMBER(15,2),
  crsk_limit_usd NUMBER(15,2),
  crsk_limit_inr NUMBER(15,2),
  crsk_violation_usd NUMBER(15,2),
  crsk_violation_inr NUMBER(15,2),
  crsk_risk_reference VARCHAR2(15 BYTE),
  crsk_other_currency NUMBER(15,2),
  crsk_mtm_rate NUMBER(15,6),
  crsk_mtm_currency NUMBER(15,2),
  crsk_for_currency NUMBER(8),
  crsk_wash_rate NUMBER(15,6),
  crsk_profit_loss NUMBER(15,2),
  crsk_account_code NUMBER(8),
  crsk_location_code NUMBER(8),
  crsk_portfolio_code NUMBER(8),
  crsk_subportfolio_code NUMBER(8),
  crsk_company_code NUMBER(8),
  crsk_lockin_rate NUMBER(15,6),
  crsk_downside_lock NUMBER(15,6),
  crsk_hedged_percentage NUMBER(15,2),
  crsk_hedge_rate NUMBER(15,6),
  crsk_mtm_rateactual NUMBER(15,6),
  crsk_mtm_actual NUMBER(15,2),
  crsk_mtm_local NUMBER(15,2),
  crsk_mtm_washrate NUMBER(15,6),
  crsk_stoploss_rate NUMBER(15,6),
  crsk_takeprofit_rate NUMBER(15,6)
);