CREATE TABLE "TEST_VSTSRedgate".trsystem011 (
  rprm_company_code NUMBER(8) NOT NULL,
  rprm_risk_type NUMBER(8) NOT NULL,
  rprm_effective_date DATE NOT NULL,
  rprm_hedge_trade NUMBER(8) NOT NULL,
  rprm_buy_sell NUMBER(8) NOT NULL,
  rprm_swap_outright NUMBER(8) NOT NULL,
  rprm_deal_type NUMBER(8) NOT NULL,
  rprm_counter_party NUMBER(8) NOT NULL,
  rprm_currency_code NUMBER(8) NOT NULL,
  rprm_dealer_id NUMBER(8) NOT NULL,
  rprm_cross_currency NUMBER(8) NOT NULL,
  rprm_gross_net NUMBER(8) NOT NULL,
  rprm_rate_type NUMBER(8) NOT NULL,
  rprm_fluct_allowed NUMBER(8) NOT NULL,
  rprm_fluct_ceo NUMBER(8) NOT NULL,
  rprm_create_date DATE NOT NULL,
  rprm_add_date DATE NOT NULL,
  rprm_entry_detail XMLTYPE,
  rprm_record_status NUMBER(8) NOT NULL,
  rprm_product_code NUMBER(8),
  rprm_subproduct_code NUMBER(8),
  rprm_location_code NUMBER(8),
  rprm_module_code NUMBER(8),
  rprm_amc_code NUMBER(8),
  rprm_scheme_code NUMBER(8),
  rprm_investment_code NUMBER(8),
  rprm_plan_code NUMBER(8),
  rprm_option_code NUMBER(8),
  rprm_broker_code NUMBER(8),
  rprm_scheme_category NUMBER(8),
  rprm_limit_in_usd NUMBER(8),
  rprm_limit_in_local NUMBER(8),
  rprm_limit_in_percent NUMBER(8),
  rprm_limit_infcy NUMBER(8),
  rprm_currency_product NUMBER(8),
  CONSTRAINT pk_trsystem011 PRIMARY KEY (rprm_company_code,rprm_risk_type,rprm_effective_date)
);