CREATE TABLE "TEST_VSTSRedgate".trsystem989 (
  companycode NUMBER(8) NOT NULL,
  tradreferenceno VARCHAR2(25 BYTE),
  dealno VARCHAR2(25 BYTE) NOT NULL,
  hdguserref VARCHAR2(25 BYTE),
  companydesc VARCHAR2(50 BYTE),
  basecrncy VARCHAR2(50 BYTE),
  othercrncy VARCHAR2(50 BYTE),
  counterprty VARCHAR2(50 BYTE),
  buysell VARCHAR2(50 BYTE),
  swapoutright VARCHAR2(50 BYTE),
  fcy NUMBER(15,2),
  exchangerate NUMBER(15,6),
  executeddate DATE,
  userid VARCHAR2(50 BYTE),
  hedgelclamt NUMBER(15,2),
  localrate NUMBER(15,6),
  baseamt NUMBER(15,2),
  maturitydate DATE,
  maturityfrom DATE,
  otheramount NUMBER(15,2),
  ttradecrncy VARCHAR2(20 BYTE),
  timportexport VARCHAR2(50 BYTE),
  tlocalbank VARCHAR2(50 BYTE),
  ttradereference VARCHAR2(100 BYTE),
  ttradfcy NUMBER(15,2),
  ttradeinr NUMBER(15,2),
  ttraderate NUMBER(15,6),
  tproductdescription VARCHAR2(50 BYTE),
  tuserreference VARCHAR2(100 BYTE),
  ttradematurity DATE,
  ttradematurityfrm DATE,
  dealbankrefe VARCHAR2(50 BYTE),
  ttradedate DATE,
  deal_buy_sell NUMBER(8),
  deal_execute_date DATE,
  deal_counter_party NUMBER(8)
);