CREATE TABLE "TEST_VSTSRedgate".trsystem979 (
  companycode NUMBER(8),
  openhedgedfcy_cost NUMBER(15,2),
  openunhedgedfcy_cost NUMBER(15,2),
  openhedgedinr_cost NUMBER(15,2),
  openunhedgedinr_cost NUMBER(15,2),
  openhedgedinr_effect NUMBER(15,2),
  openunhedgedinr_effect NUMBER(15,2),
  fccancellation NUMBER(15,2),
  openhedgedmtm NUMBER(15,2),
  futuremtm NUMBER(15,2),
  optionmtm NUMBER(15,2),
  frwdcontractfcy NUMBER(15,2),
  ftrcontractfcy NUMBER(15,2),
  frwdcontractinr NUMBER(15,2),
  ftrcontractinr NUMBER(15,2),
  refdate DATE,
  fcdeliveryfcy NUMBER(15,2),
  fcdeliverycostinr NUMBER(15,2),
  fcdeliveryeffectinr NUMBER(15,2),
  cashsettlefcy NUMBER(15,2),
  cassettlecostinr NUMBER(15,2),
  cassettleeffectinr NUMBER(15,2),
  ordercancelfcy NUMBER(15,2),
  orderbooklinr NUMBER(15,2),
  ordercancelinr NUMBER(15,2)
);