CREATE TABLE "TEST_VSTSRedgate".trsystem012 (
  risk_company_code NUMBER(8),
  risk_risk_reference VARCHAR2(15 BYTE) NOT NULL,
  risk_effective_date DATE NOT NULL,
  risk_risk_type NUMBER(8) NOT NULL,
  risk_hedge_trade NUMBER(8) NOT NULL,
  risk_buy_sell NUMBER(8) NOT NULL,
  risk_swap_outright NUMBER(8) NOT NULL,
  risk_deal_type NUMBER(8) NOT NULL,
  risk_counter_party NUMBER(8) NOT NULL,
  risk_currency_code NUMBER(8) NOT NULL,
  risk_dealer_id VARCHAR2(50 BYTE) NOT NULL,
  risk_cross_currency NUMBER(8) NOT NULL,
  risk_limit_usd NUMBER(15,2),
  risk_limit_local NUMBER(15,2),
  risk_limit_percent NUMBER(15,2),
  risk_action_taken NUMBER(8),
  risk_stake_holder VARCHAR2(500 BYTE),
  risk_fluct_allowed NUMBER(15,2),
  risk_fluct_ceo NUMBER(15,2),
  risk_noof_days NUMBER(3),
  risk_create_date DATE NOT NULL,
  risk_add_date DATE NOT NULL,
  risk_entry_detail XMLTYPE,
  risk_record_status NUMBER(8) NOT NULL,
  risk_product_code NUMBER(8),
  risk_subproduct_code NUMBER(8),
  risk_location_code NUMBER(8),
  risk_module_code NUMBER(8),
  risk_amc_code NUMBER(8),
  risk_scheme_code NUMBER(8),
  risk_investment_code NUMBER(8),
  risk_plan_code NUMBER(8),
  risk_option_code NUMBER(8),
  risk_broker_code NUMBER(8),
  risk_scheme_category NUMBER(8),
  risk_limit_fcy NUMBER(15,2),
  risk_gap_frequency NUMBER(8),
  risk_currency_product NUMBER(8),
  risk_lockin_bentchmark NUMBER(8),
  risk_lockin_ratetype NUMBER(8),
  risk_lockinrate NUMBER(15,6),
  CONSTRAINT pk_trsystem012 PRIMARY KEY (risk_risk_reference,risk_effective_date)
);