CREATE TABLE "TEST_VSTSRedgate".trtemp047b (
  intc_company_code NUMBER(8),
  intc_counter_party NUMBER(8),
  intc_currency_code NUMBER(8),
  intc_location_code NUMBER(8),
  intc_scheme_code NUMBER(8),
  intc_fd_number VARCHAR2(25 BYTE),
  intc_fd_srnumber NUMBER(4),
  intc_charging_date DATE,
  intc_open_date DATE,
  intc_principal_amt NUMBER(15,2),
  intc_intcharge_amount NUMBER(15,2),
  intc_tds_deducted_amt NUMBER(15,2),
  intc_tds_sercharge_amt NUMBER(15,2),
  intc_intcr_account VARCHAR2(25 BYTE),
  intc_charging_type NUMBER(8),
  intc_credit_to NUMBER(8),
  intc_charge_upto DATE,
  intc_create_date DATE,
  intc_add_date DATE,
  intc_record_status NUMBER(8),
  intc_nextcharge_date DATE,
  intc_entry_detail XMLTYPE,
  intc_tds_crac VARCHAR2(30 BYTE),
  intc_tds_surchargecrac VARCHAR2(30 BYTE)
);