CREATE TABLE "TEST_VSTSRedgate".trtest001 (
  dealnumber VARCHAR2(50 BYTE),
  underlying VARCHAR2(50 BYTE),
  dealdate VARCHAR2(50 BYTE),
  contractno VARCHAR2(50 BYTE),
  "CATEGORY" VARCHAR2(50 BYTE),
  bank VARCHAR2(50 BYTE),
  forwardcover VARCHAR2(50 BYTE),
  spot VARCHAR2(50 BYTE),
  prem VARCHAR2(50 BYTE),
  margin VARCHAR2(50 BYTE),
  netrate VARCHAR2(50 BYTE),
  dealmaturitydate VARCHAR2(50 BYTE),
  utilised VARCHAR2(50 BYTE),
  cancelled VARCHAR2(50 BYTE),
  balance VARCHAR2(50 BYTE),
  cancellationdate VARCHAR2(50 BYTE),
  cancellationrate VARCHAR2(50 BYTE),
  gainloss VARCHAR2(50 BYTE),
  optionpremiuminusd VARCHAR2(50 BYTE),
  optionpremiumininr VARCHAR2(50 BYTE),
  weightedavg VARCHAR2(50 BYTE),
  companycode NUMBER(8),
  bankcode NUMBER(8),
  categorycode NUMBER(8),
  initcode NUMBER(8),
  currencycode NUMBER(8)
);