CREATE TABLE "TEST_VSTSRedgate".trtran032 (
  bpur_company_code NUMBER(8),
  bpur_location_code NUMBER(8),
  bpur_deal_number VARCHAR2(25 BYTE) NOT NULL,
  bpur_deal_type NUMBER(8),
  bpur_scheme_code NUMBER(8),
  bpur_isin_number VARCHAR2(25 BYTE),
  bpur_transaction_type NUMBER(8),
  bpur_execute_date DATE,
  bpur_execute_time VARCHAR2(10 BYTE),
  bpur_value_date DATE,
  bpur_counter_party NUMBER(8),
  bpur_currency_code NUMBER(8),
  bpur_maturity_date DATE,
  bpur_period_year NUMBER(3),
  bpur_period_month NUMBER(3),
  bpur_period_days NUMBER(3),
  bpur_coupon_rate NUMBER(15,4),
  bpur_current_yield NUMBER(15,4),
  bpur_yieldat_maturity NUMBER(15,4),
  bpur_market_price NUMBER(15,4),
  bpur_face_value NUMBER(15,4),
  bpur_unit_price NUMBER(15,4),
  bpur_unit_quantity NUMBER(15,2),
  bpur_deal_amount NUMBER(15,2),
  bpur_maturity_amount NUMBER(15,2),
  bpur_interest_amount NUMBER(15,2),
  bpur_exchange_rate NUMBER(15,6),
  bpur_amount_local NUMBER(15,2),
  bpur_broker_code NUMBER(8),
  bpur_brokerage_amount NUMBER(15,2),
  bpur_dp_id NUMBER(8),
  bpur_payment_through NUMBER(8),
  bpur_cheque_number VARCHAR2(15 BYTE),
  bpur_dplinked_bank NUMBER(8),
  bpur_dplinked_ac VARCHAR2(25 BYTE),
  bpur_settlement_security NUMBER(8),
  bpur_dealer_remark VARCHAR2(1000 BYTE),
  bpur_bo_remark VARCHAR2(1000 BYTE),
  bpur_process_complete NUMBER(8),
  bpur_complete_date DATE,
  bpur_create_date DATE,
  bpur_entry_detail XMLTYPE,
  bpur_record_status NUMBER(8),
  bpur_bank_reference VARCHAR2(25 BYTE),
  CONSTRAINT trtran032_pk PRIMARY KEY (bpur_deal_number)
);