CREATE TABLE "TEST_VSTSRedgate".trtran002c (
  conr_trade_reference VARCHAR2(25 BYTE),
  conr_buyer_seller NUMBER(8),
  conr_total_quantity NUMBER(15,2),
  conr_product_rate VARCHAR2(25 BYTE),
  conr_base_amount NUMBER(15,2),
  conr_base_currency NUMBER(8),
  conr_payment_terms NUMBER(8),
  conr_local_bank NUMBER(8),
  conr_month1_qty NUMBER(15,2),
  conr_month1_amount NUMBER(15,2),
  conr_month2_qty NUMBER(15,2),
  conr_month2_amount NUMBER(15,2),
  conr_month3_qty NUMBER(15,2),
  conr_month3_amount NUMBER(15,2),
  conr_month4_qty NUMBER(15,2),
  conr_month4_amount NUMBER(15,2),
  conr_month5_qty NUMBER(15,2),
  conr_month5_amount NUMBER(15,2),
  conr_month6_qty NUMBER(15,2),
  conr_month6_amount NUMBER(15,2),
  conr_month7_qty NUMBER(15,2),
  conr_month7_amount NUMBER(15,2),
  conr_month8_qty NUMBER(15,2),
  conr_month8_amount NUMBER(15,2),
  conr_month9_qty NUMBER(15,2),
  conr_month9_amount NUMBER(15,2),
  conr_month10_qty NUMBER(15,2),
  conr_month10_amount NUMBER(15,2),
  conr_month11_qty NUMBER(15,2),
  conr_month11_amount NUMBER(15,2),
  conr_month12_qty NUMBER(15,2),
  conr_month12_amount NUMBER(15,2),
  conr_add_date DATE,
  conr_create_date DATE,
  conr_record_status VARCHAR2(20 BYTE),
  conr_reference_date DATE,
  conr_user_reference VARCHAR2(25 BYTE),
  conr_company_code NUMBER(8),
  conr_product_category NUMBER(8),
  conr_sub_category NUMBER(8),
  conr_end_date DATE,
  conr_execute_date DATE,
  conr_cont_remarks VARCHAR2(200 BYTE),
  conr_account_code NUMBER(8)
);