CREATE TABLE "TEST_VSTSRedgate".trtran002e_stagingtable_c (
  referencedate DATE,
  company VARCHAR2(50 BYTE),
  a_c VARCHAR2(10 BYTE),
  banker VARCHAR2(100 BYTE),
  place VARCHAR2(100 BYTE),
  due_date VARCHAR2(10 BYTE),
  "M" CHAR,
  lc_no VARCHAR2(50 BYTE),
  lc_dt VARCHAR2(10 BYTE),
  qty VARCHAR2(20 BYTE),
  rate VARCHAR2(50 BYTE),
  intamt VARCHAR2(20 BYTE),
  conchrg VARCHAR2(20 BYTE),
  amount_us VARCHAR2(50 BYTE),
  amount_rs VARCHAR2(50 BYTE),
  paymentconfirmed VARCHAR2(1 BYTE),
  vessel_name VARCHAR2(50 BYTE),
  port VARCHAR2(50 BYTE),
  app VARCHAR2(10 BYTE),
  beneficiary VARCHAR2(100 BYTE),
  usance VARCHAR2(100 BYTE),
  bl_date VARCHAR2(50 BYTE),
  c_type VARCHAR2(100 BYTE),
  contract_no VARCHAR2(100 BYTE),
  contract_date VARCHAR2(20 BYTE),
  remark VARCHAR2(100 BYTE),
  company_c NUMBER(8),
  banker_c NUMBER(8),
  due_date_c DATE,
  qty_c NUMBER(15,2),
  rate_c NUMBER(15,4),
  intamt_c NUMBER(15,4),
  conchrg_c NUMBER(15,2),
  amount_us_c NUMBER(15,2),
  amount_rs_c NUMBER(15,2),
  lc_dt_c DATE,
  contract_date_c DATE,
  bl_date_c DATE,
  app_serialno NUMBER(5)
);