CREATE TABLE "TEST_VSTSRedgate".trtran103a (
  dealing_system VARCHAR2(20 BYTE),
  message_type VARCHAR2(50 BYTE),
  deal_type VARCHAR2(50 BYTE),
  side_buy_sell NUMBER(8),
  product VARCHAR2(50 BYTE),
  status VARCHAR2(50 BYTE),
  revision_version NUMBER(5),
  trade_id NUMBER(20) NOT NULL,
  trader_id NUMBER(20),
  trader_name VARCHAR2(50 BYTE),
  counterparty_id NUMBER(20),
  counterparty_trader_name VARCHAR2(50 BYTE),
  date_of_deal DATE,
  time_of_deal VARCHAR2(10 BYTE),
  trade_date DATE,
  date_confirmed DATE,
  time_confirmed VARCHAR2(10 BYTE),
  counterparty_dealing_code VARCHAR2(50 BYTE),
  counterparty_name VARCHAR2(100 BYTE),
  currency_1 NUMBER(8),
  currency_2 NUMBER(8),
  amount_dealt NUMBER(15,2),
  counter_amount NUMBER(15,2),
  spot_basis_rate NUMBER(15,6),
  exchange_rate_period_1 NUMBER(15,6),
  value_date_period_1 DATE,
  tenor_period_1 VARCHAR2(20 BYTE),
  fixing_date_period_1 VARCHAR2(20 BYTE),
  value_date_period2 VARCHAR2(20 BYTE),
  tenor_period_2 VARCHAR2(20 BYTE),
  fixing_date_period_2 VARCHAR2(20 BYTE),
  split_valuedate_currency_1 VARCHAR2(20 BYTE),
  split_valuedate_currency2 VARCHAR2(20 BYTE),
  reference_spotrate NUMBER(15,6),
  reference_rate_period1 NUMBER(15,6),
  delivery_date NUMBER(15),
  banknote_ratetype NUMBER(15),
  execution_venue NUMBER(15),
  trademethod NUMBER(15),
  filename VARCHAR2(50 BYTE) NOT NULL,
  recordstatus NUMBER(8),
  business_unit NUMBER(8),
  profit_center NUMBER(8),
  forward_rate NUMBER(15,6),
  margin NUMBER(15,6),
  classification_code NUMBER(8),
  entrydate DATE,
  referencenumber VARCHAR2(500 BYTE),
  dealcreateddate DATE DEFAULT sysdate,
  dealnumber VARCHAR2(25 BYTE),
  counterpartycode NUMBER(8),
  othercurrencycode NUMBER(8),
  basecurrencycode NUMBER(8),
  buysellcode NUMBER(8),
  bank_code1 VARCHAR2(100 BYTE),
  bankdealername VARCHAR2(100 BYTE),
  bankcodedealername VARCHAR2(100 BYTE),
  bankcode1 VARCHAR2(100 BYTE),
  baseamount NUMBER(15,2),
  cancelamount NUMBER(15,2),
  CONSTRAINT trtran103a_pk PRIMARY KEY (trade_id,filename)
);