CREATE TABLE "TEST_VSTSRedgate".trtran002f (
  ishm_company_code NUMBER(8) NOT NULL,
  ishm_trade_reference VARCHAR2(25 BYTE) NOT NULL,
  ishm_import_export NUMBER(8) NOT NULL,
  ishm_entry_date DATE NOT NULL,
  ishm_user_reference VARCHAR2(1000 BYTE),
  ishm_invoice_number VARCHAR2(25 BYTE),
  ishm_reference_date DATE,
  ishm_product_code NUMBER(8),
  ishm_product_description VARCHAR2(200 BYTE),
  ishm_trade_fcy NUMBER(15,2) NOT NULL,
  ishm_trade_rate NUMBER(15,6) NOT NULL,
  ishm_trade_inr NUMBER(15,2) NOT NULL,
  ishm_period_code NUMBER(8),
  ishm_trade_period NUMBER(5),
  ishm_maturity_date DATE,
  ishm_create_date DATE NOT NULL,
  ishm_entry_detail XMLTYPE,
  ishm_record_status NUMBER(8) NOT NULL,
  ishm_contract_no VARCHAR2(50 BYTE),
  ishm_product_quantity NUMBER(15,3),
  ishm_product_rate NUMBER(15,4),
  CONSTRAINT pk_trtran002f PRIMARY KEY (ishm_company_code,ishm_trade_reference)
);