CREATE TABLE "TEST_VSTSRedgate".trtran093c (
  iroe_deal_number VARCHAR2(25 BYTE) NOT NULL,
  iroe_serial_number NUMBER(5) NOT NULL,
  iroe_subserial_number NUMBER(5) NOT NULL,
  iroe_reverse_serial NUMBER(5),
  iroe_exercise_date DATE,
  iroe_exercise_type NUMBER(8),
  iroe_settlement_date DATE,
  iroe_base_amount NUMBER(15,4) NOT NULL,
  iroe_base_rate NUMBER(15,6),
  iroe_spread_rate NUMBER(15,6),
  iroe_final_rate NUMBER(15,6),
  iroe_wash_rate NUMBER(15,6),
  iroe_profit_loss NUMBER(15,2),
  iroe_trade_reference VARCHAR2(25 BYTE),
  iroe_premium_rate NUMBER(15,6),
  iroe_premium_amount NUMBER(15,2),
  iroe_premium_exrate NUMBER(15,6),
  iroe_premium_local NUMBER(15,2),
  iroe_create_date DATE,
  iroe_add_date DATE,
  iroe_record_status NUMBER(8),
  iroe_premium_status NUMBER(8),
  iroe_confirm_date DATE,
  iroe_confirm_time VARCHAR2(10 BYTE),
  iroe_bank_reference VARCHAR2(50 BYTE),
  iroe_bo_remark VARCHAR2(1024 BYTE),
  iroe_entry_detail XMLTYPE,
  CONSTRAINT trtran093c_pk PRIMARY KEY (iroe_deal_number,iroe_serial_number,iroe_subserial_number)
);