CREATE TABLE "TEST_VSTSRedgate".trtran031 (
  mdel_company_code NUMBER(8) NOT NULL,
  mdel_location_code NUMBER(8),
  mdel_deal_number VARCHAR2(25 BYTE) NOT NULL,
  mdel_user_reference VARCHAR2(25 BYTE),
  mdel_security_name VARCHAR2(100 BYTE),
  mdel_borrow_invest NUMBER(8) NOT NULL,
  mdel_transaction_type NUMBER(8) NOT NULL,
  mdel_execute_date DATE NOT NULL,
  mdel_value_date DATE NOT NULL,
  mdel_counter_party NUMBER(8) NOT NULL,
  mdel_local_bank NUMBER(8) NOT NULL,
  mdel_current_ac VARCHAR2(25 BYTE),
  mdel_currency_code NUMBER(8) NOT NULL,
  mdel_unit_quantity NUMBER(15,2),
  mdel_unit_price NUMBER(15,4),
  mdel_deal_amount NUMBER(15,2) NOT NULL,
  mdel_exchange_rate NUMBER(15,6) NOT NULL,
  mdel_amount_local NUMBER(15,2) NOT NULL,
  mdel_maturity_amount NUMBER(15,2),
  mdel_due_date DATE NOT NULL,
  mdel_interest_type NUMBER(8) NOT NULL,
  mdel_base_rate NUMBER(15,6),
  mdel_interest_rate NUMBER(15,6),
  mdel_market_price NUMBER(15,6),
  mdel_repurchase_price NUMBER(15,6),
  mdel_period_type NUMBER(8) NOT NULL,
  mdel_period_number NUMBER(5) NOT NULL,
  mdel_broker_code NUMBER(8) NOT NULL,
  mdel_brokerage_amount NUMBER(15,2),
  mdel_total_charges NUMBER(15,2),
  mdel_dealer_remark VARCHAR2(1000 BYTE),
  mdel_bo_remark VARCHAR2(1000 BYTE),
  mdel_execute_time VARCHAR2(10 BYTE),
  mdel_confirm_date DATE,
  mdel_process_complete NUMBER(8) NOT NULL,
  mdel_complete_date DATE,
  mdel_create_date DATE NOT NULL,
  mdel_entry_detail XMLTYPE,
  mdel_record_status NUMBER(8) NOT NULL,
  CONSTRAINT trtran031_pk PRIMARY KEY (mdel_deal_number)
);