CREATE TABLE "TEST_VSTSRedgate".trtran048 (
  mftr_company_code NUMBER(8) NOT NULL,
  mftr_location_code NUMBER(8) NOT NULL,
  mftr_reference_number VARCHAR2(25 BYTE) NOT NULL,
  mftr_transaction_date DATE NOT NULL,
  mftr_reference_date DATE NOT NULL,
  mftr_scheme_code NUMBER(8) NOT NULL,
  mftr_nav_code VARCHAR2(10 BYTE),
  mftr_transaction_type NUMBER(8) NOT NULL,
  mftr_transaction_amount NUMBER(15,2),
  mftr_transaction_price NUMBER(15,4),
  mftr_transaction_quantity NUMBER(15,4),
  mftr_lockin_duedate DATE,
  mftr_entryload_charges NUMBER(15,2),
  mftr_exitload_charges NUMBER(15,2),
  mftr_transaction_charges NUMBER(15,2),
  mftr_other_charges NUMBER(15,2),
  mftr_bank_code NUMBER(8),
  mftr_current_ac VARCHAR2(25 BYTE),
  mftr_payment_through NUMBER(8),
  mftr_user_reference VARCHAR2(100 BYTE),
  mftr_broker_code NUMBER(8),
  mftr_cheque_number VARCHAR2(50 BYTE),
  mftr_user_remarks VARCHAR2(200 BYTE),
  mftr_process_complete NUMBER(8),
  mftr_complete_date DATE,
  mftr_add_date DATE,
  mftr_create_date DATE,
  mftr_entry_details XMLTYPE,
  mftr_record_status NUMBER(8),
  CONSTRAINT trtran048_pk PRIMARY KEY (mftr_reference_number)
);