CREATE TABLE "TEST_VSTSRedgate".trtran003 (
  brel_company_code NUMBER(8) NOT NULL,
  brel_trade_reference VARCHAR2(25 BYTE) NOT NULL,
  brel_reverse_serial NUMBER(5) NOT NULL,
  brel_entry_date DATE NOT NULL,
  brel_user_reference VARCHAR2(50 BYTE),
  brel_reference_date DATE,
  brel_reversal_type NUMBER(8) NOT NULL,
  brel_reversal_fcy NUMBER(15,2) NOT NULL,
  brel_reversal_rate NUMBER(15,6) NOT NULL,
  brel_reversal_inr NUMBER(15,2) NOT NULL,
  brel_period_code NUMBER(8) NOT NULL,
  brel_trade_period NUMBER(5) NOT NULL,
  brel_maturity_from DATE,
  brel_maturity_date DATE,
  brel_create_date DATE NOT NULL,
  brel_entry_detail XMLTYPE,
  brel_record_status NUMBER(8) NOT NULL,
  brel_local_bank NUMBER(8),
  brel_reverse_reference VARCHAR2(25 BYTE),
  brel_location_code NUMBER(8),
  brel_batch_number VARCHAR2(25 BYTE),
  brel_trade_currency NUMBER(8),
  brel_local_currency NUMBER(8),
  brel_import_export NUMBER(8),
  brel_user_portfolio NUMBER(8),
  brel_other_currency_yesno NUMBER(8),
  brel_product_category NUMBER(8),
  brel_remarks VARCHAR2(1000 BYTE),
  brel_transaction_date DATE,
  brel_sub_portfolio NUMBER(8),
  brel_delivery_batch VARCHAR2(25 BYTE),
  brel_live_reerencerate NUMBER(15,6),
  CONSTRAINT pk_trtran003 PRIMARY KEY (brel_company_code,brel_trade_reference,brel_reverse_serial)
);
COMMENT ON COLUMN "TEST_VSTSRedgate".trtran003.brel_batch_number IS 'This will get update when combine for settlement in inflow and outflow screen';
COMMENT ON COLUMN "TEST_VSTSRedgate".trtran003.brel_delivery_batch IS 'This will get update when settlement happens';