CREATE TABLE "TEST_VSTSRedgate".trtran075 (
  mtmr_company_code NUMBER(8),
  mtmr_bank_code NUMBER(8),
  mtmr_report_date DATE,
  mtmr_user_reference VARCHAR2(25 BYTE),
  mtmr_ibs_ref_no VARCHAR2(25 BYTE),
  mtmr_strategy_id VARCHAR2(25 BYTE),
  mtmr_trade_date DATE,
  mtmr_expiry_date DATE,
  mtmr_maturity_date DATE,
  mtmr_product VARCHAR2(25 BYTE),
  mtmr_booking_loc VARCHAR2(25 BYTE),
  mtmr_dealt_rate NUMBER(15,4),
  mtmr_spot_rate NUMBER(15,4),
  mtmr_reval_rate NUMBER(15,4),
  mtmr_buy_sell VARCHAR2(1 BYTE),
  mtmr_call_put VARCHAR2(1 BYTE),
  mtmr_leg1 VARCHAR2(1 BYTE),
  mtmr_currency1 NUMBER(8),
  mtmr_national1 NUMBER(15,4),
  mtmr_leg2 VARCHAR2(1 BYTE),
  mtmr_currency2 NUMBER(8),
  mtmr_national2 NUMBER(15,4),
  mtmr_strike_rate NUMBER(15,4),
  mtmr_deal_type VARCHAR2(25 BYTE),
  mtmr_settle_ccy NUMBER(8),
  mtmr_mtm_ccy NUMBER(8),
  mtmr_mtm_amount NUMBER(15,4),
  mtmr_mtm_usd NUMBER(15,4),
  mtmr_record_status NUMBER(8),
  mtmr_batch_number VARCHAR2(25 BYTE) NOT NULL,
  mtmr_serial_number NUMBER(8) NOT NULL,
  mtmr_add_date DATE,
  mtmr_create_date DATE,
  mtmr_entry_detail XMLTYPE,
  CONSTRAINT trtran075_pk PRIMARY KEY (mtmr_batch_number,mtmr_serial_number)
);