CREATE TABLE "TEST_VSTSRedgate".trtran047a (
  fdcl_company_code NUMBER(8) NOT NULL,
  fdcl_location_code NUMBER(8) NOT NULL,
  fdcl_fd_number VARCHAR2(25 BYTE) NOT NULL,
  fdcl_bank_reference VARCHAR2(25 BYTE),
  fdcl_reference_date DATE,
  fdcl_local_bank NUMBER(8) NOT NULL,
  fdcl_deposit_amount NUMBER(15,2) NOT NULL,
  fdcl_interest_rate NUMBER(15,2) NOT NULL,
  fdcl_maturity_amount NUMBER(15,2) NOT NULL,
  fdcl_maturity_date DATE,
  fdcl_interest_amount NUMBER(15,2),
  fdcl_closure_date DATE,
  fdcl_create_date DATE NOT NULL,
  fdcl_entry_detail XMLTYPE,
  fdcl_record_status NUMBER(8) NOT NULL,
  fdcl_currency_code NUMBER(8),
  fdcl_scheme_code NUMBER(8),
  fdcl_int_paidamt NUMBER(15,2),
  fdcl_tds_deducted_amt NUMBER(15,2),
  fdcl_mail_id VARCHAR2(100 BYTE),
  fdcl_user_remarks VARCHAR2(200 BYTE),
  fdcl_process_complete NUMBER(8),
  fdcl_tds_surcharge NUMBER(15,2),
  fdcl_penal_interest NUMBER(6,2),
  fdcl_sr_number NUMBER(3) NOT NULL,
  fdcl_closure_srno NUMBER(3) NOT NULL,
  fdcl_complete_date DATE,
  fdcl_closure_type NUMBER(8),
  fdcl_period_days NUMBER(4),
  fdcl_period_daysin NUMBER(8),
  fdcl_period_months NUMBER(4),
  fdcl_period_monthsin NUMBER(8),
  fdcl_renewal_rate NUMBER(6,2),
  fdcl_addtional_interest NUMBER(6,2),
  fdcl_utr_reference VARCHAR2(25 BYTE),
  fdcl_transaction_date DATE,
  fdcl_period_year NUMBER(4),
  fdcl_credit_acno VARCHAR2(25 BYTE),
  fdcl_utr_bank NUMBER(8),
  fdcl_tds_gl NUMBER(8),
  CONSTRAINT pk_trtran047a PRIMARY KEY (fdcl_fd_number,fdcl_sr_number,fdcl_closure_srno)
);