CREATE TABLE "TEST_VSTSRedgate".trtran002d (
  cont_trade_reference VARCHAR2(25 BYTE),
  cont_buyer_seller VARCHAR2(20 BYTE),
  cont_total_quantity NUMBER(15,2),
  cont_product_rate NUMBER(15,2),
  cont_base_amount NUMBER(15,2),
  cont_base_currency VARCHAR2(20 BYTE),
  cont_payment_terms VARCHAR2(60 BYTE),
  cont_local_bank VARCHAR2(20 BYTE),
  cont_month1_qty NUMBER(15,2),
  cont_month1_amount NUMBER(15,2),
  cont_month2_qty NUMBER(15,2),
  cont_month2_amount NUMBER(15,2),
  cont_month3_qty NUMBER(15,2),
  cont_month3_amount NUMBER(15,2),
  cont_month4_qty NUMBER(15,2),
  cont_month4_amount NUMBER(15,2),
  cont_month5_qty NUMBER(15,2),
  cont_month5_amount NUMBER(15,2),
  cont_month6_qty NUMBER(15,2),
  cont_month6_amount NUMBER(15,2),
  cont_month7_qty NUMBER(15,2),
  cont_month7_amount NUMBER(15,2),
  cont_month8_qty NUMBER(15,2),
  cont_month8_amount NUMBER(15,2),
  cont_month9_qty NUMBER(15,2),
  cont_month9_amount NUMBER(15,2),
  cont_month10_qty NUMBER(15,2),
  cont_month10_amount NUMBER(15,2),
  cont_month11_qty NUMBER(15,2),
  cont_month11_amount NUMBER(15,2),
  cont_month12_qty NUMBER(15,2),
  cont_month12_amount NUMBER(15,2),
  cont_add_date DATE,
  cont_create_date DATE,
  cont_record_status NUMBER(8),
  cont_reference_date DATE,
  cont_user_reference VARCHAR2(25 BYTE),
  cont_company_code NUMBER(8),
  cont_product_category VARCHAR2(20 BYTE),
  cont_sub_category VARCHAR2(20 BYTE),
  cont_end_date DATE,
  cont_execute_date DATE,
  cont_cont_remarks VARCHAR2(200 BYTE),
  cont_account_code NUMBER(8),
  cont_outstanding_amount NUMBER(15),
  cont_process_complete VARCHAR2(20 BYTE)
);