CREATE TABLE "TEST_VSTSRedgate".trtran015d_audit (
  char_bank_code NUMBER(8),
  char_effective_date DATE,
  char_account_head NUMBER(8),
  char_limit_type NUMBER(8),
  char_applicable_bill NUMBER(8),
  char_period_type NUMBER(8),
  char_period_upto NUMBER(15),
  char_amount_from NUMBER(15,2),
  char_amount_upto NUMBER(15,2),
  char_percent_type NUMBER(8),
  char_charges_amount NUMBER(15,3),
  char_service_tax NUMBER(15,6),
  char_bill_event NUMBER(8),
  char_timing_event NUMBER(8),
  char_rounding_upto NUMBER(8),
  char_create_date DATE,
  char_entry_detail XMLTYPE,
  char_record_status NUMBER(8),
  char_charging_event NUMBER(8),
  char_based_on NUMBER(8),
  char_reference_number VARCHAR2(25 BYTE) NOT NULL,
  char_product_type NUMBER(8),
  char_min_amount NUMBER(15,2),
  char_max_amount NUMBER(15,2),
  char_company_code NUMBER(8),
  char_location_code NUMBER(8),
  char_lob_code NUMBER(8),
  char_serial_number NUMBER(5) NOT NULL,
  char_consolidate_type NUMBER(8)
);