CREATE TABLE "TEST_VSTSRedgate".trtran090 (
  ifra_company_code NUMBER(8),
  ifra_location_code NUMBER(8),
  ifra_portfolio NUMBER(8),
  ifra_sub_portfolio NUMBER(8),
  ifra_fra_number VARCHAR2(25 BYTE) NOT NULL,
  ifra_execute_date DATE,
  ifra_buy_sell NUMBER(8),
  ifra_counter_party NUMBER(8),
  ifra_currency_code NUMBER(8),
  ifra_notional_amount NUMBER(15,2),
  ifra_sterling_period NUMBER(8),
  ifra_interest_startdate DATE,
  ifra_interest_enddate DATE,
  ifra_fra_rate NUMBER(15,6),
  ifra_interest_daystype NUMBER(8),
  ifra_rate_type NUMBER(8),
  ifra_process_complete NUMBER(8),
  ifra_complete_date DATE,
  ifra_create_date DATE,
  ifra_add_date DATE,
  ifra_entry_details XMLTYPE,
  ifra_time_stamp VARCHAR2(25 BYTE),
  ifra_record_status NUMBER(8),
  ifra_user_reference VARCHAR2(50 BYTE),
  ifra_user_remarks VARCHAR2(50 BYTE),
  ifra_base_rate NUMBER(15,6),
  ifra_spread NUMBER(15,6),
  ifra_expiry_date DATE,
  ifra_execute_time VARCHAR2(10 BYTE),
  ifra_confirm_time VARCHAR2(10 BYTE),
  ifra_confirm_date DATE,
  ifra_bank_reference VARCHAR2(50 BYTE),
  ifra_bo_remark VARCHAR2(1024 BYTE),
  ifra_hedge_trade NUMBER(8),
  CONSTRAINT trtran090_pk PRIMARY KEY (ifra_fra_number)
);