CREATE TABLE "TEST_VSTSRedgate".trtran072 (
  cosu_deal_number VARCHAR2(25 BYTE) NOT NULL,
  cosu_serial_number NUMBER(5) NOT NULL,
  cosu_option_type NUMBER(8),
  cosu_buy_sell NUMBER(8),
  cosu_product_code NUMBER(8),
  cosu_lot_numbers NUMBER(15,2),
  cosu_base_amount NUMBER(15,4),
  cosu_strike_rate NUMBER(15,6),
  cosu_other_amount NUMBER(15,4),
  cosu_local_rate NUMBER(15,6),
  cosu_local_amount NUMBER(15,4),
  cosu_premium_rate NUMBER(15,6),
  cosu_premium_amount NUMBER(15,4),
  cosu_premium_localrate NUMBER(15,6),
  cosu_premium_localamount NUMBER(15,4),
  cosu_maturity_date DATE,
  cosu_settlement_date DATE,
  cosu_delivery_type NUMBER(8),
  cosu_user_remarks VARCHAR2(200 BYTE),
  cosu_action_taken NUMBER(8),
  cosu_process_complete NUMBER(8),
  cosu_complete_date DATE,
  cosu_record_status NUMBER(8),
  cosu_subserial_number NUMBER(25),
  CONSTRAINT trtran072_pk PRIMARY KEY (cosu_deal_number,cosu_serial_number)
);