CREATE TABLE "TEST_VSTSRedgate".trtran002e (
  expo_reference_date DATE,
  expo_change_type VARCHAR2(2 BYTE),
  expo_company_code NUMBER(8),
  expo_account VARCHAR2(10 BYTE),
  expo_counter_party NUMBER(8),
  expo_counterparty_remarks VARCHAR2(100 BYTE),
  expo_place VARCHAR2(100 BYTE),
  expo_due_date DATE,
  expo_flag_m CHAR,
  expo_lc_no VARCHAR2(50 BYTE),
  expo_lc_date VARCHAR2(10 BYTE),
  expo_qty NUMBER(15,2),
  expo_rate NUMBER(15,4),
  expo_intamt NUMBER(15,4),
  expo_conchrg NUMBER(15,2),
  expo_base_currency NUMBER(8),
  expo_base_amount NUMBER(15,2),
  expo_exchage_rate NUMBER(15,4),
  expo_amount_local NUMBER(15,2),
  expo_payment_confirmed VARCHAR2(1 BYTE),
  expo_vessel_name VARCHAR2(50 BYTE),
  expo_port VARCHAR2(50 BYTE),
  expo_app VARCHAR2(20 BYTE),
  expo_beneficiary VARCHAR2(100 BYTE),
  expo_usance VARCHAR2(100 BYTE),
  expo_bl_date VARCHAR2(50 BYTE),
  expo_contract_type VARCHAR2(100 BYTE),
  expo_contract_no VARCHAR2(100 BYTE),
  expo_contract_date VARCHAR2(20 BYTE),
  expo_remark VARCHAR2(100 BYTE),
  expo_serial_no NUMBER(5)
);