CREATE TABLE "TEST_VSTSRedgate".trtran103b_fxall_detail (
  sourceofdata VARCHAR2(25 BYTE),
  reference_no VARCHAR2(25 BYTE),
  dealdate VARCHAR2(25 BYTE),
  dealtime VARCHAR2(25 BYTE),
  dealerid VARCHAR2(50 BYTE),
  dealconfirmationdate VARCHAR2(25 BYTE),
  dealconfirmationtime VARCHAR2(25 BYTE),
  dealconfirmedby VARCHAR2(50 BYTE),
  bankcode VARCHAR2(50 BYTE),
  bankname VARCHAR2(100 BYTE),
  buysell VARCHAR2(25 BYTE),
  "PERIOD" VARCHAR2(25 BYTE),
  basecurrency VARCHAR2(25 BYTE),
  othercurrency VARCHAR2(25 BYTE),
  dealamount VARCHAR2(25 BYTE),
  exchangerate VARCHAR2(25 BYTE),
  maturityfromdate VARCHAR2(25 BYTE),
  maturitydate VARCHAR2(25 BYTE),
  exchange_rate VARCHAR2(25 BYTE),
  dealername VARCHAR2(25 BYTE),
  confirmedbyname VARCHAR2(25 BYTE),
  comment_text VARCHAR2(25 BYTE),
  spotrate VARCHAR2(25 BYTE),
  userdefined1 VARCHAR2(25 BYTE),
  userdefined2 VARCHAR2(25 BYTE),
  userdefined3 VARCHAR2(25 BYTE),
  userdefined4 VARCHAR2(25 BYTE),
  userdefined5 VARCHAR2(25 BYTE),
  userdefined6 VARCHAR2(25 BYTE),
  counterpartydearid VARCHAR2(50 BYTE),
  counterparty_dear_name VARCHAR2(50 BYTE),
  ouremailaddress VARCHAR2(50 BYTE),
  theiremailaddressd VARCHAR2(50 BYTE),
  dealcreateddate DATE DEFAULT sysdate,
  dealnumber VARCHAR2(25 BYTE),
  recordstatus NUMBER(8) DEFAULT 10200001,
  business_unit NUMBER(8),
  profit_center NUMBER(8),
  forward_rate NUMBER(15,6),
  margin NUMBER(15,6),
  classification_code NUMBER(8),
  entrydate DATE,
  referencenumber VARCHAR2(500 BYTE),
  counterpartycode NUMBER(8),
  othercurrencycode NUMBER(8),
  basecurrencycode NUMBER(8),
  buysellcode NUMBER(8),
  bank_code1 VARCHAR2(100 BYTE),
  bankdealername VARCHAR2(100 BYTE),
  bankcodedealername VARCHAR2(100 BYTE),
  bankcode1 VARCHAR2(100 BYTE),
  baseamount NUMBER(15,2),
  cancelamount NUMBER(15,2)
);