CREATE TABLE "TEST_VSTSRedgate".trtran001ra (
  dear_reference_number VARCHAR2(50 BYTE),
  dear_company_code NUMBER(8),
  dear_location_code NUMBER(8),
  dear_backup_deal NUMBER(8),
  dear_init_code NUMBER(8),
  dear_buy_sell NUMBER(8),
  dear_base_currency NUMBER(8),
  dear_other_currency NUMBER(8),
  dear_currency_pair NUMBER(8),
  dear_maturity_date DATE,
  dear_spot_rate NUMBER(15,6),
  dear_forward_rate NUMBER(15,6),
  dear_margin_rate NUMBER(15,6),
  dear_exchnage_rate NUMBER(15,6),
  dear_newmaturity_date DATE,
  dear_create_date DATE,
  dear_record_status NUMBER(8),
  dear_counter_party NUMBER(8),
  dear_user_remarks VARCHAR2(100 BYTE),
  dear_base_amount NUMBER(15,2),
  dear_other_amount NUMBER(15,2),
  dear_user_reference VARCHAR2(50 BYTE),
  dear_execute_date DATE,
  dear_user_id VARCHAR2(25 BYTE),
  dear_forwarddeal_number VARCHAR2(100 BYTE),
  dear_profit_loss NUMBER(15,4),
  dear_hedge_trade NUMBER(8),
  dear_dealer_name VARCHAR2(50 BYTE),
  dear_counter_dealer VARCHAR2(50 BYTE),
  dear_wash_rate NUMBER(15,6),
  dear_conversion_rate NUMBER(15,6),
  dear_conversion_pandl NUMBER(15,4),
  dear_cancel_spot NUMBER(15,6),
  dear_cancel_margin NUMBER(15,6),
  dear_cancel_rate NUMBER(15,6),
  dear_deal_amount NUMBER(15,4),
  dear_expiry_date DATE,
  dear_newdeal_number VARCHAR2(25 BYTE),
  dear_cancel_forward NUMBER(15,6),
  dear_rollover_type NUMBER(8),
  dear_discounted_amount NUMBER(15,4),
  dear_location_codenew NUMBER(8),
  dear_backup_dealnew NUMBER(8),
  dear_init_codenew NUMBER(8),
  dear_counter_partynew NUMBER(8),
  dear_reference_date DATE,
  dear_cancel_remarks VARCHAR2(200 BYTE),
  dear_cancel_reference VARCHAR2(25 BYTE)
);