CREATE TABLE "TEST_VSTSRedgate".trtran077 (
  nser_batch_number VARCHAR2(25 BYTE) NOT NULL,
  nser_serial_number NUMBER(8) NOT NULL,
  nser_company_code NUMBER(8),
  nser_upload_date DATE,
  nser_contract VARCHAR2(100 BYTE),
  nser_product_code VARCHAR2(25 BYTE),
  nser_due_date DATE,
  nser_spot_rate NUMBER(15,4),
  nser_buy_put VARCHAR2(25 BYTE),
  nser_previous NUMBER(15,4),
  nser_open_price NUMBER(15,4),
  nser_high_price NUMBER(15,4),
  nser_low_price NUMBER(15,4),
  nser_close_price NUMBER(15,4),
  nser_settlement NUMBER(15,4),
  nser_net_change NUMBER(15,4),
  nser_oino_con NUMBER(15,4),
  nser_traded_qua NUMBER(15,4),
  nser_trd_nocon NUMBER(15,4),
  nser_uderlaying NUMBER(15,4),
  nser_notional NUMBER(15,4),
  nser_premium NUMBER(15,4),
  nser_record_status NUMBER(8),
  nser_add_date DATE,
  nser_create_date DATE,
  nser_entry_detail XMLTYPE,
  CONSTRAINT trtran077_pk PRIMARY KEY (nser_batch_number,nser_serial_number)
);