CREATE TABLE "TEST_VSTSRedgate".trtran033 (
  bred_company_code NUMBER(8),
  bred_location_code NUMBER(8),
  bred_deal_type NUMBER(8),
  bred_deal_number VARCHAR2(25 BYTE) NOT NULL,
  bred_serial_number NUMBER(5) NOT NULL,
  bred_transaction_type NUMBER(8),
  bred_deal_date DATE,
  bred_deal_time VARCHAR2(10 BYTE),
  bred_settlement_date DATE,
  bred_counter_party NUMBER(8),
  bred_currency_code NUMBER(8),
  bred_period_year NUMBER(3),
  bred_period_month NUMBER(3),
  bred_period_days NUMBER(3),
  bred_market_price NUMBER(15,4),
  bred_unit_quantity NUMBER(15,2),
  bred_deal_amount NUMBER(15,2),
  bred_accrued_interest NUMBER(15,2),
  bred_exchange_rate NUMBER(15,6),
  bred_amount_local NUMBER(15,2),
  bred_broker_code NUMBER(8),
  bred_dp_id NUMBER(8),
  bred_payment_through NUMBER(8),
  bred_settlement_security NUMBER(8),
  bred_dplinked_bank NUMBER(8),
  bred_dplinked_ac VARCHAR2(25 BYTE),
  bred_dealer_remark VARCHAR2(1000 BYTE),
  bred_bo_remark VARCHAR2(1000 BYTE),
  bred_process_complete NUMBER(8),
  bred_complete_date DATE,
  bred_create_date DATE,
  bred_entry_detail XMLTYPE,
  bred_record_status NUMBER(8),
  bred_add_date DATE,
  bred_paid_amount NUMBER(15,2),
  bred_interest_charged NUMBER(15,2),
  CONSTRAINT trtran033_pk PRIMARY KEY (bred_deal_number,bred_serial_number)
);