CREATE TABLE "TEST_VSTSRedgate".trtran103a_fxgo (
  dealing_system VARCHAR2(25 BYTE),
  deal_number VARCHAR2(100 BYTE),
  buy_sell NUMBER(8),
  base_currency NUMBER(8),
  other_currency NUMBER(8),
  counter_party NUMBER(8),
  trader_name VARCHAR2(25 BYTE),
  counterparty_trader_name VARCHAR2(25 BYTE),
  baseamount NUMBER(15,2),
  otheramount NUMBER(15,2),
  spotrate NUMBER(15,6),
  exchangerate NUMBER(15,6),
  date_of_deal DATE,
  time_of_deal VARCHAR2(10 BYTE),
  trade_date DATE,
  date_confirmed DATE,
  time_confirmed VARCHAR2(10 BYTE),
  settlement_date DATE,
  delivery_date DATE,
  classification NUMBER(8),
  business_unit NUMBER(8),
  profit_center NUMBER(8),
  forward_rate NUMBER(15,6),
  margin_rate NUMBER(15,6),
  referencenumber VARCHAR2(100 BYTE),
  recordstatus NUMBER(8),
  createdate DATE,
  adddate DATE,
  userid VARCHAR2(25 BYTE),
  user_name VARCHAR2(25 BYTE)
);