CREATE TABLE "TEST_VSTSRedgate".trtran078 (
  opmm_trade_date DATE NOT NULL,
  opmm_serial_number NUMBER(5) NOT NULL,
  opmm_contract_type VARCHAR2(50 BYTE) NOT NULL,
  opmm_base_currency NUMBER(8) NOT NULL,
  opmm_other_currency NUMBER(8) NOT NULL,
  opmm_maturity_date DATE NOT NULL,
  opmm_put_call NUMBER(8) NOT NULL,
  opmm_strike_rate NUMBER(15,6) NOT NULL,
  opmm_previous_settlement NUMBER(15,6),
  opmm_open_price NUMBER(15,6),
  opmm_high_price NUMBER(15,6),
  opmm_low_price NUMBER(15,6),
  opmm_close_price NUMBER(15,6),
  opmm_settlement_price NUMBER(15,6),
  opmm_net_change NUMBER(15,6),
  opmm_open_interest NUMBER(15,2),
  opmm_traded_quantity NUMBER(15,2),
  opmm_no_contracts NUMBER(15,2),
  opmm_underling_st NUMBER(15,2),
  opmm_notional_volume NUMBER(15,2),
  opmm_premium_tr NUMBER(15,2),
  opmm_create_date DATE,
  opmm_add_date DATE,
  opmm_entry_details XMLTYPE,
  opmm_record_status NUMBER(8),
  CONSTRAINT trtran078_pk PRIMARY KEY (opmm_trade_date,opmm_serial_number,opmm_contract_type,opmm_base_currency,opmm_other_currency,opmm_maturity_date,opmm_put_call,opmm_strike_rate)
);