CREATE TABLE "TEST_VSTSRedgate".trtran047 (
  fdrf_company_code NUMBER(8) NOT NULL,
  fdrf_location_code NUMBER(8) NOT NULL,
  fdrf_fd_number VARCHAR2(25 BYTE) NOT NULL,
  fdrf_bank_reference VARCHAR2(25 BYTE),
  fdrf_reference_date DATE,
  fdrf_local_bank NUMBER(8) NOT NULL,
  fdrf_deposit_amount NUMBER(15,2) NOT NULL,
  fdrf_interest_rate NUMBER(15,2) NOT NULL,
  fdrf_maturity_amount NUMBER(15,2) NOT NULL,
  fdrf_maturity_date DATE,
  fdrf_interest_amount NUMBER(15,2),
  fdrf_closure_type NUMBER(8) NOT NULL,
  fdrf_closure_date DATE,
  fdrf_new_reference VARCHAR2(25 BYTE),
  fdrf_create_date DATE NOT NULL,
  fdrf_entry_detail XMLTYPE,
  fdrf_record_status NUMBER(8) NOT NULL,
  fdrf_deposit_scheme NUMBER(8),
  fdrf_compound_frequency NUMBER(8),
  fdrf_currency_code NUMBER(8),
  fdrf_scheme_code NUMBER(8),
  fdrf_open_date DATE,
  fdrf_interest_plan NUMBER(8),
  fdrf_period_months NUMBER(4),
  fdrf_period_monthsin NUMBER(8),
  fdrf_period_days NUMBER(4),
  fdrf_period_daysin NUMBER(8),
  fdrf_addtional_interest NUMBER(5,2),
  fdrf_periodical_int NUMBER(15,2),
  fdrf_int_paidamt NUMBER(15,2),
  fdrf_tds_deducted_amt NUMBER(15,2),
  fdrf_interest_type NUMBER(8),
  fdrf_maturity_type NUMBER(8),
  fdrf_compounding_type NUMBER(8),
  fdrf_payment_frequency NUMBER(8),
  fdrf_autorenew_acno NUMBER(8),
  fdrf_mail_id VARCHAR2(100 BYTE),
  fdrf_user_remarks VARCHAR2(200 BYTE),
  fdrf_account_status NUMBER(8),
  fdrf_intcr_account NUMBER(15),
  fdrf_tds_plan NUMBER(8),
  fdrf_tds_drac NUMBER(15),
  fdrf_prinicipal_type NUMBER(8),
  fdrf_installment_type NUMBER(8),
  fdrf_based_on NUMBER(8),
  fdrf_process_complete NUMBER(8),
  fdrf_tds_surcharge NUMBER(15,2),
  fdrf_credit_acno VARCHAR2(25 BYTE),
  fdrf_int_provamt NUMBER(15),
  fdrf_sr_number NUMBER(3) NOT NULL,
  fdrf_complete_date DATE,
  fdrf_utr_reference VARCHAR2(25 BYTE),
  fdrf_transaction_date DATE,
  fdrf_utr_bank VARCHAR2(25 BYTE),
  fdrf_utr_date DATE,
  fdrf_interest_syscalc NUMBER(15,2),
  fdrf_period_year NUMBER(4),
  CONSTRAINT trtran047_pk PRIMARY KEY (fdrf_company_code,fdrf_location_code,fdrf_fd_number,fdrf_sr_number)
);