CREATE TABLE "TEST_VSTSRedgate".trtran012 (
  drat_currency_code NUMBER(8) NOT NULL,
  drat_for_currency NUMBER(8) NOT NULL,
  drat_effective_date DATE NOT NULL,
  drat_serial_number NUMBER(5) NOT NULL,
  drat_rate_time VARCHAR2(10 BYTE),
  drat_time_stamp VARCHAR2(25 BYTE),
  drat_rate_description VARCHAR2(50 BYTE),
  drat_spot_bid NUMBER(15,6),
  drat_spot_ask NUMBER(15,6),
  drat_month1_bid NUMBER(15,6),
  drat_month1_ask NUMBER(15,6),
  drat_month2_bid NUMBER(15,6),
  drat_month2_ask NUMBER(15,6),
  drat_month3_bid NUMBER(15,6),
  drat_month3_ask NUMBER(15,6),
  drat_month6_bid NUMBER(15,6),
  drat_month6_ask NUMBER(15,6),
  drat_month9_bid NUMBER(15,6),
  drat_month9_ask NUMBER(15,6),
  drat_month12_bid NUMBER(15,6),
  drat_month12_ask NUMBER(15,6),
  drat_create_date DATE NOT NULL,
  drat_add_date DATE NOT NULL,
  drat_entry_detail XMLTYPE,
  drat_record_status NUMBER(8) NOT NULL,
  drat_month4_bid NUMBER(15,6),
  drat_month4_ask NUMBER(15,6),
  drat_month5_bid NUMBER(15,6),
  drat_month5_ask NUMBER(15,6),
  drat_month7_bid NUMBER(15,6),
  drat_month7_ask NUMBER(15,6),
  drat_month8_bid NUMBER(15,6),
  drat_month8_ask NUMBER(15,6),
  drat_month10_bid NUMBER(15,6),
  drat_month10_ask NUMBER(15,6),
  drat_month11_bid NUMBER(15,6),
  drat_month11_ask NUMBER(15,6),
  drat_cash_ask NUMBER(15,6),
  drat_cash_bid NUMBER(15,6),
  drat_tom_ask NUMBER(15,6),
  drat_tom_bid NUMBER(15,6),
  CONSTRAINT trtran012_pk PRIMARY KEY (drat_currency_code,drat_for_currency,drat_serial_number,drat_effective_date)
);