CREATE TABLE "TEST_VSTSRedgate".trtran074a (
  optv_security VARCHAR2(25 BYTE),
  optv_external_id VARCHAR2(500 BYTE),
  optv_pc VARCHAR2(5 BYTE),
  optv_delta_usd NUMBER(15,2),
  optv_pos_delta2 NUMBER(15,2),
  optv_pos_delta1 NUMBER(15,2),
  optv_counter_party NUMBER(8),
  optv_trade_date DATE,
  optv_ccy1_amt NUMBER(15,2),
  optv_strike NUMBER(15,4),
  optv_expiry_date DATE,
  optv_delivery_date DATE,
  optv_prem_ccy1 NUMBER(15,2),
  optv_prem_ccy2 NUMBER(15,2),
  optv_pl_ccy2 NUMBER(15,2),
  optv_pl_ccy1 NUMBER(15,2),
  optv_value_ccy1 NUMBER(15,2),
  optv_value_ccy2 NUMBER(15,2),
  optv_entry_date DATE,
  optv_create_date DATE,
  optv_record_status NUMBER(8),
  optv_company_code NUMBER(8),
  optv_business_unit NUMBER(8)
);