CREATE TABLE "TEST_VSTSRedgate".trtran061 (
  cfut_company_code NUMBER(8) NOT NULL,
  cfut_deal_number VARCHAR2(25 BYTE) NOT NULL,
  cfut_user_reference VARCHAR2(25 BYTE),
  cfut_execute_date DATE NOT NULL,
  cfut_exchange_code NUMBER(8) NOT NULL,
  cfut_counter_party NUMBER(8) NOT NULL,
  cfut_base_currency NUMBER(8) NOT NULL,
  cfut_other_currency NUMBER(8) NOT NULL,
  cfut_exchange_rate NUMBER(15,6) NOT NULL,
  cfut_local_rate NUMBER(15,6),
  cfut_base_amount NUMBER(15,2) NOT NULL,
  cfut_other_amount NUMBER(15,2),
  cfut_contract_type NUMBER(8) DEFAULT 60700003 NOT NULL,
  cfut_hedge_trade NUMBER(8) NOT NULL,
  cfut_buy_sell NUMBER(8) NOT NULL,
  cfut_product_code NUMBER(8) NOT NULL,
  cfut_local_bank NUMBER(8) DEFAULT 30699999 NOT NULL,
  cfut_lot_numbers NUMBER(15,6),
  cfut_lot_quantity NUMBER(10) NOT NULL,
  cfut_margin_rate NUMBER(15,6) DEFAULT 0 NOT NULL,
  cfut_margin_amount NUMBER(15,2) DEFAULT 0 NOT NULL,
  cfut_brokerage_rate NUMBER(15,6) DEFAULT 0 NOT NULL,
  cfut_brokerage_amount NUMBER(15,2) DEFAULT 0 NOT NULL,
  cfut_service_tax NUMBER(15,2) DEFAULT 0,
  cfut_transaction_cost NUMBER(15,2) DEFAULT 0,
  cfut_other_charges NUMBER(15,2) DEFAULT 0,
  cfut_maturity_date DATE NOT NULL,
  cfut_user_id VARCHAR2(30 BYTE) NOT NULL,
  cfut_dealer_remark VARCHAR2(1000 BYTE),
  cfut_bo_remark VARCHAR2(1000 BYTE),
  cfut_confirm_date DATE,
  cfut_execute_time VARCHAR2(10 BYTE) NOT NULL,
  cfut_time_stamp VARCHAR2(25 BYTE) NOT NULL,
  cfut_process_complete NUMBER(8) DEFAULT 12400002 NOT NULL,
  cfut_complete_date DATE,
  cfut_create_date DATE NOT NULL,
  cfut_add_date DATE NOT NULL,
  cfut_entry_detail XMLTYPE,
  cfut_record_status NUMBER(8) NOT NULL,
  cfut_backup_deal NUMBER(8),
  cfut_init_code NUMBER(8),
  cfut_bank_reference VARCHAR2(50 BYTE),
  cfut_confirm_time VARCHAR2(10 BYTE),
  cfut_location_code NUMBER(8),
  cfut_spot_rate NUMBER(15,4),
  cfut_forward_rate NUMBER(15,4),
  cfut_bank_margin NUMBER(15,4),
  cfut_maturity_from DATE,
  cfut_dealer_name VARCHAR2(50 BYTE),
  cfut_counter_dealer VARCHAR2(50 BYTE),
  cfut_product_description VARCHAR2(50 BYTE),
  CONSTRAINT pk_trtran061 PRIMARY KEY (cfut_company_code,cfut_deal_number)
);