CREATE TABLE "TEST_VSTSRedgate".trtran090a (
  ifrs_fra_number VARCHAR2(25 BYTE) NOT NULL,
  ifrs_serial_number VARCHAR2(25 BYTE) NOT NULL,
  ifrs_settlement_date DATE,
  ifrs_fra_refrate NUMBER(15,6),
  ifrs_user_remarks VARCHAR2(50 BYTE),
  ifrs_create_date DATE,
  ifrs_add_date DATE,
  ifrs_entry_details XMLTYPE,
  ifrs_time_stamp VARCHAR2(25 BYTE),
  ifrs_record_status NUMBER(8),
  ifrs_base_rate NUMBER(15,6),
  ifrs_spread NUMBER(15,6),
  ifrs_conversion_rate NUMBER(15,6),
  ifrs_payoff_localamount NUMBER(15,2),
  ifrs_payoff_amount NUMBER(15,2),
  ifrs_payoff_type NUMBER(8),
  ifrs_payoff_date DATE,
  ifrs_notional_amount NUMBER(15,2),
  ifrs_confirm_time VARCHAR2(10 BYTE),
  ifrs_confirm_date DATE,
  ifrs_bank_reference VARCHAR2(50 BYTE),
  ifrs_bo_remark VARCHAR2(1024 BYTE),
  ifrs_hedge_trade NUMBER(8),
  CONSTRAINT trtran090a_pk PRIMARY KEY (ifrs_fra_number,ifrs_serial_number)
);