CREATE TABLE "TEST_VSTSRedgate".trtran008c (
  ciaf_format_file VARCHAR2(25 BYTE) NOT NULL,
  ciaf_voucher_number VARCHAR2(25 BYTE) NOT NULL,
  ciaf_serial_number NUMBER(7) NOT NULL,
  ciaf_format_type VARCHAR2(10 BYTE),
  ciaf_file_number VARCHAR2(50 BYTE),
  ciaf_document_date DATE,
  ciaf_posting_date DATE,
  ciaf_document_type VARCHAR2(25 BYTE),
  ciaf_currency_code VARCHAR2(3 BYTE),
  ciaf_exchange_rate NUMBER(15,4),
  ciaf_reference_number VARCHAR2(256 BYTE),
  ciaf_document_headertext VARCHAR2(25 BYTE),
  ciaf_posting_key VARCHAR2(10 BYTE),
  ciaf_account_number VARCHAR2(25 BYTE),
  ciaf_voucher_amount NUMBER(15,2),
  ciaf_document_number VARCHAR2(25 BYTE),
  ciaf_bank_account VARCHAR2(25 BYTE),
  ciaf_profit_center VARCHAR2(10 BYTE),
  ciaf_cost_center VARCHAR2(10 BYTE),
  ciaf_text_field VARCHAR2(200 BYTE),
  ciaf_due_on DATE,
  ciaf_due_by DATE,
  ciaf_issue_date DATE,
  ciaf_advance_amount NUMBER(15,2),
  ciaf_currency_details VARCHAR2(25 BYTE),
  ciaf_record_content VARCHAR2(512 BYTE),
  ciaf_process_complete NUMBER(8),
  ciaf_time_stamp VARCHAR2(25 BYTE),
  ciaf_create_date DATE NOT NULL,
  ciaf_entry_detail XMLTYPE,
  ciaf_record_status NUMBER(8) NOT NULL,
  ciaf_voucher_fcy NUMBER(15,4),
  ciaf_bank_reference VARCHAR2(25 BYTE),
  ciaf_company_code VARCHAR2(10 BYTE),
  ciaf_value_date VARCHAR2(10 BYTE),
  CONSTRAINT pk_trtran008c PRIMARY KEY (ciaf_format_file,ciaf_voucher_number,ciaf_serial_number)
);