CREATE TABLE "TEST_VSTSRedgate".trtran102 (
  intc_exchange_type VARCHAR2(25 BYTE),
  intc_party_code VARCHAR2(25 BYTE),
  intc_party_name NVARCHAR2(100),
  intc_currency_symbol NVARCHAR2(20),
  intc_expiry_date DATE,
  intc_option_type NVARCHAR2(20),
  intc_strike_price NUMBER(15,6),
  intc_create_date DATE,
  intc_record_status NUMBER(8),
  intc_buy_sell VARCHAR2(20 BYTE),
  intc_quantity NUMBER(15,2),
  intc_rate NUMBER(15,6),
  intc_amount NUMBER(15,2),
  intc_serial_number NUMBER(8),
  intc_reference_number VARCHAR2(200 BYTE) NOT NULL,
  intc_refsta_number VARCHAR2(200 BYTE),
  intc_broker_name NUMBER(8),
  intc_classification_code NUMBER(8),
  intc_business_unit NUMBER(8),
  intc_profit_center NUMBER(8),
  intc_settlement_date DATE,
  intc_dealer_name VARCHAR2(50 BYTE),
  intc_counter_dealer VARCHAR2(50 BYTE),
  intc_spot_rate NUMBER(15,6),
  intc_forward_rate NUMBER(15,6),
  intc_margin_rate NUMBER(15,6),
  intc_base_currency NUMBER(8),
  intc_other_currency NUMBER(8),
  intc_product_code NUMBER(8),
  intc_deal_number VARCHAR2(25 BYTE),
  intc_allin_rate NUMBER(15,6),
  intc_add_date DATE,
  intc_out_quantity NUMBER(8),
  intc_user_id VARCHAR2(50 BYTE),
  CONSTRAINT trtran102_pk PRIMARY KEY (intc_reference_number)
);