CREATE TABLE "TEST_VSTSRedgate".trtran031a (
  mbor_company_code NUMBER(8) NOT NULL,
  mbor_location_code NUMBER(8),
  mbor_deal_number VARCHAR2(25 BYTE) NOT NULL,
  mbor_user_reference VARCHAR2(25 BYTE),
  mbor_security_name VARCHAR2(100 BYTE),
  mbor_borrow_invest NUMBER(8) NOT NULL,
  mbor_transaction_type NUMBER(8) NOT NULL,
  mbor_execute_date DATE NOT NULL,
  mbor_value_date DATE NOT NULL,
  mbor_counter_party NUMBER(8) NOT NULL,
  mbor_dp_id VARCHAR2(25 BYTE),
  mbor_client_id VARCHAR2(25 BYTE),
  mbor_pan_number VARCHAR2(10 BYTE),
  mbor_company_rating VARCHAR2(25 BYTE),
  mbor_rating_agency VARCHAR2(100 BYTE),
  mbor_local_bank NUMBER(8) NOT NULL,
  mbor_current_ac VARCHAR2(25 BYTE),
  mbor_currency_code NUMBER(8) NOT NULL,
  mbor_unit_quantity NUMBER(15,2),
  mbor_unit_price NUMBER(15,4),
  mbor_deal_amount NUMBER(15,2) NOT NULL,
  mbor_exchange_rate NUMBER(15,6) NOT NULL,
  mbor_amount_local NUMBER(15,2) NOT NULL,
  mbor_face_value NUMBER(15,2),
  mbor_due_date DATE NOT NULL,
  mbor_interest_type NUMBER(8) NOT NULL,
  mbor_base_rate NUMBER(15,6),
  mbor_interest_rate NUMBER(15,6),
  mbor_market_price NUMBER(15,6),
  mbor_repurchase_price NUMBER(15,6),
  mbor_period_type NUMBER(8) NOT NULL,
  mbor_period_number NUMBER(5) NOT NULL,
  mbor_broker_code NUMBER(8) NOT NULL,
  mbor_brokerage_amount NUMBER(15,2),
  mbor_total_charges NUMBER(15,2),
  mbor_dealer_remark VARCHAR2(1000 BYTE),
  mbor_bo_remark VARCHAR2(1000 BYTE),
  mbor_execute_time VARCHAR2(10 BYTE),
  mbor_confirm_date DATE,
  mbor_process_complete NUMBER(8) NOT NULL,
  mbor_complete_date DATE,
  mbor_create_date DATE NOT NULL,
  mbor_entry_detail XMLTYPE,
  mbor_record_status NUMBER(8) NOT NULL,
  mbor_interest_amount NUMBER(15,2),
  CONSTRAINT trtran031a_pk PRIMARY KEY (mbor_deal_number)
);