CREATE TABLE "TEST_VSTSRedgate".trtran081 (
  tlon_company_code NUMBER(8) NOT NULL,
  tlon_location_code NUMBER(8) NOT NULL,
  tlon_loan_number VARCHAR2(25 BYTE) NOT NULL,
  tlon_loan_type NUMBER(8) NOT NULL,
  tlon_local_bank NUMBER(8) NOT NULL,
  tlon_currency_code NUMBER(8) NOT NULL,
  tlon_period_type NUMBER(8),
  tlon_period_number NUMBER(5),
  tlon_instalment_type NUMBER(8),
  tlon_instalment_amount NUMBER(15,4),
  tlon_due_date DATE,
  tlon_libor_rate NUMBER(15,6),
  tlon_interest_spread NUMBER(15,6),
  tlon_interest_rate NUMBER(15,6),
  tlon_interest_type NUMBER(8),
  tlon_float_rate NUMBER(8),
  tlon_bank_reference VARCHAR2(25 BYTE),
  tlon_reference_date DATE,
  tlon_reason_code NUMBER(8),
  tlon_reason_detail VARCHAR2(50 BYTE),
  tlon_sanctioned_fcy NUMBER(15,4),
  tlon_sanctioned_rate NUMBER(15,6),
  tlon_sanctioned_inr NUMBER(15,2),
  tlon_disbursal_date DATE,
  tlon_conversion_rate NUMBER(15,6),
  tlon_transfer_code NUMBER(8),
  tlon_total_charges NUMBER(15,2),
  tlon_loan_remarks VARCHAR2(512 BYTE),
  tlon_process_complete NUMBER(8),
  tlon_completion_date DATE,
  tlon_create_date DATE NOT NULL,
  tlon_entry_detail XMLTYPE,
  tlon_record_status NUMBER(8),
  tlon_sap_bank VARCHAR2(30 BYTE),
  tlon_saploan_type VARCHAR2(30 BYTE),
  tlon_portfolio_type VARCHAR2(30 BYTE),
  tlon_sapinterest_type VARCHAR2(30 BYTE),
  tlon_flow_type VARCHAR2(10 BYTE),
  CONSTRAINT pk_tftran121 PRIMARY KEY (tlon_company_code,tlon_location_code,tlon_loan_number)
);