CREATE TABLE "TEST_VSTSRedgate".trtran073 (
  corv_company_code NUMBER(8) NOT NULL,
  corv_deal_number VARCHAR2(25 BYTE) NOT NULL,
  corv_serial_number NUMBER(5) NOT NULL,
  corv_subserial_number NUMBER(5) NOT NULL,
  corv_reverse_serial NUMBER(5) NOT NULL,
  corv_exercise_date DATE,
  corv_exercise_type NUMBER(8),
  corv_settlement_date DATE,
  corv_base_amount NUMBER(15,4) NOT NULL,
  corv_exercise_rate NUMBER(15,6),
  corv_other_amount NUMBER(15,4),
  corv_wash_rate NUMBER(15,6),
  corv_rbi_refrate NUMBER(15,6),
  corv_profit_loss NUMBER(15,2),
  corv_pl_voucher VARCHAR2(25 BYTE),
  corv_time_stamp VARCHAR2(25 BYTE),
  corv_dealer_remarks VARCHAR2(100 BYTE),
  corv_trade_reference VARCHAR2(25 BYTE),
  corv_trade_serial NUMBER(5),
  corv_premium_rate NUMBER(15,6),
  corv_premium_amount NUMBER(15,2),
  corv_premium_exrate NUMBER(15,6),
  corv_premium_local NUMBER(15,2),
  corv_create_date DATE,
  corv_add_date DATE,
  corv_record_status NUMBER(8),
  corv_premium_status NUMBER(8),
  corv_pandl_spot NUMBER(15,4),
  corv_pandl_usd NUMBER(15,2),
  copt_cancel_reason NUMBER(8),
  corv_confirm_date DATE,
  corv_confirm_time VARCHAR2(10 BYTE),
  corv_bank_reference VARCHAR2(50 BYTE),
  corv_bo_remark VARCHAR2(1024 BYTE),
  corv_entry_detail XMLTYPE,
  corv_margin_rate NUMBER(15,6),
  corv_dealer_name VARCHAR2(50 BYTE),
  corv_counter_dealer VARCHAR2(50 BYTE),
  corv_user_id VARCHAR2(25 BYTE),
  corv_location_code NUMBER(8),
  CONSTRAINT trtran073_pk PRIMARY KEY (corv_company_code,corv_deal_number,corv_serial_number,corv_subserial_number,corv_reverse_serial)
);