CREATE TABLE "TEST_VSTSRedgate".trtran103 (
  intc_exchange_type NUMBER(8),
  intc_party_code VARCHAR2(25 BYTE),
  intc_party_name NUMBER(8),
  intc_currency_symbol NUMBER(8),
  intc_expiry_date DATE,
  intc_option_type NVARCHAR2(20),
  intc_strike_price NUMBER(15,6),
  intc_create_date DATE,
  intc_record_status NUMBER(8),
  intc_buy_sell VARCHAR2(20 BYTE),
  intc_quantity NUMBER(15,2),
  intc_rate NUMBER(15,6),
  intc_amount NUMBER(15,2),
  intc_serial_number NUMBER(8),
  intc_reference_number VARCHAR2(200 BYTE),
  intc_refsta_number VARCHAR2(200 BYTE),
  intc_buy_qty NUMBER(15,2),
  intc_buy_rate NUMBER(15,6),
  intc_buy_amount NUMBER(15,2),
  intc_sell_qty NUMBER(15,2),
  intc_sell_rate NUMBER(15,6),
  intc_sell_amount NUMBER(15,2),
  intc_net_qty NUMBER(15,2),
  intc_broker_name NUMBER(8),
  intc_base_currency NUMBER(8),
  intc_other_currency NUMBER(8),
  intc_product_code NUMBER(8),
  intc_broker_code NUMBER(8)
);