CREATE TABLE "TEST_VSTSRedgate".trtran001 (
  deal_company_code NUMBER(8) NOT NULL,
  deal_deal_number VARCHAR2(25 BYTE) NOT NULL,
  deal_serial_number NUMBER(5) NOT NULL,
  deal_execute_date DATE NOT NULL,
  deal_hedge_trade NUMBER(8) NOT NULL,
  deal_buy_sell NUMBER(8) NOT NULL,
  deal_swap_outright NUMBER(8) NOT NULL,
  deal_deal_type NUMBER(8) NOT NULL,
  deal_counter_party NUMBER(8) NOT NULL,
  deal_base_currency NUMBER(8) NOT NULL,
  deal_other_currency NUMBER(8) NOT NULL,
  deal_exchange_rate NUMBER(15,6) NOT NULL,
  deal_local_rate NUMBER(15,6),
  deal_base_amount NUMBER(15,2) NOT NULL,
  deal_other_amount NUMBER(15,2),
  deal_amount_local NUMBER(15,2) NOT NULL,
  deal_maturity_code NUMBER(8) NOT NULL,
  deal_maturity_from DATE,
  deal_maturity_date DATE NOT NULL,
  deal_maturity_month NUMBER(2),
  deal_user_id VARCHAR2(30 BYTE) NOT NULL,
  deal_confirm_date DATE,
  deal_dealer_remarks VARCHAR2(512 BYTE),
  deal_time_stamp VARCHAR2(25 BYTE),
  deal_execute_time VARCHAR2(10 BYTE),
  deal_confirm_time VARCHAR2(10 BYTE),
  deal_process_complete NUMBER(8) DEFAULT 12400002 NOT NULL,
  deal_complete_date DATE,
  deal_create_date DATE NOT NULL,
  deal_entry_detail XMLTYPE,
  deal_record_status NUMBER(8) NOT NULL,
  deal_user_reference VARCHAR2(50 BYTE),
  deal_fixed_option NUMBER(8),
  deal_delivary_no NUMBER(8),
  deal_forward_rate NUMBER(15,6),
  deal_spot_rate NUMBER(15,6),
  deal_margin_rate NUMBER(15,6),
  deal_backup_deal NUMBER(8),
  deal_stop_loss NUMBER(15,6),
  deal_take_profit NUMBER(15,6),
  deal_init_code NUMBER(8),
  deal_bank_reference VARCHAR2(50 BYTE),
  deal_bo_remark VARCHAR2(1024 BYTE),
  deal_location_code NUMBER(8),
  deal_dealer_name VARCHAR2(50 BYTE),
  deal_counter_dealer VARCHAR2(50 BYTE),
  deal_direct_indirect NUMBER(8),
  CONSTRAINT pk_trtran001 PRIMARY KEY (deal_company_code,deal_deal_number,deal_serial_number)
);