CREATE TABLE "TEST_VSTSRedgate".trtran091b (
  iirm_irs_number VARCHAR2(25 BYTE) NOT NULL,
  iirm_serial_number NUMBER(5) NOT NULL,
  iirm_intstart_date DATE NOT NULL,
  iirm_intend_date DATE,
  iirm_base_rate NUMBER(15,6),
  iirm_spread NUMBER(15,6),
  iirm_final_rate NUMBER(15,6),
  iirm_interest_amount NUMBER(15,2),
  iirm_create_date DATE,
  iirm_add_date DATE,
  iirm_record_status NUMBER(8),
  iirm_process_complete NUMBER(8),
  iirm_complete_date DATE,
  iirm_settlement_date DATE,
  iirm_leg_serial NUMBER(5) NOT NULL,
  iirm_intfixing_date DATE,
  iirm_spot_rate NUMBER(15,6),
  iirm_converted_amount NUMBER(15,6),
  iirm_net_cashflow NUMBER(15,6),
  iirs_settlement_type NUMBER(8),
  iirs_forwarddeal_rate NUMBER(15,6),
  iirs_forwarddeal_amount NUMBER(15,2),
  iirs_spot_amount NUMBER(15,2),
  iirm_location_code NUMBER(8),
  CONSTRAINT trtran091b_pk PRIMARY KEY (iirm_irs_number,iirm_serial_number,iirm_leg_serial)
);