CREATE TABLE "TEST_VSTSRedgate".trtran015 (
  bank_company_code NUMBER(8) NOT NULL,
  bank_local_bank NUMBER(8) NOT NULL,
  bank_record_type NUMBER(8) NOT NULL,
  bank_limit_type NUMBER(8) NOT NULL,
  bank_effective_date DATE NOT NULL,
  bank_reference_number VARCHAR2(25 BYTE),
  bank_reference_date DATE,
  bank_opening_balance NUMBER(15,2),
  bank_tenor_type NUMBER(8),
  bank_limit_tenor NUMBER(5),
  bank_limit_amount NUMBER(15,2),
  bank_due_date DATE,
  bank_change_percentage NUMBER(3),
  bank_margin_rate NUMBER(15,2),
  bank_margin_amount NUMBER(15,2),
  bank_margin_reference VARCHAR2(50 BYTE),
  bank_create_date DATE NOT NULL,
  bank_entry_detail XMLTYPE,
  bank_record_status NUMBER(8) NOT NULL,
  bank_location_code NUMBER(8),
  bank_currency_code NUMBER(8),
  bank_portfolio NUMBER(8),
  CONSTRAINT pk_tftran015 PRIMARY KEY (bank_company_code,bank_local_bank,bank_record_type,bank_limit_type,bank_effective_date)
);