CREATE TABLE "TEST_VSTSRedgate".trtran008 (
  bcac_company_code NUMBER(8) NOT NULL,
  bcac_location_code NUMBER(8) NOT NULL,
  bcac_local_bank NUMBER(8) NOT NULL,
  bcac_voucher_number VARCHAR2(25 BYTE) NOT NULL,
  bcac_voucher_date DATE NOT NULL,
  bcac_crdr_code NUMBER(8) NOT NULL,
  bcac_account_head NUMBER(8) NOT NULL,
  bcac_voucher_type NUMBER(8) NOT NULL,
  bcac_local_merchant NUMBER(8) NOT NULL,
  bcac_voucher_reference VARCHAR2(25 BYTE),
  bcac_reference_serial NUMBER(5),
  bcac_voucher_currency NUMBER(8) NOT NULL,
  bcac_voucher_fcy NUMBER(15,4),
  bcac_voucher_rate NUMBER(15,4),
  bcac_voucher_inr NUMBER(15,2) NOT NULL,
  bcac_cheque_number VARCHAR2(10 BYTE),
  bcac_cheque_date DATE,
  bcac_voucher_detail VARCHAR2(100 BYTE),
  bcac_recon_flag NUMBER(8),
  bcac_create_date DATE NOT NULL,
  bcac_entry_detail XMLTYPE,
  bcac_record_status NUMBER(8) NOT NULL,
  bcac_account_number VARCHAR2(25 BYTE),
  bcac_record_type NUMBER(8),
  bcac_recon_date DATE,
  bcac_recon_inr NUMBER(15,2),
  bcac_recon_remarks VARCHAR2(100 BYTE),
  bcac_bank_reference VARCHAR2(50 BYTE),
  bcac_add_date DATE,
  bcac_batch_no VARCHAR2(25 BYTE),
  CONSTRAINT pk_trtran008 PRIMARY KEY (bcac_company_code,bcac_location_code,bcac_voucher_number)
);