CREATE TABLE "TEST_VSTSRedgate".trtran056 (
  gopt_company_code NUMBER(8) NOT NULL,
  gopt_deal_number VARCHAR2(25 BYTE) NOT NULL,
  gopt_serial_number NUMBER(5) NOT NULL,
  gopt_counter_party NUMBER(8) NOT NULL,
  gopt_trade_date DATE NOT NULL,
  gopt_fixing_day NUMBER(8) NOT NULL,
  gopt_effective_date DATE NOT NULL,
  gopt_termination_date DATE NOT NULL,
  gopt_currency_code NUMBER(8),
  gopt_base_amount NUMBER(15,2),
  gopt_product_code NUMBER(8),
  gopt_uom_code NUMBER(8),
  gopt_structure_type NUMBER(8),
  gopt_rate_type NUMBER(8),
  gopt_notional_quantity NUMBER(15,2),
  gopt_leverage_quantity NUMBER(15,2),
  gopt_delivery_period NUMBER(5),
  gopt_delivery_type NUMBER(8),
  gopt_knockout_event NUMBER(8),
  gopt_target_value NUMBER(15,2),
  gopt_target_quantity NUMBER(15,2),
  gopt_target_count NUMBER(5),
  gopt_expiry_date DATE,
  gopt_strike1_price NUMBER(15,2),
  gopt_strike2_price NUMBER(15,2),
  gopt_strike3_price NUMBER(15,2),
  gopt_strike4_price NUMBER(15,2),
  gopt_dormant_code NUMBER(8),
  gopt_premium_fcy NUMBER(15,2),
  gopt_premium_exrate NUMBER(15,4),
  gopt_premium_inr NUMBER(15,2),
  gopt_present_status NUMBER(8),
  gopt_user_remarks VARCHAR2(1000 BYTE),
  gopt_process_complete NUMBER(8),
  gopt_completion_date DATE,
  gopt_add_date DATE,
  gopt_create_date DATE,
  gopt_entry_details XMLTYPE,
  gopt_record_status NUMBER(8)
);