CREATE TABLE "TEST_VSTSRedgate".trtran092 (
  iirf_company_code NUMBER(8) NOT NULL,
  iirf_location_code NUMBER(8),
  iirf_deal_number VARCHAR2(25 BYTE) NOT NULL,
  iirf_user_reference VARCHAR2(25 BYTE),
  iirf_execute_date DATE NOT NULL,
  iirf_execute_time VARCHAR2(10 BYTE) NOT NULL,
  iirf_exchange_code NUMBER(8) NOT NULL,
  iirf_broker_code NUMBER(8) NOT NULL,
  iirf_currency_code NUMBER(8) NOT NULL,
  iirf_future_price NUMBER(15,6) NOT NULL,
  iirf_base_amount NUMBER(15,2) NOT NULL,
  iirf_hedge_trade NUMBER(8) NOT NULL,
  iirf_buy_sell NUMBER(8) NOT NULL,
  iirf_product_code NUMBER(8) NOT NULL,
  iirf_local_bank NUMBER(8) NOT NULL,
  iirf_lot_numbers NUMBER(10) NOT NULL,
  iirf_lot_quantity NUMBER(10) NOT NULL,
  iirf_lot_price NUMBER(15,4) NOT NULL,
  iirf_margin_rate NUMBER(5,2) NOT NULL,
  iirf_margin_amount NUMBER(15,2) NOT NULL,
  iirf_brokerage_rate NUMBER(5,2) NOT NULL,
  iirf_brokerage_amount NUMBER(15,2) NOT NULL,
  iirf_service_tax NUMBER(15,2),
  iirf_transaction_cost NUMBER(15,2),
  iirf_other_charges NUMBER(15,2),
  iirf_maturity_month NUMBER(6) NOT NULL,
  iirf_maturity_date DATE NOT NULL,
  iirf_dealer_remark VARCHAR2(1000 BYTE),
  iirf_bo_remark VARCHAR2(1000 BYTE),
  iirf_confirm_date DATE,
  iirf_time_stamp VARCHAR2(25 BYTE) NOT NULL,
  iirf_process_complete NUMBER(8) NOT NULL,
  iirf_complete_date DATE,
  iirf_create_date DATE NOT NULL,
  iirf_add_date DATE NOT NULL,
  iirf_entry_detail XMLTYPE,
  iirf_record_status NUMBER(8) NOT NULL,
  iirf_portfolio NUMBER(8),
  iirf_sub_portfolio NUMBER(8),
  CONSTRAINT pk_trtran092 PRIMARY KEY (iirf_company_code,iirf_deal_number)
);