CREATE TABLE "TEST_VSTSRedgate".trtran045 (
  bcrd_company_code NUMBER(8) NOT NULL,
  bcrd_location_code NUMBER(8) NOT NULL,
  bcrd_buyers_credit VARCHAR2(30 BYTE) NOT NULL,
  bcrd_request_date DATE,
  bcrd_local_bank NUMBER(8) NOT NULL,
  bcrd_foreign_bank NUMBER(8),
  bcrd_agent_code NUMBER(8),
  bcrd_currency_code NUMBER(8) NOT NULL,
  bcrd_sanctioned_fcy NUMBER(15,4) NOT NULL,
  bcrd_conversion_rate NUMBER(15,4) NOT NULL,
  bcrd_sanctioned_inr NUMBER(15,2) NOT NULL,
  bcrd_sanction_reference VARCHAR2(25 BYTE),
  bcrd_sanction_date DATE,
  bcrd_product_detail VARCHAR2(50 BYTE),
  bcrd_noof_days NUMBER(8) NOT NULL,
  bcrd_due_date DATE NOT NULL,
  bcrd_libor_rate NUMBER(15,6),
  bcrd_interest_spread NUMBER(15,6),
  bcrd_interest_rate NUMBER(15,6) NOT NULL,
  bcrd_interest_fcy NUMBER(15,2),
  bcrd_noof_days1 NUMBER(8),
  bcrd_due_date1 DATE,
  bcrd_libor_rate1 NUMBER(15,6),
  bcrd_interest_spread1 NUMBER(15,6),
  bcrd_interest_rate1 NUMBER(15,6),
  bcrd_interest_fcy1 NUMBER(15,2),
  bcrd_fcharges_fcy NUMBER(15,4),
  bcrd_fcharges_inr NUMBER(15,2),
  bcrd_bcharges_inr NUMBER(15,2),
  bcrd_bcharges1_inr NUMBER(15,2),
  bcrd_total_charges NUMBER(15,2),
  bcrd_repaid_date DATE,
  bcrd_repaid_rate NUMBER(15,4),
  bcrd_loan_remarks VARCHAR2(100 BYTE),
  bcrd_create_date DATE NOT NULL,
  bcrd_entry_detail XMLTYPE,
  bcrd_record_status NUMBER(8) NOT NULL,
  bcrd_hedge_reference VARCHAR2(25 BYTE),
  bcrd_hedge_date DATE,
  bcrd_hedge_rate NUMBER(15,4),
  bcrd_hedge_amount NUMBER(15,2),
  bcrd_process_complete NUMBER(8),
  bcrd_completion_date DATE,
  bcrd_spot_rate NUMBER(15,4),
  bcrd_forward_rate NUMBER(15,4),
  bcrd_margin_rate NUMBER(15,4),
  fdrf_currency_code NUMBER(8),
  fdrf_scheme_code NUMBER(8),
  fdrf_open_date DATE,
  fdrf_interest_plan NUMBER(8),
  fdrf_period_months NUMBER(4),
  fdrf_period_monthsin NUMBER(8),
  fdrf_period_days NUMBER(4),
  fdrf_period_daysin NUMBER(8),
  fdrf_addtional_interest NUMBER(5,2),
  fdrf_periodical_int NUMBER(15,2),
  fdrf_int_paidamt NUMBER(15,2),
  fdrf_tds_deducted_amt NUMBER(15,2),
  fdrf_interest_type NUMBER(8),
  fdrf_maturity_type NUMBER(8),
  fdrf_compounding_type NUMBER(8),
  fdrf_payment_frequency NUMBER(8),
  fdrf_autorenew_acno NUMBER(8),
  fdrf_mail_id VARCHAR2(100 BYTE),
  fdrf_user_remarks VARCHAR2(200 BYTE),
  fdrf_account_status NUMBER(8),
  fdrf_intcr_account NUMBER(15),
  fdrf_tds_plan NUMBER(8),
  fdrf_tds_drac NUMBER(15),
  bcrd_subproduct_code NUMBER(8),
  bcrd_product_category NUMBER(8),
  bcrd_portfolio VARCHAR2(50 BYTE),
  bcrd_product_type VARCHAR2(50 BYTE),
  CONSTRAINT pk_trtran045 UNIQUE (bcrd_company_code,bcrd_location_code,bcrd_buyers_credit)
);