CREATE MATERIALIZED VIEW "TEST_VSTSRedgate".md_regex_schema_mview (project_id,connection_id,connection_name,catalog_id,catalog_name,schema_id,schema_name,item,"VALUE")
ORGANIZATION HEAP 
AS SELECT  PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM, SUM(VALUE) "VALUE" from MD_REGEX_MVIEW
        group by PROJECT_NAME, PROJECT_ID, CONNECTION_ID, CONNECTION_NAME,CATALOG_ID,
        CATALOG_NAME,SCHEMA_ID,SCHEMA_NAME, ITEM;